#ifndef GUARD_CARD_LABEL_DATA_H
#define GUARD_CARD_LABEL_DATA_H

#include "card_ui_types.h"
#include "types.h"

enum HcEffectId {
    HC_EFFECT_NONE,
    HC_EFFECT_INCREMENTOR,
    HC_EFFECT_ATTACK_BRACER,
    HC_EFFECT_COMBO_PLUS,
    HC_EFFECT_FIRE_BOOST,
    HC_EFFECT_COMBO_FINISH,
    HC_EFFECT_DRAW,
    HC_EFFECT_CARDBLIND,
    HC_EFFECT_BERSERK,
    HC_EFFECT_QUICKLOAD,
    HC_EFFECT_COMBO_PLUS_2,
    HC_EFFECT_BLIZZARD_BOOST,
    HC_EFFECT_THUNDER_BOOST,
    HC_EFFECT_CURE_BOOST,
    HC_EFFECT_PROTECT,
    HC_EFFECT_SLEIGHT_LOCK,
    HC_EFFECT_RANDOM_VALUES,
    HC_EFFECT_ALL_ZEROS,
    HC_EFFECT_QUICK_RECOVERY,
    HC_EFFECT_VANISH,
    HC_EFFECT_LEAF_BRACER,
    HC_EFFECT_DECREMENTOR,
    HC_EFFECT_DECREMENTOR_2,
    HC_EFFECT_REGEN,
    HC_EFFECT_BIO,
    HC_EFFECT_DRAW_2,
    HC_EFFECT_SECOND_CHANCE,
    HC_EFFECT_AUTO_LIFE,
    HC_EFFECT_SLEIGHTBLIND,
    HC_EFFECT_ITEM_BRACER,
    HC_EFFECT_RELOAD_KINESIS,
    HC_EFFECT_RETROGRADE,
    HC_EFFECT_WIDE_ATTACK,
    HC_EFFECT_BERSERK_2,
    HC_EFFECT_WIDE_ATTACK_2,
    HC_EFFECT_DRAIN,
    HC_EFFECT_BACK_ATTACK,
    HC_EFFECT_RANDOM_FLUSH,
    HC_EFFECT_MAGIC_BOOST,
    HC_EFFECT_SUMMON_BOOST,
    HC_EFFECT_AUTO_RELOAD,
    HC_EFFECT_DISPEL,
    HC_EFFECT_HYPER_HEALING,
    HC_EFFECT_OVERDRIVE,
    HC_EFFECT_ATTACK_HASTE,
    HC_EFFECT_MIMIC,
    HC_EFFECT_SHELL,
    HC_EFFECT_DOUBLE_SLEIGHT,
    HC_EFFECT_VALUE_BREAK,
    HC_EFFECT_WARP_BREAK,
    HC_EFFECT_DASH,
    HC_EFFECT_GUARD,
    HC_EFFECT_MIMIC_2,
    HC_EFFECT_FLOAT,
    HC_EFFECT_INCREMENTOR_2
};

typedef struct HcEffectDef {
#ifdef VERSION_EU
    void** tiles;
    void*** sprites;
#else
    void* tiles;
    u32 tilesSize;
    void** sprites;
#endif
    u16 spriteIndex;
    u16 count;
} HcEffectDef;

extern const HcEffectDef gHcEffectDefs[];
extern const SpriteFrameResourceDef gStockNameSprites[];

#endif
