/**
 * btl_collision.c
 * Attack Hit Checks and Colliders
 */

#include "engine_math.h"
#include "listpool.h"
#include "battle.h"
#include "btl_effect.h"
#include "songs.h"
#include "battle_actor.h"
#include "battle_actor_types.h"
#include "battle_work.h"
#include "field_state.h"
#include "fld_types.h"
#include "m4a_song.h"
#include "types.h"
#include <stddef.h>

static const BattleAttackDef sBattleAttackDefs[330] = {
    { 256, 204, 0, 3, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 1024, 384, 8, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON },
    { 384, 384, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 256, 20, BgFxStartRikuHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 512, 0, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, -768, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, -256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 256, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2048, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 896, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 640, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 896, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 1536, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 2560, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 3840, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 1024, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2048, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3328, 0, 0, 20, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 51, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 102, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 179, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 512, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC },
    { 896, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_MAGIC },
    { 1536, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_MAGIC },
    { 768, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2304, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 256, 8, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 0, 256, 8, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, BgFxStartSoraHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 6400, 384, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 76, 0, 2, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 332, 384, 2, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, -921, 384, 13, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 3328, 0, 0, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 460, -768, 8, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 332, 307, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 20, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 5120, 384, 256, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 128, 128, 20, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 0, 0, 0, 20, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_WARP_AWAY | ATTACK_FLAG_NO_EXP | ATTACK_FLAG_IS_SLEIGHT },
    { 640, 204, 0, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2048, 0, 0, 8, BgFxStartSoraHit, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_THUNDER },
    { 179, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1280, 0, 0, 4, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2048, 0, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 0, 844, 332, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1024, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 0, 0, 0, 0, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_INFLICT_TERROR | ATTACK_FLAG_IS_SLEIGHT },
    { 640, 0, 384, 4, BgFxStartSoraHit, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 2048, 0, 844, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 3328, 256, 256, 4, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_BIND },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1152, 0, 256, 8, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 384, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 384, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 512, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 4608, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2560, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3840, 0, 0, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 1024, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 256, 256, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1536, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 4608, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2560, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3840, 0, 0, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 1024, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 76, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 230, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 2048, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1536, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 102, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 512, 384, 256, 8, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 4, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 0, 256, 30, BgFxStartFriendHit, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2560, 486, 384, 30, BgFxStartFriendHit, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 30, NULL, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 30, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 0, 0, 30, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 204, 0, 0, NULL, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 51, 51, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 76, 76, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 128, 128, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 460, 460, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 460, 460, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 0, 0, 0, BgFxStartFriendHit, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 0, 0, 0, BgFxStartFriendHit, ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 0, 0, 0, NULL, ATTACK_FLAG_WARP_AWAY },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 76, 76, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 640, 128, 128, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 512, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, -256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 512, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 179, 358, 179, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 384, 384, 0, BgFxStartEnemyHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 128, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 192, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 15, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 51, 512, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 320, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 153, 332, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 409, 0, 15, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 512, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, -256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 76, 0, 0, 4, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 0, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 51, 51, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 256, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 332, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 0, 384, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 307, 256, 256, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 64, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 153, 332, 204, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 307, 256, 256, 8, NULL, ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 281, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 307, 358, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 102, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 153, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON },
    { 384, 128, 128, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 0, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 460, 435, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 153, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 332, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 819, 435, 0, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_FORWARD_KNOCKBACK },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 332, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 384, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 76, 0, 256, 0, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, 1152, 15, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 204, 563, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 332, 640, 0, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 460, 256, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 76, 256, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 460, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 256, 20, BgFxStartRikuHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 640, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, -256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 0, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 128, 256, 0, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 3, BgFxStartFireHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 768, 0, 128, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 102, 384, 128, 8, BgFxStartThunderHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 128, 384, 8, BgFxStartThunderHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 102, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 204, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 128, 0, 256, 0, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 204, 256, 256, 8, BgFxStartBlizzardHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 0, 0, 8, BgFxStartBlizzardHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 128, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 204, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 0, 0, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 89, 512, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 460, 332, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 0, 0, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 307, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 179, 179, 3, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 307, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
};

static ListPool sUnk_020348E8;
static ListPool sUnk_020348F8;
static ListPool sUnk_02034908;
static ListPool sUnk_02034918;

u8 CanAttackBoxHitBtlObj(BtlObj* p, s32 x, s32 y, s32 z, s16 a, s16 b, s16 c) {
    BtlObj* q = p->parent;
    u64 f;

    if (q != NULL) {
        f = q->flags | p->flags;
    } else {
        f = p->flags;
        q = p;
    }

    if (f & (BTLOBJ_FLAG_HIT_LOCKED | BTLOBJ_FLAG_INTANGIBLE | BTLOBJ_FLAG_UNHITTABLE)) {
        return 0;
    }

    if (x - (a << 8) > p->x + (p->radiusX << 8)) {
        return 0;
    }

    if (x + (a << 8) < p->x - (p->radiusX << 8)) {
        return 0;
    }

    if (y - (b << 8) > p->y + (p->radiusY << 8)) {
        return 0;
    }

    if (y + (b << 8) < p->y - (p->radiusY << 8)) {
        return 0;
    }

    if (z - (c << 8) > p->z) {
        return 0;
    }

    if (z + (c << 8) < p->z - (p->height << 8)) {
        return 0;
    }

    if (q->invincibleTimer > 0) {
        return 0;
    }

    return 1;
}

void AbsorbAttack(BtlObj* a, BtlObj* b, const BattleAttackDef* c) {
    gBtlWork->pendingHitStop = 8;
    a->damage = -((b->attack * c->power) >> 8);
    a->flags |= BTLOBJ_FLAG_HEAL_PENDING;
}

s32 ResolveAttackHit(BtlObj* hit, s32 index) {
    const BattleAttackDef* attack = &sBattleAttackDefs[index];
    s32 scale = gBtlWork->damageScale;
    BtlObj* target;
    BtlObj* source;

    if (hit->parent != NULL) {
        target = hit->parent;
    } else {
        target = hit;
    }

    target->hitFlags = attack->flags;
    target->hitAttack = index;

    if (attack->flags & ATTACK_FLAG_WARP_AWAY) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_WARP) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        if (attack->flags & ATTACK_FLAG_NO_EXP) target->exp = 0;

        target->flags |= BTLOBJ_FLAG_WARP_PENDING;
        return 0;
    }

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gRikuBtlWork->actor;
    } else if (gBtlWork->flags & BTL_FLAG_HUM_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gBtlWork->actor3;
    } else {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gBtlWork->actor3;
    }

    if (source->btl != NULL) {
        switch (source->btl->hcEffect) {
        case 35:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) != ATTACK_FLAG_KIND_WEAPON) break;

            if (hit->flags & BTLOBJ_FLAG_INVULNERABLE) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) && (hit->flags & BTLOBJ_FLAG_GUARD_PHYSICAL)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) && (hit->flags & BTLOBJ_FLAG_GUARD_NEUTRAL)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_FIRE) && (hit->flags & BTLOBJ_FLAG_IMMUNE_FIRE)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) && (hit->flags & BTLOBJ_FLAG_IMMUNE_BLIZZARD)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) && (hit->flags & BTLOBJ_FLAG_IMMUNE_THUNDER)) break;

            if (hit->badStatus == BAD_STATUS_STOP) break;

            {
                s16 drain = target->hp >> 3;

                if (drain <= 0) drain = 1;
                else if (drain > 20) drain = 20;

                source->hp += drain;
                target->hp -= drain;

                if (target->hp <= 0) target->hp = 1;

                if (source->hp > source->maxHp) source->hp = source->maxHp;

                CreateBtlPopTask(source, 10);
                target->exp -= target->exp >> 2;
            }

            break;
        case 43:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            }

            break;
        case 8:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON && source->hp < (source->maxHp >> 2)) {
                scale = scale != 0 ? (scale * 512) >> 8 : 512;
            }

            break;
        case 4:
            if (attack->flags & ATTACK_FLAG_ELEMENT_FIRE) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            }

            break;
        case 11:
            if (attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            }

            break;
        case 12:
            if (attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            }

            break;
        case 38:
            if (attack->flags & ATTACK_FLAG_KIND_MAGIC) {
                scale = scale != 0 ? (scale * 332) >> 8 : 332;
            }

            break;
        case 39:
            if (attack->flags & ATTACK_FLAG_KIND_SUMMON) {
                scale = scale != 0 ? (scale * 332) >> 8 : 332;
            }

            break;
        case 36:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON) {
                if (source->flags & BTLOBJ_FLAG_FACING_LEFT) {
                    if ((hit->flags & BTLOBJ_FLAG_FACING_LEFT) && hit->x < source->x) {
                        scale = scale != 0 ? (scale * 512) >> 8 : 512;
                    }
                } else if (!(hit->flags & BTLOBJ_FLAG_FACING_LEFT) && source->x < hit->x) {
                    scale = scale != 0 ? (scale * 512) >> 8 : 512;
                }
            }

            break;
        }
    }

    if (target->btl != NULL) {
        switch (target->btl->hcEffect) {
        case 14:
            if (attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) {
                CreateBtlPopTask(hit, 0);
                scale = scale != 0 ? (scale * 128) >> 8 : 128;
            }

            break;
        case 46:
            target->btl->hcEffectCount--;

#ifdef VERSION_EU
            if (attack->flags & ATTACK_FLAG_KIND_MAGIC)
#endif
            {
                scale = scale != 0 ? (scale * 128) >> 8 : 128;
            }

            break;
        }
    }

    if (attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) {
        if (hit->flags & BTLOBJ_FLAG_GUARD_PHYSICAL) {
            switch ((u32)hit->kind) {
            case 7:
            case 28:
            case 50:
            case 52:
                m4aSongNumStart(SONG_BTL_GARD);
                break;
            default:
                m4aSongNumStart(SONG_BTL_RB_GARD);
                break;
            }

            hit->invincibleTimer = 30;
            CreateBtlPopTask(hit, 0);
            BgFxStartGuard(gBtlWork->x3, gBtlWork->y3, hit->z - hit->centerHeight * 256);
            return 2;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_PHYSICAL) {
            scale = scale != 0 ? (scale * 128) >> 8 : 128;
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_PHYSICAL) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS | BTLOBJ_FLAG_PLAYER)) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) {
        if (hit->flags & BTLOBJ_FLAG_GUARD_NEUTRAL) {
            switch ((u32)hit->kind) {
            case 7:
            case 28:
            case 50:
                m4aSongNumStart(SONG_BTL_GARD);
                break;
            default:
                m4aSongNumStart(SONG_BTL_RB_GARD);
                break;
            }

            hit->invincibleTimer = 30;
            CreateBtlPopTask(hit, 0);
            BgFxStartGuard(gBtlWork->x3, gBtlWork->y3, hit->z - hit->centerHeight * 256);
            return 2;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_NEUTRAL) {
            scale = scale != 0 ? (scale * 128) >> 8 : 128;
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_NEUTRAL) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS | BTLOBJ_FLAG_PLAYER)) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_FIRE) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_FIRE) {
            AbsorbAttack(target, source, attack);
            return 1;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_FIRE) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_FIRE) {
            scale = scale != 0 ? (scale * 128) >> 8 : 128;
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_FIRE) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_BLIZZARD) {
            AbsorbAttack(target, source, attack);
            return 1;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_BLIZZARD) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_BLIZZARD) {
            scale = scale != 0 ? (scale * 128) >> 8 : 128;
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_BLIZZARD) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_THUNDER) {
            AbsorbAttack(target, source, attack);
            return 1;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_THUNDER) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_THUNDER) {
            scale = scale != 0 ? (scale * 128) >> 8 : 128;
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_THUNDER) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * 384) >> 8 : 384;
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_INFLICT_STOP) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_STOP) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        hit->flags |= BTLOBJ_FLAG_STOP_PENDING;

        if (scale == 0) hit->damage = ((u32)attack->power * 15) >> 6;
        else hit->damage = (((attack->power * 60) >> 8) * scale) >> 8;

        gBtlWork->pendingHitStop = (u8)attack->hitStop;
        hit->invincibleTimer = 30;
        return 1;
    }

    if (hit->flags & BTLOBJ_FLAG_INVULNERABLE) {
        CreateBtlPopTask(hit, 0);
        hit->invincibleTimer = 30;
        gBtlWork->hitStop = (u8)attack->hitStop;
        return 1;
    }

    if (attack->flags & ATTACK_FLAG_INFLICT_STUN) {
        target->flags |= BTLOBJ_FLAG_STUN_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_TERROR) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_TERROR) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        target->flags |= BTLOBJ_FLAG_TERROR_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_CONFUSE) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_CONFUSE) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        target->flags |= BTLOBJ_FLAG_CONFUSE_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_BIND) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_BIND) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        target->flags |= BTLOBJ_FLAG_BIND_PENDING;
    }

    if (attack->flags & ATTACK_FLAG_INFLICT_GRAVITY) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_GRAVITY) {
            CreateBtlPopTask(hit, 0);
            hit->invincibleTimer = 30;
            return 2;
        }

        target->flags |= BTLOBJ_FLAG_GRAVITY_PENDING;

        if (attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) {
            if (scale == 0) target->damage = (source->attack * attack->power) >> 8;
            else target->damage = (((source->attack * attack->power) >> 8) * scale) >> 8;
        } else {
            if (scale == 0) target->damage = (target->hp * attack->power) >> 8;
            else target->damage = (((target->hp * attack->power) >> 8) * scale) >> 8;

            if (target->flags & BTLOBJ_FLAG_PLAYER) {
                target->damage = (target->damage * 76) >> 8;
            }
        }
    } else {
        if (scale == 0) target->damage = (source->attack * attack->power) >> 8;
        else target->damage = (((source->attack * attack->power) >> 8) * scale) >> 8;

        if (target->damage == 0 && attack->power > 0) target->damage = 1;
    }

    if (target->btl != NULL && target->btl->hcEffect == 26) {
        if (target->hp > 1 && target->hp - target->damage <= 0) {
            target->damage = target->hp - 1;
            target->invincibleTimer = 60;
            CreateBtlPopTask(target, 0);
            target->btl->hcEffectCount--;
        }
    }

    target->flags |= BTLOBJ_FLAG_DAMAGE_PENDING;
    gBtlWork->pendingHitStop = (u8)attack->hitStop;
    target->knockbackSpeed = attack->knockbackSpeed;
    target->knockbackLift = attack->knockbackLift;

    if (attack->flags & ATTACK_FLAG_FORWARD_KNOCKBACK) {
        if (source->flags & BTLOBJ_FLAG_FACING_LEFT) target->angle = 192;
        else target->angle = 64;
    } else if (attack->flags & ATTACK_FLAG_RADIAL_KNOCKBACK) {
        target->angle = GetAngle(gBtlWork->x3, gBtlWork->y3, target->x, target->y);
    } else {
        target->angle = GetAngle(source->x, source->y, target->x, target->y);
    }

    return 1;
}

u8 TestAttackBox(s32 x, s32 y, s32 z, s16 a, s16 b, s16 c) {
    BtlObj* o;

    gBtlWork->areaUpdated = 1;
    gBtlWork->x3 = x;
    gBtlWork->y3 = y;
    gBtlWork->z3 = z;
    gBtlWork->areaHalfX = a;
    gBtlWork->areaHalfY = b;
    gBtlWork->areaHalfZ = c;

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
            o = gRikuBtlWork->actor;
        } else {
            o = gBtlWork->actor;
        }

        if (CanAttackBoxHitBtlObj(o, x, y, z, a, b, c)) {
            return 1;
        }
    } else if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
        o = ListPoolFirst(&gBtlWork->pool);

        while (o != NULL) {
            if (CanAttackBoxHitBtlObj(o, x, y, z, a, b, c)) {
                return 1;
            }

            o = ListPoolNext(&o->node);
        }

        return 0;
    } else {
        o = gBtlWork->actor;

        if (CanAttackBoxHitBtlObj(o, x, y, z, a, b, c)) {
            return 1;
        }
    }

    return 0;
}

s32 ApplyAttackToBtlObj(s32 a, BtlObj* b) {
    return ResolveAttackHit(b, a);
}

s32 ApplyAttackBox(s32 a, s32 x, s32 y, s32 z, s16 p, s16 q, s16 r) {
    const BattleAttackDef* t;
    BtlObj* o;
    s32 sx;
    s32 sy;
    s32 sz;
    s16 cnt;
    s32 flag;
    s32 n;
    s32 res;
    s32 r2;

    t = &sBattleAttackDefs[a];
    cnt = 0;
    flag = 0;
    gBtlWork->areaUpdated = 1;
    gBtlWork->x3 = x;
    gBtlWork->y3 = y;
    gBtlWork->z3 = z;
    gBtlWork->areaHalfX = p;
    gBtlWork->areaHalfY = q;
    gBtlWork->areaHalfZ = r;

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
            o = gRikuBtlWork->actor;
        } else {
            o = gBtlWork->actor;
        }

        if (CanAttackBoxHitBtlObj(o, x, y, z, p, q, r)) {
            res = ResolveAttackHit(o, a);

            if (res == 1) {
                if (t->hitEffect != NULL) {
                    t->hitEffect(o->x, o->y, o->z);
                }
            }

            return res;
        }
    } else if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
        o = ListPoolFirst(&gBtlWork->pool);
        sz = 0;
        sy = 0;
        sx = 0;

        while (o != NULL) {
            if (!CanAttackBoxHitBtlObj(o, x, y, z, p, q, r)) {
                o = ListPoolNext(&o->node);
                continue;
            }

            r2 = ResolveAttackHit(o, a);

            if (r2 == 1) {
                sx += o->x;
                sy += o->y;
                sz += o->z;
                cnt++;

                if (t->flags & ATTACK_FLAG_SINGLE_TARGET) {
                    break;
                }
            } else if (r2 == 2) {
                flag = 1;
            }

            o = ListPoolNext(&o->node);
        }

        if (flag) {
            return 2;
        }

        n = cnt;

        if (n > 0) {
            if (t->hitEffect != NULL) {
                sx /= n;
                sy /= n;
                sz /= n;
                t->hitEffect(sx, sy, sz);
            }

            return 1;
        }
    } else {
        o = gBtlWork->actor;

        if (CanAttackBoxHitBtlObj(o, x, y, z, p, q, r)) {
            res = ResolveAttackHit(o, a);

            if (res == 1) {
                if (t->hitEffect != NULL) {
                    t->hitEffect(o->x, o->y, o->z);
                }
            }

            return res;
        }
    }

    return 0;
}

s32 ApplyAttackAt(s32 a, s32 b, s32 c, s32 d) {
    return ApplyAttackBox(a, b, c, d, 16, 16, 16);
}

s32 ApplyAttackInFront(BtlObj* p, s16 h, s32 c) {
    if (p->flags & BTLOBJ_FLAG_FACING_LEFT) {
        return ApplyAttackAt(p->x - (h << 8), p->y, p->z - (p->height >> 1), c);
    } else {
        return ApplyAttackAt(p->x + (h << 8), p->y, p->z - (p->height >> 1), c);
    }
}

void FldObjRegister(FldObj* p) {
    ListNodeInit(&p->node, &gFieldState->actor.pool, p);
    ListPoolAppend(&p->node, &gFieldState->actor.pool);
}

void FldObjUnregister(FldObj* p) {
    ListPoolRemove(&p->node, &gFieldState->actor.pool);
}

void func_08012214() {
}

void* ColliderGetPool(u32 type) {
    switch (type) {
    case 1:
    case 2:
    case 4:
    case 9:
        return &sUnk_020348E8;
    case 3:
        return &sUnk_020348F8;
    case 5:
    case 7:
    case 8:
    case 10:
    case 11:
    case 12:
        return &sUnk_02034908;
    }

    return &sUnk_02034918;
}

void ColliderPoolsInit() {
    ListPoolInit(&sUnk_020348E8);
    ListPoolInit(&sUnk_020348F8);
    ListPoolInit(&sUnk_02034908);
    ListPoolInit(&sUnk_02034918);
}

void ColliderInit(Collider* p, u32 type, u16 r, u16 h) {
    void* pool;
    p->otherType = 0;
    p->colliding = 0;
    p->standFlags = 0;
    p->flags = 0;
    p->radius = r << 8;
    p->height = h << 8;
    p->type = type;
    p->self = p;
    p->touchedTypes = 0;
    pool = ColliderGetPool(type);

    switch (type) {
    case 6:
    case 7:
        p->flags |= COLLIDER_FLAG_IS_PLATFORM;
        break;
    }

    ListNodeInit(&p->node, pool, p);
    ListPoolAppend(&p->node, pool);
}

void ColliderUnregister(Collider* p) {
    Collider* q = p->self;

    if (q == p) {
        ListPoolRemove(&q->node, ColliderGetPool(q->type));
    }
}

void ColliderSetPosition(Collider* p, s32 a, s32 b, s32 c) {
    p->x = a;
    p->y = b * 2;
    p->z = c;
}

void ColliderClearPoolContacts(ListPool* pool) {
    Collider* p = ListPoolFirst(pool);

    while (p != NULL) {
        p->colliding = 0;
        p->touchedTypes = 0;
        p->standFlags = 0;
        p = ListPoolNext(&p->node);
    }
}

void ColliderCheckPoolPairs(ListPool* a, ListPool* b) {
    Collider* p;
    Collider* q;
    s32 sum;
    s32 dx;
    s32 dy;
    s32 pen;
    s32 dz;
    s32 t;
    u8 angle;

    p = ListPoolFirst(a);

    while (p != NULL) {
        q = ListPoolLast(b);

        while (q != NULL && p != q) {
            sum = p->radius + q->radius;
            dx = p->x - q->x;

            if (dx < 0) {
                dx = q->x - p->x;
            }

            dy = p->y - q->y;

            if (dy < 0) {
                dy = q->y - p->y;
            }

            if (dx < sum && dy < sum) {
                pen = sum - Sqrt8(((dx * dx) >> 8) + ((dy * dy) >> 8));

                if (pen > 0) {
                    dz = p->z - q->z;

                    if (dz < p->height && -dz < q->height) {
                        q->colliding = 1;
                        p->colliding = 1;
                        p->otherType = q->type;
                        q->otherType = p->type;
                        p->touchedTypes |= 1 << q->type;
                        q->touchedTypes |= 1 << p->type;
                        angle = GetAngle(p->x, p->y, q->x, q->y);
                        t = (pen * gSineTable[angle]) >> 8;
                        p->pushX = -t;
                        p->pushY = -((pen * -gSineTable[angle + 64]) >> 8);
                        p->other = q;
                        q->pushX = t;
                        q->pushY = -p->pushY;
                        q->other = p;

                        if (q->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            p->platformZ = q->z - q->height;
                            p->penetration = pen;
                            p->platformY = q->y >> 1;
                            p->platformX = q->x;
                        }

                        if (p->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            q->platformZ = p->z - p->height;
                            q->penetration = pen;
                            q->platformY = p->y >> 1;
                            q->platformX = p->x;
                        }
                    } else {
                        if (q->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            if (q->z - q->height >= p->z) {
                                p->standFlags |= COLLIDER_STAND_OVER_PLATFORM;

                                if (q->z - q->height == p->z) {
                                    q->standFlags |= COLLIDER_STAND_STOOD_ON;
                                    p->touchedTypes |= 1 << q->type;
                                    q->touchedTypes |= 1 << p->type;
                                }

                                p->platformZ = q->z - q->height;
                                p->penetration = pen;
                                p->platformY = q->y >> 1;
                                p->platformX = q->x;
                                p->other = q;
                                p->otherType = q->type;
                                q->otherType = p->type;
                            }
                        }

                        if (p->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            if (p->z - p->height >= q->z) {
                                q->standFlags |= COLLIDER_STAND_OVER_PLATFORM;

                                if (p->z - p->height == q->z) {
                                    p->standFlags |= COLLIDER_STAND_STOOD_ON;
                                    p->touchedTypes |= 1 << q->type;
                                    q->touchedTypes |= 1 << p->type;
                                }

                                q->platformZ = p->z - p->height;
                                q->penetration = pen;
                                q->platformY = p->y >> 1;
                                q->platformX = p->x;
                                q->other = p;
                                p->otherType = q->type;
                                q->otherType = p->type;
                            }
                        }
                    }
                }
            }

            q = ListPoolPrev(&q->node);
        }

        p = ListPoolNext(&p->node);
    }
}

void ColliderUpdateAll() {
    ColliderClearPoolContacts(&sUnk_020348E8);
    ColliderClearPoolContacts(&sUnk_020348F8);
    ColliderClearPoolContacts(&sUnk_02034908);
    ColliderClearPoolContacts(&sUnk_02034918);
    ColliderCheckPoolPairs(&sUnk_020348E8, &sUnk_020348E8);
    ColliderCheckPoolPairs(&sUnk_020348F8, &sUnk_020348E8);
    ColliderCheckPoolPairs(&sUnk_02034908, &sUnk_020348E8);
    ColliderCheckPoolPairs(&sUnk_020348F8, &sUnk_020348F8);
    ColliderCheckPoolPairs(&sUnk_02034918, &sUnk_020348E8);
    ColliderCheckPoolPairs(&sUnk_02034918, &sUnk_020348F8);
}

void ColliderSetDisabled(Collider* p, u8 b) {
    if (b) {
        p->node.flags |= LIST_NODE_FLAG_SKIP;
        p->colliding = 0;
        p->standFlags = 0;
    } else {
        p->node.flags &= ~LIST_NODE_FLAG_SKIP;
    }
}

u8 ColliderIsColliding(Collider* p) {
    return p->colliding;
}

void ColliderSetRadius(Collider* p, u16 r) {
    p->radius = r << 8;
}

void ColliderSetHeight(Collider* p, u16 h) {
    p->height = h << 8;
}

u8 ColliderIsTouchingType(Collider* p, s32 bit) {
    if (p->touchedTypes & (1 << bit)) {
        return 1;
    }

    return 0;
}
