/**
 * btl_collision.c
 * Attack Hit Checks and Colliders
 */

#include "engine_math.h"
#include "listpool.h"
#include "battle.h"
#include "btl_effect.h"
#include "songs.h"
#include "battle_actor.h"
#include "battle_actor_types.h"
#include "battle_work.h"
#include "field_state.h"
#include "fld_types.h"
#include "m4a_song.h"
#include "types.h"
#include <stddef.h>
#include "card_label_data.h"
#include "enemy_ids.h"
#include "btl_collision.h"

static const BattleAttackDef sBattleAttackDefs[330] = {
    { 256, 204, 0, 3, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 1024, 384, 8, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON },
    { 384, 384, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 256, 20, BgFxStartRikuHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 512, 0, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, -768, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, -256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 256, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2048, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 896, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 640, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 896, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 896, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1024, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 204, 0, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 204, 204, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 1536, 384, 384, 16, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 2560, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 3840, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 1024, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2048, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3328, 0, 0, 20, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 51, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 102, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 179, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_MAGIC },
    { 512, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_MAGIC },
    { 896, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_MAGIC },
    { 1536, 0, 0, 15, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_MAGIC },
    { 768, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2304, -384, 384, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 256, 8, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 0, 256, 8, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, BgFxStartSoraHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 6400, 384, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 76, 0, 2, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 332, 384, 2, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, -921, 384, 13, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 3328, 0, 0, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 460, -768, 8, BgFxStartFlashHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 640, 332, 307, 3, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 20, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 5120, 384, 256, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 128, 128, 20, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 0, 0, 0, 20, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_WARP_AWAY | ATTACK_FLAG_NO_EXP | ATTACK_FLAG_IS_SLEIGHT },
    { 640, 204, 0, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2048, 0, 0, 8, BgFxStartSoraHit, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_THUNDER },
    { 179, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1280, 0, 0, 4, BgFxStartSoraHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2048, 0, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 0, 844, 332, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 1024, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 0, 0, 0, 0, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_INFLICT_TERROR | ATTACK_FLAG_IS_SLEIGHT },
    { 640, 0, 384, 4, BgFxStartSoraHit, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT },
    { 2048, 0, 844, 0, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_NO_DEATH_EFFECT | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 3328, 256, 256, 4, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_BIND },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1152, 0, 256, 8, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 384, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 384, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 512, 384, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 4608, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2560, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3840, 0, 0, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 1024, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 256, 256, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1536, 51, 51, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 3072, 76, 76, 15, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 4608, 128, 128, 20, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_FIRE },
    { 1280, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 2560, 0, 0, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 3840, 0, 0, 20, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 1024, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 2048, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 3072, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_THUNDER },
    { 25, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 76, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 230, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 2048, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 1536, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 1280, 0, 0, 8, NULL, ATTACK_FLAG_INFLICT_STOP | ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 102, 0, 0, 0, NULL, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_SUMMON },
    { 512, 384, 256, 8, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 4, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 0, 256, 30, BgFxStartFriendHit, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 2560, 486, 384, 30, BgFxStartFriendHit, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 30, NULL, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 0, 0, 30, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1280, 0, 0, 30, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 204, 0, 0, NULL, ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 51, 51, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 76, 76, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 128, 128, 0, NULL, ATTACK_FLAG_SINGLE_TARGET | ATTACK_FLAG_KIND_SUMMON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 460, 460, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 460, 460, 3, BgFxStartFriendHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 0, 0, 0, BgFxStartFriendHit, ATTACK_FLAG_INFLICT_GRAVITY | ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1024, 0, 0, 0, BgFxStartFriendHit, ATTACK_FLAG_KIND_FRIEND | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 1536, 0, 0, 0, NULL, ATTACK_FLAG_WARP_AWAY },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 76, 76, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 640, 128, 128, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 512, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_MAGIC },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 384, -256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 512, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 179, 358, 179, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 384, 384, 0, BgFxStartEnemyHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 128, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 192, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 15, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 51, 512, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 320, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 153, 332, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 409, 0, 15, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 512, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, -256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 76, 0, 0, 4, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 0, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 640, 51, 51, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 0, 0, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 256, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 332, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 0, 384, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 307, 256, 256, 15, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 64, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 204, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 15, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 153, 332, 204, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 307, 256, 256, 8, NULL, ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 281, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 307, 358, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 102, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 153, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON },
    { 384, 128, 128, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 512, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 0, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 460, 435, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 768, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 153, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 332, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 384, 819, 435, 0, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_FORWARD_KNOCKBACK },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 332, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 256, 0, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 384, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 768, 384, 384, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 76, 0, 256, 0, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, 1152, 15, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 30, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 204, 563, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 332, 640, 0, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 460, 256, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 76, 256, 256, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 256, 460, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 128, 256, 20, BgFxStartRikuHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 640, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 0, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 0, -256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, BgFxStartRikuHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 768, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_INFLICT_CONFUSE | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 0, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 128, 256, 0, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 3, BgFxStartFireHit, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 512, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_FIRE },
    { 768, 0, 128, 8, BgFxStartFireHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_FIRE },
    { 102, 384, 128, 8, BgFxStartThunderHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 128, 384, 8, BgFxStartThunderHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 102, 102, 0, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_THUNDER },
    { 204, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 128, 0, 256, 0, NULL, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 256, 256, 256, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_THUNDER },
    { 204, 256, 256, 8, BgFxStartBlizzardHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 384, 0, 0, 8, BgFxStartBlizzardHit, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_BLIZZARD },
    { 128, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 256, 256, 8, NULL, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 204, 256, 256, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 0, 0, 8, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 512, 0, 0, 0, NULL, ATTACK_FLAG_RADIAL_KNOCKBACK | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 89, 512, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 128, 0, 0, 8, NULL, ATTACK_FLAG_KIND_MAGIC | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 256, 460, 332, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 384, 0, 0, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 307, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 384, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
    { 256, 256, 256, 8, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON },
    { 256, 179, 179, 3, BgFxStartEnemyHit, ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_NEUTRAL },
    { 384, 307, 256, 12, BgFxStartEnemyHit, ATTACK_FLAG_INFLICT_STUN | ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_ELEMENT_PHYSICAL },
};

static ListPool sColliderPoolPlayer;
static ListPool sColliderPoolEnemy;
static ListPool sColliderPoolPlayerOnly;
static ListPool sColliderPoolObstacle;

u8 CanAttackBoxHitBtlObj(BtlObj* obj, s32 x, s32 y, s32 z, s16 halfX, s16 halfY, s16 halfZ) {
    BtlObj* owner = obj->parent;
    u64 flags;

    if (owner != NULL) {
        flags = owner->flags | obj->flags;
    } else {
        flags = obj->flags;
        owner = obj;
    }

    if (flags & (BTLOBJ_FLAG_HIT_LOCKED | BTLOBJ_FLAG_INTANGIBLE | BTLOBJ_FLAG_UNHITTABLE)) {
        return FALSE;
    }

    if (x - (halfX << 8) > obj->x + (obj->radiusX << 8)) {
        return FALSE;
    }

    if (x + (halfX << 8) < obj->x - (obj->radiusX << 8)) {
        return FALSE;
    }

    if (y - (halfY << 8) > obj->y + (obj->radiusY << 8)) {
        return FALSE;
    }

    if (y + (halfY << 8) < obj->y - (obj->radiusY << 8)) {
        return FALSE;
    }

    if (z - (halfZ << 8) > obj->z) {
        return FALSE;
    }

    if (z + (halfZ << 8) < obj->z - (obj->height << 8)) {
        return FALSE;
    }

    if (owner->invincibleTimer > 0) {
        return FALSE;
    }

    return TRUE;
}

void AbsorbAttack(BtlObj* target, BtlObj* source, const BattleAttackDef* attack) {
    gBtlWork->pendingHitStop = 8;
    target->damage = -((source->attack * attack->power) >> 8);
    target->flags |= BTLOBJ_FLAG_HEAL_PENDING;
}

s32 ResolveAttackHit(BtlObj* hit, s32 index) {
    const BattleAttackDef* attack = &sBattleAttackDefs[index];
    s32 scale = gBtlWork->damageScale;
    BtlObj* target;
    BtlObj* source;

    if (hit->parent != NULL) {
        target = hit->parent;
    } else {
        target = hit;
    }

    target->hitFlags = attack->flags;
    target->hitAttack = index;

    if (attack->flags & ATTACK_FLAG_WARP_AWAY) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_WARP) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        if (attack->flags & ATTACK_FLAG_NO_EXP) target->exp = 0;

        target->flags |= BTLOBJ_FLAG_WARP_PENDING;
        return ATTACK_RESULT_NONE;
    }

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gRikuBtlWork->actor;
    } else if (gBtlWork->flags & BTL_FLAG_HUM_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gBtlWork->actor3;
    } else {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) source = gBtlWork->actor;
        else source = gBtlWork->actor3;
    }

    if (source->btl != NULL) {
        switch (source->btl->hcEffect) {
        case HC_EFFECT_DRAIN:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) != ATTACK_FLAG_KIND_WEAPON) break;

            if (hit->flags & BTLOBJ_FLAG_INVULNERABLE) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) && (hit->flags & BTLOBJ_FLAG_GUARD_PHYSICAL)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) && (hit->flags & BTLOBJ_FLAG_GUARD_NEUTRAL)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_FIRE) && (hit->flags & BTLOBJ_FLAG_IMMUNE_FIRE)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) && (hit->flags & BTLOBJ_FLAG_IMMUNE_BLIZZARD)) break;

            if ((attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) && (hit->flags & BTLOBJ_FLAG_IMMUNE_THUNDER)) break;

            if (hit->badStatus == BAD_STATUS_STOP) break;

            {
                s16 drain = target->hp >> 3;

                if (drain <= 0) drain = 1;
                else if (drain > 20) drain = 20;

                source->hp += drain;
                target->hp -= drain;

                if (target->hp <= 0) target->hp = 1;

                if (source->hp > source->maxHp) source->hp = source->maxHp;

                CreateBtlPopTask(source, BTL_POP_RECOVER);
                target->exp -= target->exp >> 2;
            }

            break;
        case HC_EFFECT_OVERDRIVE:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            }

            break;
        case HC_EFFECT_BERSERK:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON && source->hp < (source->maxHp >> 2)) {
                scale = scale != 0 ? (scale * Q_8_8(2)) >> 8 : Q_8_8(2);
            }

            break;
        case HC_EFFECT_FIRE_BOOST:
            if (attack->flags & ATTACK_FLAG_ELEMENT_FIRE) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            }

            break;
        case HC_EFFECT_BLIZZARD_BOOST:
            if (attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            }

            break;
        case HC_EFFECT_THUNDER_BOOST:
            if (attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            }

            break;
        case HC_EFFECT_MAGIC_BOOST:
            if (attack->flags & ATTACK_FLAG_KIND_MAGIC) {
                scale = scale != 0 ? (scale * Q_8_8(1.3)) >> 8 : Q_8_8(1.3);
            }

            break;
        case HC_EFFECT_SUMMON_BOOST:
            if (attack->flags & ATTACK_FLAG_KIND_SUMMON) {
                scale = scale != 0 ? (scale * Q_8_8(1.3)) >> 8 : Q_8_8(1.3);
            }

            break;
        case HC_EFFECT_BACK_ATTACK:
            if ((attack->flags & (ATTACK_FLAG_KIND_WEAPON | ATTACK_FLAG_IS_SLEIGHT)) == ATTACK_FLAG_KIND_WEAPON) {
                if (source->flags & BTLOBJ_FLAG_FACING_LEFT) {
                    if ((hit->flags & BTLOBJ_FLAG_FACING_LEFT) && hit->x < source->x) {
                        scale = scale != 0 ? (scale * Q_8_8(2)) >> 8 : Q_8_8(2);
                    }
                } else if (!(hit->flags & BTLOBJ_FLAG_FACING_LEFT) && source->x < hit->x) {
                    scale = scale != 0 ? (scale * Q_8_8(2)) >> 8 : Q_8_8(2);
                }
            }

            break;
        }
    }

    if (target->btl != NULL) {
        switch (target->btl->hcEffect) {
        case HC_EFFECT_PROTECT:
            if (attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) {
                CreateBtlPopTask(hit, BTL_POP_GUARD);
                scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
            }

            break;
        case HC_EFFECT_SHELL:
            target->btl->hcEffectCount--;

#ifdef VERSION_EU
            if (attack->flags & ATTACK_FLAG_KIND_MAGIC)
#endif
            {
                scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
            }

            break;
        }
    }

    if (attack->flags & ATTACK_FLAG_ELEMENT_PHYSICAL) {
        if (hit->flags & BTLOBJ_FLAG_GUARD_PHYSICAL) {
            switch ((u32)hit->kind) {
            case ENEMY_BLACK_FUNGUS:
            case ENEMY_DEFENDER:
            case ENEMY_VEXEN:
            case ENEMY_ANSEM:
                m4aSongNumStart(SONG_BTL_GARD);
                break;
            default:
                m4aSongNumStart(SONG_BTL_RB_GARD);
                break;
            }

            hit->invincibleTimer = 30;
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            BgFxStartGuard(gBtlWork->x3, gBtlWork->y3, hit->z - hit->centerHeight * 256);
            return ATTACK_RESULT_BLOCKED;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_PHYSICAL) {
            scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_PHYSICAL) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS | BTLOBJ_FLAG_PLAYER)) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) {
        if (hit->flags & BTLOBJ_FLAG_GUARD_NEUTRAL) {
            switch ((u32)hit->kind) {
            case ENEMY_BLACK_FUNGUS:
            case ENEMY_DEFENDER:
            case ENEMY_VEXEN:
                m4aSongNumStart(SONG_BTL_GARD);
                break;
            default:
                m4aSongNumStart(SONG_BTL_RB_GARD);
                break;
            }

            hit->invincibleTimer = 30;
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            BgFxStartGuard(gBtlWork->x3, gBtlWork->y3, hit->z - hit->centerHeight * 256);
            return ATTACK_RESULT_BLOCKED;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_NEUTRAL) {
            scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_NEUTRAL) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS | BTLOBJ_FLAG_PLAYER)) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_FIRE) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_FIRE) {
            AbsorbAttack(target, source, attack);
            return ATTACK_RESULT_HIT;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_FIRE) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_FIRE) {
            scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_FIRE) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_BLIZZARD) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_BLIZZARD) {
            AbsorbAttack(target, source, attack);
            return ATTACK_RESULT_HIT;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_BLIZZARD) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_BLIZZARD) {
            scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_BLIZZARD) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_ELEMENT_THUNDER) {
        if (hit->flags & BTLOBJ_FLAG_ABSORB_THUNDER) {
            AbsorbAttack(target, source, attack);
            return ATTACK_RESULT_HIT;
        }

        if (hit->flags & BTLOBJ_FLAG_IMMUNE_THUNDER) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        } else if (hit->flags & BTLOBJ_FLAG_RESIST_THUNDER) {
            scale = scale != 0 ? (scale * Q_8_8(0.5)) >> 8 : Q_8_8(0.5);
        } else if (hit->flags & BTLOBJ_FLAG_WEAK_THUNDER) {
            if (target->flags & (BTLOBJ_FLAG_BOSS | BTLOBJ_FLAG_HUM_BOSS)) {
                scale = scale != 0 ? (scale * Q_8_8(1.5)) >> 8 : Q_8_8(1.5);
            } else {
                hit->flags |= BTLOBJ_FLAG_STUN_PENDING;
            }
        }
    } else if (attack->flags & ATTACK_FLAG_INFLICT_STOP) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_STOP) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        hit->flags |= BTLOBJ_FLAG_STOP_PENDING;

        if (scale == 0) hit->damage = ((u32)attack->power * 15) >> 6;
        else hit->damage = (((attack->power * 60) >> 8) * scale) >> 8;

        gBtlWork->pendingHitStop = (u8)attack->hitStop;
        hit->invincibleTimer = 30;
        return ATTACK_RESULT_HIT;
    }

    if (hit->flags & BTLOBJ_FLAG_INVULNERABLE) {
        CreateBtlPopTask(hit, BTL_POP_GUARD);
        hit->invincibleTimer = 30;
        gBtlWork->hitStop = (u8)attack->hitStop;
        return ATTACK_RESULT_HIT;
    }

    if (attack->flags & ATTACK_FLAG_INFLICT_STUN) {
        target->flags |= BTLOBJ_FLAG_STUN_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_TERROR) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_TERROR) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        target->flags |= BTLOBJ_FLAG_TERROR_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_CONFUSE) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_CONFUSE) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        target->flags |= BTLOBJ_FLAG_CONFUSE_PENDING;
    } else if (attack->flags & ATTACK_FLAG_INFLICT_BIND) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_BIND) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        target->flags |= BTLOBJ_FLAG_BIND_PENDING;
    }

    if (attack->flags & ATTACK_FLAG_INFLICT_GRAVITY) {
        if (hit->flags & BTLOBJ_FLAG_IMMUNE_GRAVITY) {
            CreateBtlPopTask(hit, BTL_POP_GUARD);
            hit->invincibleTimer = 30;
            return ATTACK_RESULT_BLOCKED;
        }

        target->flags |= BTLOBJ_FLAG_GRAVITY_PENDING;

        if (attack->flags & ATTACK_FLAG_ELEMENT_NEUTRAL) {
            if (scale == 0) target->damage = (source->attack * attack->power) >> 8;
            else target->damage = (((source->attack * attack->power) >> 8) * scale) >> 8;
        } else {
            if (scale == 0) target->damage = (target->hp * attack->power) >> 8;
            else target->damage = (((target->hp * attack->power) >> 8) * scale) >> 8;

            if (target->flags & BTLOBJ_FLAG_PLAYER) {
                target->damage = (target->damage * 76) >> 8;
            }
        }
    } else {
        if (scale == 0) target->damage = (source->attack * attack->power) >> 8;
        else target->damage = (((source->attack * attack->power) >> 8) * scale) >> 8;

        if (target->damage == 0 && attack->power > 0) target->damage = 1;
    }

    if (target->btl != NULL && target->btl->hcEffect == HC_EFFECT_SECOND_CHANCE) {
        if (target->hp > 1 && target->hp - target->damage <= 0) {
            target->damage = target->hp - 1;
            target->invincibleTimer = 60;
            CreateBtlPopTask(target, BTL_POP_GUARD);
            target->btl->hcEffectCount--;
        }
    }

    target->flags |= BTLOBJ_FLAG_DAMAGE_PENDING;
    gBtlWork->pendingHitStop = (u8)attack->hitStop;
    target->knockbackSpeed = attack->knockbackSpeed;
    target->knockbackLift = attack->knockbackLift;

    if (attack->flags & ATTACK_FLAG_FORWARD_KNOCKBACK) {
        if (source->flags & BTLOBJ_FLAG_FACING_LEFT) target->angle = 192;
        else target->angle = 64;
    } else if (attack->flags & ATTACK_FLAG_RADIAL_KNOCKBACK) {
        target->angle = GetAngle(gBtlWork->x3, gBtlWork->y3, target->x, target->y);
    } else {
        target->angle = GetAngle(source->x, source->y, target->x, target->y);
    }

    return ATTACK_RESULT_HIT;
}

u8 TestAttackBox(s32 x, s32 y, s32 z, s16 halfX, s16 halfY, s16 halfZ) {
    BtlObj* opponent;

    gBtlWork->areaUpdated = TRUE;
    gBtlWork->x3 = x;
    gBtlWork->y3 = y;
    gBtlWork->z3 = z;
    gBtlWork->areaHalfX = halfX;
    gBtlWork->areaHalfY = halfY;
    gBtlWork->areaHalfZ = halfZ;

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
            opponent = gRikuBtlWork->actor;
        } else {
            opponent = gBtlWork->actor;
        }

        if (CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
            return TRUE;
        }
    } else if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
        opponent = ListPoolFirst(&gBtlWork->pool);

        while (opponent != NULL) {
            if (CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
                return TRUE;
            }

            opponent = ListPoolNext(&opponent->node);
        }

        return FALSE;
    } else {
        opponent = gBtlWork->actor;

        if (CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
            return TRUE;
        }
    }

    return FALSE;
}

s32 ApplyAttackToBtlObj(s32 attack, BtlObj* obj) {
    return ResolveAttackHit(obj, attack);
}

s32 ApplyAttackBox(s32 attack, s32 x, s32 y, s32 z, s16 halfX, s16 halfY, s16 halfZ) {
    const BattleAttackDef* def;
    BtlObj* opponent;
    s32 sumX;
    s32 sumY;
    s32 sumZ;
    s16 hitCount;
    s32 blocked;
    s32 n;
    s32 result;
    s32 enemyResult;

    def = &sBattleAttackDefs[attack];
    hitCount = 0;
    blocked = FALSE;
    gBtlWork->areaUpdated = TRUE;
    gBtlWork->x3 = x;
    gBtlWork->y3 = y;
    gBtlWork->z3 = z;
    gBtlWork->areaHalfX = halfX;
    gBtlWork->areaHalfY = halfY;
    gBtlWork->areaHalfZ = halfZ;

    if (gBtlWork->flags & BTL_FLAG_VS_BATTLE) {
        if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
            opponent = gRikuBtlWork->actor;
        } else {
            opponent = gBtlWork->actor;
        }

        if (CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
            result = ResolveAttackHit(opponent, attack);

            if (result == ATTACK_RESULT_HIT) {
                if (def->hitEffect != NULL) {
                    def->hitEffect(opponent->x, opponent->y, opponent->z);
                }
            }

            return result;
        }
    } else if (gBtlWork->flags & BTL_FLAG_PLAYER_CARD_ACTION) {
        opponent = ListPoolFirst(&gBtlWork->pool);
        sumZ = 0;
        sumY = 0;
        sumX = 0;

        while (opponent != NULL) {
            if (!CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
                opponent = ListPoolNext(&opponent->node);
                continue;
            }

            enemyResult = ResolveAttackHit(opponent, attack);

            if (enemyResult == ATTACK_RESULT_HIT) {
                sumX += opponent->x;
                sumY += opponent->y;
                sumZ += opponent->z;
                hitCount++;

                if (def->flags & ATTACK_FLAG_SINGLE_TARGET) {
                    break;
                }
            } else if (enemyResult == ATTACK_RESULT_BLOCKED) {
                blocked = TRUE;
            }

            opponent = ListPoolNext(&opponent->node);
        }

        if (blocked) {
            return ATTACK_RESULT_BLOCKED;
        }

        n = hitCount;

        if (n > 0) {
            if (def->hitEffect != NULL) {
                sumX /= n;
                sumY /= n;
                sumZ /= n;
                def->hitEffect(sumX, sumY, sumZ);
            }

            return ATTACK_RESULT_HIT;
        }
    } else {
        opponent = gBtlWork->actor;

        if (CanAttackBoxHitBtlObj(opponent, x, y, z, halfX, halfY, halfZ)) {
            result = ResolveAttackHit(opponent, attack);

            if (result == ATTACK_RESULT_HIT) {
                if (def->hitEffect != NULL) {
                    def->hitEffect(opponent->x, opponent->y, opponent->z);
                }
            }

            return result;
        }
    }

    return ATTACK_RESULT_NONE;
}

s32 ApplyAttackAt(s32 attack, s32 x, s32 y, s32 z) {
    return ApplyAttackBox(attack, x, y, z, 16, 16, 16);
}

s32 ApplyAttackInFront(BtlObj* obj, s16 distance, s32 attack) {
    if (obj->flags & BTLOBJ_FLAG_FACING_LEFT) {
        return ApplyAttackAt(obj->x - (distance << 8), obj->y, obj->z - (obj->height >> 1), attack);
    } else {
        return ApplyAttackAt(obj->x + (distance << 8), obj->y, obj->z - (obj->height >> 1), attack);
    }
}

void FldObjRegister(FldObj* obj) {
    ListNodeInit(&obj->node, &gFieldState->actor.pool, obj);
    ListPoolAppend(&obj->node, &gFieldState->actor.pool);
}

void FldObjUnregister(FldObj* obj) {
    ListPoolRemove(&obj->node, &gFieldState->actor.pool);
}

void func_08012214() {
}

void* ColliderGetPool(u32 type) {
    switch (type) {
    case COLLIDER_TYPE_PLAYER:
    case COLLIDER_TYPE_OPPONENT:
    case COLLIDER_TYPE_NPC:
    case COLLIDER_TYPE_POOH:
        return &sColliderPoolPlayer;
    case COLLIDER_TYPE_ENEMY:
        return &sColliderPoolEnemy;
    case COLLIDER_TYPE_PICKUP:
    case COLLIDER_TYPE_PLATFORM:
    case COLLIDER_TYPE_BOSS:
    case COLLIDER_TYPE_POOH_OBJECT:
    case COLLIDER_TYPE_ENEMY_NO_ENEMY_COLLISION:
    case COLLIDER_TYPE_SLIPPERY:
        return &sColliderPoolPlayerOnly;
    }

    return &sColliderPoolObstacle;
}

void ColliderPoolsInit() {
    ListPoolInit(&sColliderPoolPlayer);
    ListPoolInit(&sColliderPoolEnemy);
    ListPoolInit(&sColliderPoolPlayerOnly);
    ListPoolInit(&sColliderPoolObstacle);
}

void ColliderInit(Collider* collider, u32 type, u16 radius, u16 height) {
    void* pool;
    collider->otherType = COLLIDER_TYPE_NONE;
    collider->colliding = FALSE;
    collider->standFlags = 0;
    collider->flags = 0;
    collider->radius = radius << 8;
    collider->height = height << 8;
    collider->type = type;
    collider->self = collider;
    collider->touchedTypes = 0;
    pool = ColliderGetPool(type);

    switch (type) {
    case COLLIDER_TYPE_SOLID:
    case COLLIDER_TYPE_PLATFORM:
        collider->flags |= COLLIDER_FLAG_IS_PLATFORM;
        break;
    }

    ListNodeInit(&collider->node, pool, collider);
    ListPoolAppend(&collider->node, pool);
}

void ColliderUnregister(Collider* collider) {
    Collider* self = collider->self;

    if (self == collider) {
        ListPoolRemove(&self->node, ColliderGetPool(self->type));
    }
}

void ColliderSetPosition(Collider* collider, s32 x, s32 y, s32 z) {
    collider->x = x;
    collider->y = y * 2;
    collider->z = z;
}

void ColliderClearPoolContacts(ListPool* pool) {
    Collider* collider = ListPoolFirst(pool);

    while (collider != NULL) {
        collider->colliding = FALSE;
        collider->touchedTypes = 0;
        collider->standFlags = 0;
        collider = ListPoolNext(&collider->node);
    }
}

void ColliderCheckPoolPairs(ListPool* poolA, ListPool* poolB) {
    Collider* colliderA;
    Collider* colliderB;
    s32 radiusSum;
    s32 dx;
    s32 dy;
    s32 penetration;
    s32 dz;
    s32 pushX;
    u8 angle;

    colliderA = ListPoolFirst(poolA);

    while (colliderA != NULL) {
        colliderB = ListPoolLast(poolB);

        while (colliderB != NULL && colliderA != colliderB) {
            radiusSum = colliderA->radius + colliderB->radius;
            dx = colliderA->x - colliderB->x;

            if (dx < 0) {
                dx = colliderB->x - colliderA->x;
            }

            dy = colliderA->y - colliderB->y;

            if (dy < 0) {
                dy = colliderB->y - colliderA->y;
            }

            if (dx < radiusSum && dy < radiusSum) {
                penetration = radiusSum - Sqrt8(((dx * dx) >> 8) + ((dy * dy) >> 8));

                if (penetration > 0) {
                    dz = colliderA->z - colliderB->z;

                    if (dz < colliderA->height && -dz < colliderB->height) {
                        colliderB->colliding = TRUE;
                        colliderA->colliding = TRUE;
                        colliderA->otherType = colliderB->type;
                        colliderB->otherType = colliderA->type;
                        colliderA->touchedTypes |= 1 << colliderB->type;
                        colliderB->touchedTypes |= 1 << colliderA->type;
                        angle = GetAngle(colliderA->x, colliderA->y, colliderB->x, colliderB->y);
                        pushX = (penetration * gSineTable[angle]) >> 8;
                        colliderA->pushX = -pushX;
                        colliderA->pushY = -((penetration * -gSineTable[angle + 64]) >> 8);
                        colliderA->other = colliderB;
                        colliderB->pushX = pushX;
                        colliderB->pushY = -colliderA->pushY;
                        colliderB->other = colliderA;

                        if (colliderB->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            colliderA->platformZ = colliderB->z - colliderB->height;
                            colliderA->penetration = penetration;
                            colliderA->platformY = colliderB->y >> 1;
                            colliderA->platformX = colliderB->x;
                        }

                        if (colliderA->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            colliderB->platformZ = colliderA->z - colliderA->height;
                            colliderB->penetration = penetration;
                            colliderB->platformY = colliderA->y >> 1;
                            colliderB->platformX = colliderA->x;
                        }
                    } else {
                        if (colliderB->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            if (colliderB->z - colliderB->height >= colliderA->z) {
                                colliderA->standFlags |= COLLIDER_STAND_OVER_PLATFORM;

                                if (colliderB->z - colliderB->height == colliderA->z) {
                                    colliderB->standFlags |= COLLIDER_STAND_STOOD_ON;
                                    colliderA->touchedTypes |= 1 << colliderB->type;
                                    colliderB->touchedTypes |= 1 << colliderA->type;
                                }

                                colliderA->platformZ = colliderB->z - colliderB->height;
                                colliderA->penetration = penetration;
                                colliderA->platformY = colliderB->y >> 1;
                                colliderA->platformX = colliderB->x;
                                colliderA->other = colliderB;
                                colliderA->otherType = colliderB->type;
                                colliderB->otherType = colliderA->type;
                            }
                        }

                        if (colliderA->flags & COLLIDER_FLAG_IS_PLATFORM) {
                            if (colliderA->z - colliderA->height >= colliderB->z) {
                                colliderB->standFlags |= COLLIDER_STAND_OVER_PLATFORM;

                                if (colliderA->z - colliderA->height == colliderB->z) {
                                    colliderA->standFlags |= COLLIDER_STAND_STOOD_ON;
                                    colliderA->touchedTypes |= 1 << colliderB->type;
                                    colliderB->touchedTypes |= 1 << colliderA->type;
                                }

                                colliderB->platformZ = colliderA->z - colliderA->height;
                                colliderB->penetration = penetration;
                                colliderB->platformY = colliderA->y >> 1;
                                colliderB->platformX = colliderA->x;
                                colliderB->other = colliderA;
                                colliderA->otherType = colliderB->type;
                                colliderB->otherType = colliderA->type;
                            }
                        }
                    }
                }
            }

            colliderB = ListPoolPrev(&colliderB->node);
        }

        colliderA = ListPoolNext(&colliderA->node);
    }
}

void ColliderUpdateAll() {
    ColliderClearPoolContacts(&sColliderPoolPlayer);
    ColliderClearPoolContacts(&sColliderPoolEnemy);
    ColliderClearPoolContacts(&sColliderPoolPlayerOnly);
    ColliderClearPoolContacts(&sColliderPoolObstacle);
    ColliderCheckPoolPairs(&sColliderPoolPlayer, &sColliderPoolPlayer);
    ColliderCheckPoolPairs(&sColliderPoolEnemy, &sColliderPoolPlayer);
    ColliderCheckPoolPairs(&sColliderPoolPlayerOnly, &sColliderPoolPlayer);
    ColliderCheckPoolPairs(&sColliderPoolEnemy, &sColliderPoolEnemy);
    ColliderCheckPoolPairs(&sColliderPoolObstacle, &sColliderPoolPlayer);
    ColliderCheckPoolPairs(&sColliderPoolObstacle, &sColliderPoolEnemy);
}

void ColliderSetDisabled(Collider* collider, u8 on) {
    if (on) {
        collider->node.flags |= LIST_NODE_FLAG_SKIP;
        collider->colliding = FALSE;
        collider->standFlags = 0;
    } else {
        collider->node.flags &= ~LIST_NODE_FLAG_SKIP;
    }
}

u8 ColliderIsColliding(Collider* collider) {
    return collider->colliding;
}

void ColliderSetRadius(Collider* collider, u16 radius) {
    collider->radius = radius << 8;
}

void ColliderSetHeight(Collider* collider, u16 height) {
    collider->height = height << 8;
}

u8 ColliderIsTouchingType(Collider* collider, s32 bit) {
    if (collider->touchedTypes & (1 << bit)) {
        return TRUE;
    }

    return FALSE;
}
