#ifndef GUARD_MAP_TASKS_H
#define GUARD_MAP_TASKS_H

#include "map.h"
#include "fld_types.h"
#include "map_types.h"
#include "types.h"

s32 MapEnm00CheckOffscreen(MapEnmWork* p);
void MapEnm00Move(MapEnmWork* p, s32 b, s32 c);
void MapEnm00CheckBlocked(MapEnmWork* p, s32 b, s32 c);
s32 MapEnm00SpotPlayer(MapEnmWork* p);
void MapEnm00Appear(MapEnmWork* p);
void MapEnm00Idle(MapEnmWork* p);
void MapEnm00Wander(MapEnmWork* p);
void MapEnm00Chase(MapEnmWork* p);
void MapEnm00Pursue(MapEnmWork* p);
void MapEnm00Vanish(MapEnmWork* p);
void MapEnm00Hit(MapEnmWork* p);
void MapEnm00Stand(MapEnmWork* p);
void Task_MapEnm00_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm00_1(MapEnmWork* p);
void Task_MapEnm00_2(MapEnmWork* p);
void Task_MapEnm00_3(MapEnmWork* p);
void MapEnm01CheckOffscreen(MapEnm01Work* p);
void MapEnm01UpdateHover(MapEnmWork* p, u8 a);
void MapEnm01PickTarget(MapEnmWork* p, u8 a);
void MapEnm01Idle(MapEnmWork* p);
void MapEnm01Fly(MapEnmWork* p);
void MapEnm01Hit(MapEnmWork* p);
void MapEnm01Stand(MapEnmWork* p);
void Task_MapEnm01_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm01_1(MapEnmWork* p);
void Task_MapEnm01_2(MapEnmWork* p);
void Task_MapEnm01_3(MapEnmWork* p);
void MapEnm02Idle(MapEnmWork* p);
void Task_MapEnm02_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm02_1(MapEnmWork* p);
void Task_MapEnm02_2(MapEnmWork* p);
void Task_MapEnm02_3(MapEnmWork* p);
void MapEnm03UpdateHover(MapEnmWork* p, u8 a);
s32 MapEnm03MoveToTarget(MapEnmWork* p);
s32 MapEnm03IsPlayerNearHome(MapEnm03Work* p, s32 lim);
void MapEnm03Guard(MapEnmWork* w);
void MapEnm03Charge(MapEnmWork* w);
void MapEnm03Return(MapEnmWork* w);
void Task_MapEnm03_0(MapEnmWork* w, MapEnmArgs* arg);
s32 Task_MapEnm03_1(MapEnmWork* p);
void Task_MapEnm03_2(MapEnmWork* p);
void Task_MapEnm03_3(MapEnmWork* p);
void MapEnm04CheckOffscreen(MapEnm01Work* p);
void MapEnm04UpdateHover(MapEnmWork* p, u8 a);
void MapEnm04PickTarget(MapEnmWork* p, u8 flag);
void MapEnm04Idle(MapEnmWork* p);
void MapEnm04Fly(MapEnmWork* p);
void MapEnm04Hit(MapEnmWork* p);
void MapEnm04Stand(MapEnmWork* p);
void Task_MapEnm04_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm04_1(MapEnmWork* p);
void Task_MapEnm04_2(MapEnmWork* p);
void Task_MapEnm04_3(MapEnmWork* p);
void MapEnm05Appear(MapEnmWork* p);
void MapEnm05Idle(MapEnmWork* p);
void MapEnm05Vanish(MapEnmWork* p);
void MapEnm05Hit(MapEnmWork* p);
void Task_MapEnm05_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm05_1(MapEnmWork* p);
void Task_MapEnm05_2(MapEnmWork* p);
void Task_MapEnm05_3(MapEnmWork* p);
void MapEnm06Appear(MapEnmWork* p);
void MapEnm06Idle(MapEnmWork* p);
void MapEnm06Vanish(MapEnmWork* p);
void MapEnm06Hit(MapEnmWork* p);
void Task_MapEnm06_0(MapEnmWork* p, MapEnmArgs* q);
s32 Task_MapEnm06_1(MapEnmWork* p);
void Task_MapEnm06_2(MapEnmWork* p);
void Task_MapEnm06_3(MapEnmWork* p);
s32 GetMapRoomDebugCode(MapFloorRoom* p);
void MapDbgWaitInput(MapDbgWork* w);
void MapDbgEditSeed(MapDbgWork* w);
void MapDbgEditWorld(MapDbgWork* w);
void Task_MapDbg_0(MapDbgWork* w, u8* p);
s32 Task_MapDbg_1(MapDbgWork* w);
void Task_MapDbg_2(MapDbgWork* w);
void Task_MapDbg_3(MapDbgWork* w);
void MapGmkJumpWaitStep(MapGmkJumpWork* w);
void MapGmkJumpWaitJump(MapGmkJumpWork* w);
void MapGmkJumpLaunch(MapGmkJumpWork* w);
void Task_MapGmk_Jump_0(MapGmkJumpWork* w, MapPlatform* arg);
s32 Task_MapGmk_Jump_1(MapGmkJumpWork* w);
void Task_MapGmk_Jump_2(MapGmkJumpWork* w);
void Task_MapGmk_Jump_3(MapGmkJumpWork* w);
u8 MapGmkEnmRise(MapGmkEnmWork* w);
void Task_MapGmk_Enm_0(MapGmkEnmWork* w, FldPos* arg);
u8 Task_MapGmk_Enm_1(MapGmkEnmWork* w);
void Task_MapGmk_Enm_2(MapGmkEnmWork* w);
void Task_MapGmk_Enm_3(MapGmkEnmWork* w);
void Task_MapGmk_Dmy_0(MapGmkDmyWork* w);
s32 Task_MapGmk_Dmy_1();
void Task_MapGmk_Dmy_2(MapGmkDmyWork* w);
void Task_MapGmk_Dmy_3(MapGmkDmyWork* w);
u8 MapGmkTutorialWaitHit(MapGmkTutorialWork* w);
u8 MapGmkTutorialWaitCard(MapGmkTutorialWork* w);
u8 MapGmkTutorialWaitOpen(MapGmkTutorialWork* w);
u8 MapGmkTutorialIdle(MapGmkTutorialWork* w);
void Task_MapGmk_Tutorial_0(MapGmkTutorialWork* w);
s32 Task_MapGmk_Tutorial_1(MapGmkTutorialWork* w);
void Task_MapGmk_Tutorial_2(MapGmkTutorialWork* w);
void Task_MapGmk_Tutorial_3(MapGmkTutorialWork* w);
u8 MapGmkSpiderStartBattle(MapGmkSpiderWork* w);
void Task_MapGmk_Spider_0(MapGmkSpiderWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_Spider_1(MapGmkSpiderWork* w);
void Task_MapGmk_Spider_2(MapGmkSpiderWork* w);
void Task_MapGmk_Spider_3(MapGmkSpiderWork* w);
u8 MapGmkGp00WaitHit(MapGmkGpWork* w);
u8 MapGmkGp00HitDelay(MapGmkGpWork* w);
void Task_MapGmk_GP00_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP00_1(MapGmkGpWork* w);
void Task_MapGmk_GP00_2(MapGmkGpWork* w);
void Task_MapGmk_GP00_3(MapGmkGpWork* w);
u8 MapGmkGp01WaitHit(MapGmkGp1Work* w);
u8 MapGmkGp01Break(MapGmkGp1Work* w);
void Task_MapGmk_GP01_0(MapGmkGp1Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP01_1(MapGmkGp1Work* w);
void Task_MapGmk_GP01_2(MapGmkGp1Work* w);
void Task_MapGmk_GP01_3(MapGmkGp1Work* w);
u8 MapGmkGp02WaitHit(MapGmkGpWork* w);
u8 MapGmkGp02HitAnim(MapGmkGpWork* w);
void Task_MapGmk_GP02_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP02_1(MapGmkGpWork* w);
void Task_MapGmk_GP02_2(MapGmkGpWork* w);
void Task_MapGmk_GP02_3(MapGmkGpWork* w);
u8 MapGmkGp03WaitHit(MapGmkGpWork* w);
u8 MapGmkGp03HitAnim(MapGmkGpWork* w);
u8 MapGmkGp03EndAnim(MapGmkGpWork* w);
void Task_MapGmk_GP03_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP03_1(MapGmkGpWork* w);
void Task_MapGmk_GP03_2(MapGmkGpWork* w);
void Task_MapGmk_GP03_3(MapGmkGpWork* w);
u8 MapGmkGp04WaitHit(MapGmkGpWork* w);
u8 MapGmkGp04HitDelay(MapGmkGpWork* w);
void Task_MapGmk_GP04_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP04_1(MapGmkGpWork* w);
void Task_MapGmk_GP04_2(MapGmkGpWork* w);
void Task_MapGmk_GP04_3(MapGmkGpWork* w);
u8 MapGmkGp05WaitHit(MapGmkGpWork* w);
u8 MapGmkGp05HitAnim(MapGmkGpWork* w);
void Task_MapGmk_GP05_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP05_1(MapGmkGpWork* w);
void Task_MapGmk_GP05_2(MapGmkGpWork* w);
void Task_MapGmk_GP05_3(MapGmkGpWork* w);
u8 MapGmkGp06WaitHit(MapGmkGpWork* w);
u8 MapGmkGp06HitDelay(MapGmkGpWork* w);
void Task_MapGmk_GP06_0(MapGmkGpWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP06_1(MapGmkGpWork* w);
void Task_MapGmk_GP06_2(MapGmkGpWork* w);
void Task_MapGmk_GP06_3(MapGmkGpWork* w);
s32 MapGmkGp07WaitStep(MapGmkGp07Work* w);
s32 MapGmkGp07WaitStepOff(MapGmkGp07Work* w);
s32 MapGmkGp07EndAnim(MapGmkGp07Work* w);
void Task_MapGmk_GP07_0(MapGmkGp07Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP07_1(MapGmkGp07Work* w);
void Task_MapGmk_GP07_2(MapGmkGp07Work* w);
void Task_MapGmk_GP07_3(MapGmkGp07Work* w);
s32 MapGmkGp08WaitHit(MapGmkGp08Work* w);
s32 MapGmkGp08HitAnim(MapGmkGp08Work* w);
void Task_MapGmk_GP08_0(MapGmkGp08Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP08_1(MapGmkGp08Work* w);
void Task_MapGmk_GP08_2(MapGmkGp08Work* w);
void Task_MapGmk_GP08_3(MapGmkGp08Work* w);
s32 MapGmkGp09WaitStep(MapGmkGp09Work* w);
s32 MapGmkGp09StepAnim(MapGmkGp09Work* w);
s32 MapGmkGp09WaitStepOff(MapGmkGp09Work* w);
void Task_MapGmk_GP09_0(MapGmkGp09Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk_GP09_1(MapGmkGp09Work* w);
void Task_MapGmk_GP09_2(MapGmkGp09Work* w);
void Task_MapGmk_GP09_3(MapGmkGp09Work* w);
void Task_MapGmk00_0(MapGmk00Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk00_1(MapGmk00Work* w);
void Task_MapGmk00_2(MapGmk00Work* w);
void Task_MapGmk00_3(MapGmk00Work* w);
u8 MapGmk01WaitHit(MapGmk01Work* w);
u8 MapGmk01Open(MapGmk01Work* w);
u8 MapGmk01WaitPrize(MapGmk01Work* w);
void Task_MapGmk01_0(MapGmk01Work* w, MapGmkPlacement* arg);
u8 Task_MapGmk01_1(MapGmk01Work* w);
void Task_MapGmk01_2(MapGmk01Work* w);
void Task_MapGmk01_3(MapGmk01Work* w);
void MapGmkBarrelDropPrizes(FldPos* p);
u8 MapGmkBarrelWaitHit(MapGmkBarrelWork* w);
u8 MapGmkBarrelBreak(MapGmkBarrelWork* w);
void Task_MapGmk_Barrel_0(MapGmkBarrelWork* w, MapGmkPlacement* arg);
u8 Task_MapGmk_Barrel_1(MapGmkBarrelWork* w);
void Task_MapGmk_Barrel_2(MapGmkBarrelWork* w);
void Task_MapGmk_Barrel_3(MapGmkBarrelWork* w);
void MapGmk04CheckTalk(MapGmk04Work* w);
void MapGmk04CheckFirstTalk(MapGmk04Work* w);
void MapGmk04WaitMessage(MapGmk04Work* w);
void MapGmk04WaitFirstTalkEnd(MapGmk04Work* w);
void Task_MapGmk04_0(MapGmk04Work* w, MapGmkPlacement* arg);
s32 Task_MapGmk04_1(MapGmk04Work* w);
void Task_MapGmk04_2(MapGmk04Work* w);
void Task_MapGmk04_3(MapGmk04Work* w);
void MapGmk05CheckTalk(MapGmk05Work* w);
void MapGmk05EnterShop(MapGmk05Work* w);
void Task_MapGmk05_0(MapGmk05Work* w, MapGmkPlacement* arg);
s32 Task_MapGmk05_1(MapGmk05Work* w);
void Task_MapGmk05_2(MapGmk05Work* w);
void Task_MapGmk05_3(MapGmk05Work* w);
void MapGmk06CheckTalk(MapGmk06Work* w);
void MapGmk06EnterWorldWarp(MapGmk06Work* w);
void MapGmk06WaitMessage(MapGmk06Work* w);
void Task_MapGmk06_0(MapGmk06Work* w, MapGmkPlacement* arg);
s32 Task_MapGmk06_1(MapGmk06Work* w);
void Task_MapGmk06_2(MapGmk06Work* w);
void Task_MapGmk06_3(MapGmk06Work* w);
void MapPrizeBounce(MapPrizeWork* w);
void MapPrizeCollect(MapPrizeWork* w);
void Task_MapPrize_0(MapPrizeWork* w, MapPrizeArgs* arg);
s32 Task_MapPrize_1(MapPrizeWork* w);
void Task_MapPrize_2(MapPrizeWork* w);
void Task_MapPrize_3(MapPrizeWork* w);
void MapPrzCardUpdateScale(MapPrzCardWork* work);
void MapPrzCardAimAtCenter(MapPrzCardWork* w);
void MapPrzCardBounce(MapPrzCardWork* w);
void MapPrzCardFlyToCenter(MapPrzCardWork* w);
void MapPrzCardShowName(MapPrzCardWork* w);
void MapPrzCardShrink(MapPrzCardWork* w);
void Task_MapPrzCard_0(MapPrzCardWork* w, MapPrizeArgs* p);
s32 Task_MapPrzCard_1(MapPrzCardWork* w);
void Task_MapPrzCard_2(MapPrzCardWork* w);
void Task_MapPrzCard_3(MapPrzCardWork* w);
void MapPrzStockShowMessage(MapPrzStockWork* w);
void MapPrzStockWaitMessage(MapPrzStockWork* w);
void Task_MapPrzStock_0(MapPrzStockWork* w, u16* a);
s32 Task_MapPrzStock_1(MapPrzStockWork* w);
void Task_MapPrzStock_2(MapPrzStockWork* w);
void Task_MapPrzStock_3(MapPrzStockWork* w);
void MapMsgInit(MapMsgWork* w, void* text);
s32 Task_MapMsg_1(MapMsgWork* w);
void MapMsgDraw(MapMsgWork* w);
void MapMsgDestroy(MapMsgWork* w);
s32 Task_MapMsg2_1(MapMsgWork* w);
void Task_MapSpark_0(MapSparkWork* w, FldObj* obj);
s32 Task_MapSpark_1(MapSparkWork* w);
void Task_MapSpark_2(MapSparkWork* w);
void Task_MapSpark_3(MapSparkWork* w);
void Task_MapTalk_0(MapTalkWork* w, FldObj* obj);
s32 Task_MapTalk_1(MapTalkWork* w);
void Task_MapTalk_2(MapTalkWork* w);
void Task_MapTalk_3(MapTalkWork* w);
void MapDonaldCheckTalk(MapDonaldWork* w);
void MapDonaldWaitMessage(MapDonaldWork* w);
void Task_MapDonald_0(MapDonaldWork* w);
s32 Task_MapDonald_1(MapDonaldWork* w);
void Task_MapDonald_2(MapDonaldWork* w);
void Task_MapDonald_3(MapDonaldWork* w);
void MapGoofyCheckTalk(MapGoofyWork* w);
void MapGoofyWaitMessage(MapGoofyWork* w);
void Task_MapGoofy_0(MapGoofyWork* w);
s32 Task_MapGoofy_1(MapGoofyWork* w);
void Task_MapGoofy_2(MapGoofyWork* w);
void Task_MapGoofy_3(MapGoofyWork* w);
void MapNamineCheckTalk(MapNamineWork* w);
void MapNamineWaitMessage(MapNamineWork* w);
void Task_MapNamine_0(MapNamineWork* w);
s32 Task_MapNamine_1(MapNamineWork* w);
void Task_MapNamine_2(MapNamineWork* w);
void Task_MapNamine_3(MapNamineWork* w);
void MapNiserikuCheckTalk(MapNiserikuWork* w);
void MapNiserikuWaitMessage(MapNiserikuWork* w);
void MapNiserikuWaitApproach(MapNiserikuWork* w);
void MapNiserikuStartEvent(MapNiserikuWork* w);
void Task_MapNiseriku_0(MapNiserikuWork* w);
s32 Task_MapNiseriku_1(MapNiserikuWork* w);
void Task_MapNiseriku_2(MapNiserikuWork* w);
void Task_MapNiseriku_3(MapNiserikuWork* w);
void MapMickeyCheckTalk(MapMickeyWork* w);
void MapMickeyWaitMessage(MapMickeyWork* w);
void Task_MapMickey_0(MapMickeyWork* w);
s32 Task_MapMickey_1(MapMickeyWork* w);
void Task_MapMickey_2(MapMickeyWork* w);
void Task_MapMickey_3(MapMickeyWork* w);
void MapTutorialStartBattle();
void MapTutorialWaitStart(MapTutorialWork* w);
void MapTutorialDropBarrel(MapTutorialWork* w);
void MapTutorialBarrelFall(MapTutorialWork* w);
void MapTutorialWaitBarrelHit(MapTutorialWork* w);
void MapTutorialBarrelBreak(MapTutorialWork* w);
void MapTutorialWaitPrizeCard(MapTutorialWork* w);
void MapTutorialSpawnEnemy(MapTutorialWork* w);
void MapTutorialEnemyAppear(MapTutorialWork* w);
void MapTutorialWaitEnemyMessage(MapTutorialWork* w);
void MapTutorialEnemyUpdate(MapTutorialWork* w);
void MapTutorialEnemyHit(MapTutorialWork* w);
void Task_MapTutorial_0(MapTutorialWork* w);
s32 Task_MapTutorial_1(MapTutorialWork* w);
void Task_MapTutorial_2(MapTutorialWork* w);
void Task_MapTutorial_3(MapTutorialWork* w);
s32 IsPlayerWithin(FldPos* p, s32 lim);
void func_080F74E8(MapStairWork* w);
void func_080F753C(MapStairWork* w);
void MapStairWaitApproach(MapStairWork* w);
void MapStairWaitMessage(MapStairWork* w);
void Task_MapStair_0(MapStairWork* w, FldObj* arg);
s32 Task_MapStair_1(MapStairWork* w);
void Task_MapStair_2(MapStairWork* w);
void Task_MapStair_3(MapStairWork* w);
void Task_MapFaint_0(MapFaintWork* w, FldObj* obj);
s32 Task_MapFaint_1(MapFaintWork* w);
void Task_MapFaint_2(MapFaintWork* w);
void Task_MapFaint_3(MapFaintWork* w);
void Task_MapDmg_0(MapDmgWork* w);
s32 Task_MapDmg_1(MapDmgWork* w);
void Task_MapDmg_2(MapDmgWork* w);
void Task_MapDmg_3(MapDmgWork* w);
void* GetFloorName();
void Task_MapFloor_0(MapFloorWork* w);
s32 Task_MapFloor_1(MapFloorWork* w);
void Task_MapFloor_2(MapFloorWork* w);
void Task_MapFloor_3(MapFloorWork* w);

#endif
