#ifndef GUARD_MAP_TASKS_H
#define GUARD_MAP_TASKS_H

#include "map.h"
#include "fld_types.h"
#include "map_types.h"
#include "types.h"

s32 MapEnm00CheckOffscreen(MapEnmWork* work);
void MapEnm00Move(MapEnmWork* work, s32 accel, s32 maxSpeed);
void MapEnm00CheckBlocked(MapEnmWork* work, s32 x, s32 y);
s32 MapEnm00SpotPlayer(MapEnmWork* work);
void MapEnm00Appear(MapEnmWork* work);
void MapEnm00Idle(MapEnmWork* work);
void MapEnm00Wander(MapEnmWork* work);
void MapEnm00Chase(MapEnmWork* work);
void MapEnm00Pursue(MapEnmWork* work);
void MapEnm00Vanish(MapEnmWork* work);
void MapEnm00Hit(MapEnmWork* work);
void MapEnm00Stand(MapEnmWork* work);
void Task_MapEnm00_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm00_1(MapEnmWork* work);
void Task_MapEnm00_2(MapEnmWork* work);
void Task_MapEnm00_3(MapEnmWork* work);
void MapEnm01CheckOffscreen(MapEnm01Work* work);
void MapEnm01UpdateHover(MapEnmWork* work, u8 moving);
void MapEnm01PickTarget(MapEnmWork* work, u8 atPlayer);
void MapEnm01Idle(MapEnmWork* work);
void MapEnm01Fly(MapEnmWork* work);
void MapEnm01Hit(MapEnmWork* work);
void MapEnm01Stand(MapEnmWork* work);
void Task_MapEnm01_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm01_1(MapEnmWork* work);
void Task_MapEnm01_2(MapEnmWork* work);
void Task_MapEnm01_3(MapEnmWork* work);
void MapEnm02Idle(MapEnmWork* work);
void Task_MapEnm02_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm02_1(MapEnmWork* work);
void Task_MapEnm02_2(MapEnmWork* work);
void Task_MapEnm02_3(MapEnmWork* work);
void MapEnm03UpdateHover(MapEnmWork* work, u8 moving);
s32 MapEnm03MoveToTarget(MapEnmWork* work);
s32 MapEnm03IsPlayerNearHome(MapEnm03Work* work, s32 lim);
void MapEnm03Guard(MapEnmWork* work);
void MapEnm03Charge(MapEnmWork* work);
void MapEnm03Return(MapEnmWork* work);
void Task_MapEnm03_0(MapEnmWork* work, MapEnmArgs* arg);
s32 Task_MapEnm03_1(MapEnmWork* work);
void Task_MapEnm03_2(MapEnmWork* work);
void Task_MapEnm03_3(MapEnmWork* work);
void MapEnm04CheckOffscreen(MapEnm01Work* work);
void MapEnm04UpdateHover(MapEnmWork* work, u8 moving);
void MapEnm04PickTarget(MapEnmWork* work, u8 flag);
void MapEnm04Idle(MapEnmWork* work);
void MapEnm04Fly(MapEnmWork* work);
void MapEnm04Hit(MapEnmWork* work);
void MapEnm04Stand(MapEnmWork* work);
void Task_MapEnm04_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm04_1(MapEnmWork* work);
void Task_MapEnm04_2(MapEnmWork* work);
void Task_MapEnm04_3(MapEnmWork* work);
void MapEnm05Appear(MapEnmWork* work);
void MapEnm05Idle(MapEnmWork* work);
void MapEnm05Vanish(MapEnmWork* work);
void MapEnm05Hit(MapEnmWork* work);
void Task_MapEnm05_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm05_1(MapEnmWork* work);
void Task_MapEnm05_2(MapEnmWork* work);
void Task_MapEnm05_3(MapEnmWork* work);
void MapEnm06Appear(MapEnmWork* work);
void MapEnm06Idle(MapEnmWork* work);
void MapEnm06Vanish(MapEnmWork* work);
void MapEnm06Hit(MapEnmWork* work);
void Task_MapEnm06_0(MapEnmWork* work, MapEnmArgs* q);
s32 Task_MapEnm06_1(MapEnmWork* work);
void Task_MapEnm06_2(MapEnmWork* work);
void Task_MapEnm06_3(MapEnmWork* work);
s32 GetMapRoomDebugCode(MapFloorRoom* floorRoom);
void MapDbgWaitInput(MapDbgWork* work);
void MapDbgEditSeed(MapDbgWork* work);
void MapDbgEditWorld(MapDbgWork* work);
void Task_MapDbg_0(MapDbgWork* work, u8* editing);
s32 Task_MapDbg_1(MapDbgWork* work);
void Task_MapDbg_2(MapDbgWork* work);
void Task_MapDbg_3(MapDbgWork* work);
void MapGmkJumpWaitStep(MapGmkJumpWork* work);
void MapGmkJumpWaitJump(MapGmkJumpWork* work);
void MapGmkJumpLaunch(MapGmkJumpWork* work);
void Task_MapGmk_Jump_0(MapGmkJumpWork* work, MapPlatform* arg);
s32 Task_MapGmk_Jump_1(MapGmkJumpWork* work);
void Task_MapGmk_Jump_2(MapGmkJumpWork* work);
void Task_MapGmk_Jump_3(MapGmkJumpWork* work);
u8 MapGmkEnmRise(MapGmkEnmWork* work);
void Task_MapGmk_Enm_0(MapGmkEnmWork* work, FldPos* arg);
u8 Task_MapGmk_Enm_1(MapGmkEnmWork* work);
void Task_MapGmk_Enm_2(MapGmkEnmWork* work);
void Task_MapGmk_Enm_3(MapGmkEnmWork* work);
void Task_MapGmk_Dmy_0(MapGmkDmyWork* work);
s32 Task_MapGmk_Dmy_1();
void Task_MapGmk_Dmy_2(MapGmkDmyWork* work);
void Task_MapGmk_Dmy_3(MapGmkDmyWork* work);
u8 MapGmkTutorialWaitHit(MapGmkTutorialWork* work);
u8 MapGmkTutorialWaitCard(MapGmkTutorialWork* work);
u8 MapGmkTutorialWaitOpen(MapGmkTutorialWork* work);
u8 MapGmkTutorialIdle(MapGmkTutorialWork* work);
void Task_MapGmk_Tutorial_0(MapGmkTutorialWork* work);
s32 Task_MapGmk_Tutorial_1(MapGmkTutorialWork* work);
void Task_MapGmk_Tutorial_2(MapGmkTutorialWork* work);
void Task_MapGmk_Tutorial_3(MapGmkTutorialWork* work);
u8 MapGmkSpiderStartBattle(MapGmkSpiderWork* work);
void Task_MapGmk_Spider_0(MapGmkSpiderWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_Spider_1(MapGmkSpiderWork* work);
void Task_MapGmk_Spider_2(MapGmkSpiderWork* work);
void Task_MapGmk_Spider_3(MapGmkSpiderWork* work);
u8 MapGmkGp00WaitHit(MapGmkGpWork* work);
u8 MapGmkGp00HitDelay(MapGmkGpWork* work);
void Task_MapGmk_GP00_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP00_1(MapGmkGpWork* work);
void Task_MapGmk_GP00_2(MapGmkGpWork* work);
void Task_MapGmk_GP00_3(MapGmkGpWork* work);
u8 MapGmkGp01WaitHit(MapGmkGp1Work* work);
u8 MapGmkGp01Break(MapGmkGp1Work* work);
void Task_MapGmk_GP01_0(MapGmkGp1Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP01_1(MapGmkGp1Work* work);
void Task_MapGmk_GP01_2(MapGmkGp1Work* work);
void Task_MapGmk_GP01_3(MapGmkGp1Work* work);
u8 MapGmkGp02WaitHit(MapGmkGpWork* work);
u8 MapGmkGp02HitAnim(MapGmkGpWork* work);
void Task_MapGmk_GP02_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP02_1(MapGmkGpWork* work);
void Task_MapGmk_GP02_2(MapGmkGpWork* work);
void Task_MapGmk_GP02_3(MapGmkGpWork* work);
u8 MapGmkGp03WaitHit(MapGmkGpWork* work);
u8 MapGmkGp03HitAnim(MapGmkGpWork* work);
u8 MapGmkGp03EndAnim(MapGmkGpWork* work);
void Task_MapGmk_GP03_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP03_1(MapGmkGpWork* work);
void Task_MapGmk_GP03_2(MapGmkGpWork* work);
void Task_MapGmk_GP03_3(MapGmkGpWork* work);
u8 MapGmkGp04WaitHit(MapGmkGpWork* work);
u8 MapGmkGp04HitDelay(MapGmkGpWork* work);
void Task_MapGmk_GP04_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP04_1(MapGmkGpWork* work);
void Task_MapGmk_GP04_2(MapGmkGpWork* work);
void Task_MapGmk_GP04_3(MapGmkGpWork* work);
u8 MapGmkGp05WaitHit(MapGmkGpWork* work);
u8 MapGmkGp05HitAnim(MapGmkGpWork* work);
void Task_MapGmk_GP05_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP05_1(MapGmkGpWork* work);
void Task_MapGmk_GP05_2(MapGmkGpWork* work);
void Task_MapGmk_GP05_3(MapGmkGpWork* work);
u8 MapGmkGp06WaitHit(MapGmkGpWork* work);
u8 MapGmkGp06HitDelay(MapGmkGpWork* work);
void Task_MapGmk_GP06_0(MapGmkGpWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP06_1(MapGmkGpWork* work);
void Task_MapGmk_GP06_2(MapGmkGpWork* work);
void Task_MapGmk_GP06_3(MapGmkGpWork* work);
s32 MapGmkGp07WaitStep(MapGmkGp07Work* work);
s32 MapGmkGp07WaitStepOff(MapGmkGp07Work* work);
s32 MapGmkGp07EndAnim(MapGmkGp07Work* work);
void Task_MapGmk_GP07_0(MapGmkGp07Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP07_1(MapGmkGp07Work* work);
void Task_MapGmk_GP07_2(MapGmkGp07Work* work);
void Task_MapGmk_GP07_3(MapGmkGp07Work* work);
s32 MapGmkGp08WaitHit(MapGmkGp08Work* work);
s32 MapGmkGp08HitAnim(MapGmkGp08Work* work);
void Task_MapGmk_GP08_0(MapGmkGp08Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP08_1(MapGmkGp08Work* work);
void Task_MapGmk_GP08_2(MapGmkGp08Work* work);
void Task_MapGmk_GP08_3(MapGmkGp08Work* work);
s32 MapGmkGp09WaitStep(MapGmkGp09Work* work);
s32 MapGmkGp09StepAnim(MapGmkGp09Work* work);
s32 MapGmkGp09WaitStepOff(MapGmkGp09Work* work);
void Task_MapGmk_GP09_0(MapGmkGp09Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk_GP09_1(MapGmkGp09Work* work);
void Task_MapGmk_GP09_2(MapGmkGp09Work* work);
void Task_MapGmk_GP09_3(MapGmkGp09Work* work);
void Task_MapGmk00_0(MapGmk00Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk00_1(MapGmk00Work* work);
void Task_MapGmk00_2(MapGmk00Work* work);
void Task_MapGmk00_3(MapGmk00Work* work);
u8 MapGmk01WaitHit(MapGmk01Work* work);
u8 MapGmk01Open(MapGmk01Work* work);
u8 MapGmk01WaitPrize(MapGmk01Work* work);
void Task_MapGmk01_0(MapGmk01Work* work, MapGmkPlacement* arg);
u8 Task_MapGmk01_1(MapGmk01Work* work);
void Task_MapGmk01_2(MapGmk01Work* work);
void Task_MapGmk01_3(MapGmk01Work* work);
void MapGmkBarrelDropPrizes(FldPos* pos);
u8 MapGmkBarrelWaitHit(MapGmkBarrelWork* work);
u8 MapGmkBarrelBreak(MapGmkBarrelWork* work);
void Task_MapGmk_Barrel_0(MapGmkBarrelWork* work, MapGmkPlacement* arg);
u8 Task_MapGmk_Barrel_1(MapGmkBarrelWork* work);
void Task_MapGmk_Barrel_2(MapGmkBarrelWork* work);
void Task_MapGmk_Barrel_3(MapGmkBarrelWork* work);
void MapGmk04CheckTalk(MapGmk04Work* work);
void MapGmk04CheckFirstTalk(MapGmk04Work* work);
void MapGmk04WaitMessage(MapGmk04Work* work);
void MapGmk04WaitFirstTalkEnd(MapGmk04Work* work);
void Task_MapGmk04_0(MapGmk04Work* work, MapGmkPlacement* arg);
s32 Task_MapGmk04_1(MapGmk04Work* work);
void Task_MapGmk04_2(MapGmk04Work* work);
void Task_MapGmk04_3(MapGmk04Work* work);
void MapGmk05CheckTalk(MapGmk05Work* work);
void MapGmk05EnterShop(MapGmk05Work* work);
void Task_MapGmk05_0(MapGmk05Work* work, MapGmkPlacement* arg);
s32 Task_MapGmk05_1(MapGmk05Work* work);
void Task_MapGmk05_2(MapGmk05Work* work);
void Task_MapGmk05_3(MapGmk05Work* work);
void MapGmk06CheckTalk(MapGmk06Work* work);
void MapGmk06EnterWorldWarp(MapGmk06Work* work);
void MapGmk06WaitMessage(MapGmk06Work* work);
void Task_MapGmk06_0(MapGmk06Work* work, MapGmkPlacement* arg);
s32 Task_MapGmk06_1(MapGmk06Work* work);
void Task_MapGmk06_2(MapGmk06Work* work);
void Task_MapGmk06_3(MapGmk06Work* work);
void MapPrizeBounce(MapPrizeWork* work);
void MapPrizeCollect(MapPrizeWork* work);
void Task_MapPrize_0(MapPrizeWork* work, MapPrizeArgs* arg);
s32 Task_MapPrize_1(MapPrizeWork* work);
void Task_MapPrize_2(MapPrizeWork* work);
void Task_MapPrize_3(MapPrizeWork* work);
void MapPrzCardUpdateScale(MapPrzCardWork* work);
void MapPrzCardAimAtCenter(MapPrzCardWork* work);
void MapPrzCardBounce(MapPrzCardWork* work);
void MapPrzCardFlyToCenter(MapPrzCardWork* work);
void MapPrzCardShowName(MapPrzCardWork* work);
void MapPrzCardShrink(MapPrzCardWork* work);
void Task_MapPrzCard_0(MapPrzCardWork* work, MapPrizeArgs* arg);
s32 Task_MapPrzCard_1(MapPrzCardWork* work);
void Task_MapPrzCard_2(MapPrzCardWork* work);
void Task_MapPrzCard_3(MapPrzCardWork* work);
void MapPrzStockShowMessage(MapPrzStockWork* work);
void MapPrzStockWaitMessage(MapPrzStockWork* work);
void Task_MapPrzStock_0(MapPrzStockWork* work, u16* stock);
s32 Task_MapPrzStock_1(MapPrzStockWork* work);
void Task_MapPrzStock_2(MapPrzStockWork* work);
void Task_MapPrzStock_3(MapPrzStockWork* work);
void MapMsgInit(MapMsgWork* work, void* text);
s32 Task_MapMsg_1(MapMsgWork* work);
void MapMsgDraw(MapMsgWork* work);
void MapMsgDestroy(MapMsgWork* work);
s32 Task_MapMsg2_1(MapMsgWork* work);
void Task_MapSpark_0(MapSparkWork* work, FldObj* obj);
s32 Task_MapSpark_1(MapSparkWork* work);
void Task_MapSpark_2(MapSparkWork* work);
void Task_MapSpark_3(MapSparkWork* work);
void Task_MapTalk_0(MapTalkWork* work, FldObj* obj);
s32 Task_MapTalk_1(MapTalkWork* work);
void Task_MapTalk_2(MapTalkWork* work);
void Task_MapTalk_3(MapTalkWork* work);
void MapDonaldCheckTalk(MapDonaldWork* work);
void MapDonaldWaitMessage(MapDonaldWork* work);
void Task_MapDonald_0(MapDonaldWork* work);
s32 Task_MapDonald_1(MapDonaldWork* work);
void Task_MapDonald_2(MapDonaldWork* work);
void Task_MapDonald_3(MapDonaldWork* work);
void MapGoofyCheckTalk(MapGoofyWork* work);
void MapGoofyWaitMessage(MapGoofyWork* work);
void Task_MapGoofy_0(MapGoofyWork* work);
s32 Task_MapGoofy_1(MapGoofyWork* work);
void Task_MapGoofy_2(MapGoofyWork* work);
void Task_MapGoofy_3(MapGoofyWork* work);
void MapNamineCheckTalk(MapNamineWork* work);
void MapNamineWaitMessage(MapNamineWork* work);
void Task_MapNamine_0(MapNamineWork* work);
s32 Task_MapNamine_1(MapNamineWork* work);
void Task_MapNamine_2(MapNamineWork* work);
void Task_MapNamine_3(MapNamineWork* work);
void MapNiserikuCheckTalk(MapNiserikuWork* work);
void MapNiserikuWaitMessage(MapNiserikuWork* work);
void MapNiserikuWaitApproach(MapNiserikuWork* work);
void MapNiserikuStartEvent(MapNiserikuWork* work);
void Task_MapNiseriku_0(MapNiserikuWork* work);
s32 Task_MapNiseriku_1(MapNiserikuWork* work);
void Task_MapNiseriku_2(MapNiserikuWork* work);
void Task_MapNiseriku_3(MapNiserikuWork* work);
void MapMickeyCheckTalk(MapMickeyWork* work);
void MapMickeyWaitMessage(MapMickeyWork* work);
void Task_MapMickey_0(MapMickeyWork* work);
s32 Task_MapMickey_1(MapMickeyWork* work);
void Task_MapMickey_2(MapMickeyWork* work);
void Task_MapMickey_3(MapMickeyWork* work);
void MapTutorialStartBattle();
void MapTutorialWaitStart(MapTutorialWork* work);
void MapTutorialDropBarrel(MapTutorialWork* work);
void MapTutorialBarrelFall(MapTutorialWork* work);
void MapTutorialWaitBarrelHit(MapTutorialWork* work);
void MapTutorialBarrelBreak(MapTutorialWork* work);
void MapTutorialWaitPrizeCard(MapTutorialWork* work);
void MapTutorialSpawnEnemy(MapTutorialWork* work);
void MapTutorialEnemyAppear(MapTutorialWork* work);
void MapTutorialWaitEnemyMessage(MapTutorialWork* work);
void MapTutorialEnemyUpdate(MapTutorialWork* work);
void MapTutorialEnemyHit(MapTutorialWork* work);
void Task_MapTutorial_0(MapTutorialWork* work);
s32 Task_MapTutorial_1(MapTutorialWork* work);
void Task_MapTutorial_2(MapTutorialWork* work);
void Task_MapTutorial_3(MapTutorialWork* work);
s32 IsPlayerWithin(FldPos* pos, s32 lim);
void MapStairWaitStepOn(MapStairWork* work);
void MapStairWaitStepOn2(MapStairWork* work);
void MapStairWaitApproach(MapStairWork* work);
void MapStairWaitMessage(MapStairWork* work);
void Task_MapStair_0(MapStairWork* work, FldObj* arg);
s32 Task_MapStair_1(MapStairWork* work);
void Task_MapStair_2(MapStairWork* work);
void Task_MapStair_3(MapStairWork* work);
void Task_MapFaint_0(MapFaintWork* work, FldObj* obj);
s32 Task_MapFaint_1(MapFaintWork* work);
void Task_MapFaint_2(MapFaintWork* work);
void Task_MapFaint_3(MapFaintWork* work);
void Task_MapDmg_0(MapDmgWork* work);
s32 Task_MapDmg_1(MapDmgWork* work);
void Task_MapDmg_2(MapDmgWork* work);
void Task_MapDmg_3(MapDmgWork* work);
const void* GetFloorName();
void Task_MapFloor_0(MapFloorWork* work);
s32 Task_MapFloor_1(MapFloorWork* work);
void Task_MapFloor_2(MapFloorWork* work);
void Task_MapFloor_3(MapFloorWork* work);

#endif
