#ifndef GUARD_MSG_PORTRAIT_DATA_H
#define GUARD_MSG_PORTRAIT_DATA_H

#include "anim.h"
#include "types.h"

enum PortraitId {
    PORTRAIT_SORA,
    PORTRAIT_DONALD,
    PORTRAIT_GOOFY,
    PORTRAIT_ROBED_FIGURE,
    PORTRAIT_QUEEN_OF_HEARTS,
    PORTRAIT_ALICE,
    PORTRAIT_JIMINY_CRICKET,
    PORTRAIT_MOOGLE,
    PORTRAIT_WHITE_RABBIT,
    PORTRAIT_CHESHIRE_CAT,
    PORTRAIT_PINOCCHIO,
    PORTRAIT_JACK,
    PORTRAIT_OOGIE_BOOGIE,
    PORTRAIT_ARIEL,
    PORTRAIT_URSULA,
    PORTRAIT_ALADDIN,
    PORTRAIT_JAFAR,
    PORTRAIT_GEPPETTO,
    PORTRAIT_SALLY,
    PORTRAIT_DR_FINKELSTEIN,
    PORTRAIT_AXEL,
    PORTRAIT_GENIE,
    PORTRAIT_FLOUNDER,
    PORTRAIT_SEBASTIAN,
    PORTRAIT_DONALD_2,
    PORTRAIT_GOOFY_2,
    PORTRAIT_RIKU,
    PORTRAIT_RIKU_REPLICA,
    PORTRAIT_KAIRI,
    PORTRAIT_PETER_PAN,
    PORTRAIT_HOOK,
    PORTRAIT_LEON,
    PORTRAIT_AERITH,
    PORTRAIT_CID,
    PORTRAIT_HADES,
    PORTRAIT_CLOUD,
    PORTRAIT_WINNIE_THE_POOH,
    PORTRAIT_YUFFIE,
    PORTRAIT_VEXEN,
    PORTRAIT_TIDUS,
    PORTRAIT_SELPHIE,
    PORTRAIT_WAKKA,
    PORTRAIT_WENDY,
    PORTRAIT_BEAST,
    PORTRAIT_MALEFICENT,
    PORTRAIT_PHILOCTETES,
    PORTRAIT_HERCULES,
    PORTRAIT_PIGLET,
    PORTRAIT_OWL,
    PORTRAIT_RABBIT,
    PORTRAIT_EEYORE,
    PORTRAIT_ROO,
    PORTRAIT_DIZ,
    PORTRAIT_BELLE,
    PORTRAIT_LARXENE,
    PORTRAIT_ZEXION,
    PORTRAIT_ANSEM,
    PORTRAIT_LEXAEUS,
    PORTRAIT_MARLUXIA,
    PORTRAIT_TIGGER,
    PORTRAIT_NAMINE,
    PORTRAIT_MICKEY,
    PORTRAIT_NONE
};

typedef struct MsgFaceAnim {
    void* tiles;
    void* palette;
    void** gfxTable;
    AnimHeader** anims;
    u8 animCount;
    u8 animFlags;
} MsgFaceAnim;

extern const MsgFaceAnim* gMsgFaceAnims[62];

#endif
