#ifdef VERSION_US
#include "event_063_text.inc"
#endif

static const MessageScriptEntry sEvent063Script[15] = {
    { PORTRAIT_MARLUXIA, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text00), 0, 260 },
    { PORTRAIT_AXEL, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text01), 0, 280 },
    { PORTRAIT_MARLUXIA, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text02), 0, 300 },
    { PORTRAIT_MARLUXIA, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text03), 0, 302 },
    { PORTRAIT_MARLUXIA, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text04), 0, 304 },
    { PORTRAIT_AXEL, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text05), 0, 330 },
    { PORTRAIT_AXEL, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text06), 0, 332 },
    { PORTRAIT_AXEL, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text07), 0, 334 },
    { PORTRAIT_AXEL, 3, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text08), 0, 336 },
    { PORTRAIT_MARLUXIA, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text09), 0, 360 },
    { PORTRAIT_AXEL, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text10), 0, 390 },
    { PORTRAIT_AXEL, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text11), 0, 392 },
    { PORTRAIT_MARLUXIA, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text12), 0, 420 },
    { PORTRAIT_AXEL, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text13), 0, 450 },
    { PORTRAIT_AXEL, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent063Text14), MSG_SCRIPT_FLAG_END, 700 },
};

#ifdef VERSION_JP
#include "event_063_text.inc"
#endif

static const EventCameraKeyframe sEvent063Camera[5] = {
    { -65346, 190464, 70144, 0, 255, 0, 0, NULL },
    { -64946, 180480, 65792, 0, 255, CAMERA_MODE_APPROACH, 30, NULL },
    { -64936, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_MODE_KEEP, 10, NULL },
    { -64906, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 20, NULL },
    { -64537, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EvSoundCue sEvent063SoundCues[4] = {
    { SONG_BGM_EVENT_XIII, 0, 0, 0 },
    { SONG_EV_EV34_02, 510, 0, 0 },
    { SONG_EV_EV34_03, 599, 0, 0 },
    { SONG_BGM_EVENT_XIII, 745, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent063Track0[15] = {
    { 485, 99, 0, 0, 0, 0, 2, NULL, NULL },
    { 485, 100, 194560, 46848, 0, 0, 2, NULL, NULL },
    { 494, 210, 170240, 66304, 0, 485, 3, NULL, NULL },
    { 485, 220, 0, 0, 0, 0, 5, NULL, NULL },
    { 485, 275, 0, 0, 0, 0, 69, NULL, NULL },
    { 509, 333, 0, 0, 0, 0, 69, NULL, NULL },
    { 485, 335, 0, 0, 0, 0, 69, NULL, NULL },
    { 499, 337, 0, 0, 0, 0, 69, NULL, NULL },
    { 485, 391, 0, 0, 0, 0, 69, NULL, NULL },
    { 495, 410, 0, 0, 0, 0, 69, NULL, NULL },
    { 485, 500, 0, 0, 0, 0, 69, NULL, NULL },
    { 490, 551, 0, 0, 0, 0, 69, NULL, NULL },
    { 491, 599, 0, 0, 0, 0, 69, NULL, NULL },
    { 492, 650, 0, 0, 0, 0, 69, NULL, NULL },
    { 493, 670, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent063Track1[4] = {
    { 841, 200, 191232, 78592, 0, 0, 2, NULL, NULL },
    { 841, 230, 0, 0, 0, 0, 5, NULL, NULL },
    { 842, 240, 0, 0, 0, 0, 5, NULL, NULL },
    { 842, 250, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent063Track2[3] = {
    { 485, 586, 0, 0, 0, 0, 66, NULL, NULL },
    { 512, 599, 170240, 66304, 0, 0, 66, NULL, NULL },
    { 485, 999, 0, 0, 0, 0, 32834, NULL, NULL },
};

static const EventCharaTrack sEvent063Tracks[3] = {
    { sEvent063Track0, EVENT_CHARA_AXEL },
    { sEvent063Track1, EVENT_CHARA_MARLUXIA },
    { sEvent063Track2, EVENT_CHARA_AXEL },
};

const EventSequenceDef gEvent063 = {
    3,
    sEvent063Tracks,
    sEvent063Camera,
    sEvent063Script,
    sEvent063SoundCues,
    NULL,
    750,
    0,
    0,
    0,
    0,
    1,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
