#ifdef VERSION_US
#include "event_064_text.inc"
#endif

static const MessageScriptEntry sEvent064Script[16] = {
    { 20, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text00), 0, 150 },
    { 20, 3, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text01), 0, 152 },
    { 58, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text02), 0, 180 },
    { 20, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text03), 0, 230 },
    { 20, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text04), 0, 232 },
    { 20, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text05), 0, 280 },
    { 58, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text06), 0, 300 },
    { 58, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text07), 0, 400 },
    { 20, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text08), 0, 550 },
    { 58, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text09), 0, 580 },
    { 20, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text10), 0, 650 },
    { 0, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text11), 0, 670 },
    { 20, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text12), 0, 690 },
    { 20, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text13), 0, 770 },
    { 20, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text14), 0, 772 },
    { 20, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent064Text15), MSG_SCRIPT_FLAG_END, 830 },
};

#ifdef VERSION_JP
#include "event_064_text.inc"
#endif

static const EventCameraKeyframe sEvent064Camera[3] = {
    { -65046, 182016, 66304, 0, 255, 0, 0, NULL },
    { -64881, 170752, 66560, 0, 255, CAMERA_MODE_APPROACH, 30, NULL },
    { -64537, 164352, 66560, 0, 255, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_APPROACH, 50, NULL },
};

static const EvSoundCue sEvent064SoundCues[6] = {
    { SONG_BGM_EVENT_XIII, 0, 0, 0 },
    { SONG_EV_EV34_03, 270, 0, 0 },
    { SONG_BGM_EVENT_XIII, 450, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_EV_WARPIN, 635, 0, 0 },
    { SONG_BGM_EVENT2, 780, 0, 0 },
    { SONG_EV_EV34_03, 790, EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent064Track0[6] = {
    { 510, 240, 175872, 67584, 0, 0, 66, NULL, NULL },
    { 503, 270, 0, 0, 0, 0, 69, NULL, NULL },
    { 493, 410, 0, 0, 0, 0, 69, NULL, NULL },
    { 510, 460, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 510, 790, 0, 0, 0, 0, 5, NULL, NULL },
    { 511, 999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent064Track1[4] = {
    { 842, 615, 190720, 80128, 0, 0, 2, NULL, NULL },
    { 844, 635, 185600, 76544, 0, 842, 3, NULL, NULL },
    { 842, 655, 0, 0, 0, 0, 0, EventCharaFadeOut, NULL },
    { 842, 1000, 0, 0, 0, 0, 32770, NULL, NULL },
};

static const EventCharaKeyframe sEvent064Track2[7] = {
    { 428, 190, 0, 0, 0, 0, 8194, NULL, NULL },
    { 428, 210, 184320, 75008, 0, 0, 16386, EventCharaFadeIn, NULL },
    { 428, 240, 0, 0, 0, 0, 5, NULL, NULL },
    { 428, 290, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 428, 635, 0, 0, 0, 0, 5, NULL, NULL },
    { 428, 655, 0, 0, 0, 0, 0, EventCharaFadeOut, NULL },
    { 428, 9999, 0, 0, 0, 0, 32770, NULL, NULL },
};

static const EventCharaKeyframe sEvent064Track3[6] = {
    { 4, 450, 139520, 86272, 0, 0, 66, NULL, NULL },
    { 14, 520, 164096, 74240, 0, 4, 67, NULL, NULL },
    { 4, 522, 0, 0, 0, 45, 68, NULL, NULL },
    { 4, 590, 0, 0, 0, 0, 69, NULL, NULL },
    { 19, 600, 0, 0, 0, 0, 69, NULL, NULL },
    { 21, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent064Track4[6] = {
    { 114, 450, 132352, 89088, 0, 0, 66, NULL, NULL },
    { 120, 530, 154112, 76288, 0, 114, 67, NULL, NULL },
    { 114, 532, 0, 0, 0, 45, 68, NULL, NULL },
    { 114, 595, 0, 0, 0, 0, 69, NULL, NULL },
    { 122, 605, 0, 0, 0, 0, 69, NULL, NULL },
    { 123, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent064Track5[6] = {
    { 146, 450, 142848, 94720, 0, 0, 66, NULL, NULL },
    { 153, 530, 160512, 82944, 0, 146, 67, NULL, NULL },
    { 146, 532, 0, 0, 0, 45, 68, NULL, NULL },
    { 146, 600, 0, 0, 0, 0, 69, NULL, NULL },
    { 157, 600, 0, 0, 0, 0, 69, NULL, NULL },
    { 158, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaTrack sEvent064Tracks[6] = {
    { sEvent064Track0, 43 },
    { sEvent064Track1, 79 },
    { sEvent064Track2, 35 },
    { sEvent064Track3, 0 },
    { sEvent064Track4, 1 },
    { sEvent064Track5, 2 },
};

const EventSequenceDef gEvent064 = {
    6,
    sEvent064Tracks,
    sEvent064Camera,
    sEvent064Script,
    sEvent064SoundCues,
    NULL,
    880,
    0,
    1,
    0,
    0,
    0,
    BATTLE_AXEL_2,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
