#ifdef VERSION_US
#include "event_075_text.inc"
static const MessageScriptEntry sEvent075Script[22] = {
    { 6, 2, 2, 1, { 0, 0, 0 }, gEvent075Text00, 0, 110 },
    { 17, 0, 0, 1, { 0, 0, 0 }, gEvent075Text01, 0, 210 },
    { 6, 2, 2, 1, { 0, 0, 0 }, gEvent075Text02, 0, 220 },
    { 17, 0, 0, 1, { 0, 0, 0 }, gEvent075Text03, 0, 230 },
    { 1, 5, 2, 1, { 0, 0, 0 }, gEvent075Text04, 0, 370 },
    { 2, 2, 1, 1, { 0, 0, 0 }, gEvent075Text05, 0, 390 },
    { 17, 2, 0, 1, { 0, 0, 0 }, gEvent075Text06, 0, 400 },
    { 0, 0, 3, 1, { 0, 0, 0 }, gEvent075Text07, 0, 410 },
    { 0, 5, 4, 1, { 0, 0, 0 }, gEvent075Text08, 0, 412 },
    { 17, 2, 0, 1, { 0, 0, 0 }, gEvent075Text09, 0, 430 },
    { 17, 2, 4, 1, { 0, 0, 0 }, gEvent075Text10, 0, 432 },
    { 0, 0, 3, 1, { 0, 0, 0 }, gEvent075Text11, 0, 470 },
    { 17, 0, 0, 1, { 0, 0, 0 }, gEvent075Text12, 0, 480 },
    { 6, 1, 3, 1, { 0, 0, 0 }, gEvent075Text13, 0, 490 },
    { 17, 2, 0, 1, { 0, 0, 0 }, gEvent075Text14, 0, 500 },
    { 0, 3, 3, 1, { 0, 0, 0 }, gEvent075Text15, 0, 580 },
    { 1, 0, 2, 1, { 0, 0, 0 }, gEvent075Text16, 0, 590 },
    { 17, 0, 0, 1, { 0, 0, 0 }, gEvent075Text17, 0, 600 },
    { 17, 1, 4, 1, { 0, 0, 0 }, gEvent075Text18, 0, 604 },
    { 6, 1, 3, 1, { 0, 0, 0 }, gEvent075Text19, 0, 620 },
    { 0, 1, 3, 1, { 0, 0, 0 }, gEvent075Text20, 0, 660 },
    { 0, 0, 4, 1, { 0, 0, 0 }, gEvent075Text21, MSG_SCRIPT_FLAG_END, 662 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent075Script[24] = {
    { 6, 2, 2, 3, { 0, 0, 0 }, gEvent075Text00, 0, 110 },
    { 17, 0, 0, 3, { 0, 0, 0 }, gEvent075Text01, 0, 210 },
    { 6, 2, 2, 3, { 0, 0, 0 }, gEvent075Text02, 0, 220 },
    { 17, 0, 0, 3, { 0, 0, 0 }, gEvent075Text03, 0, 230 },
    { 1, 5, 2, 3, { 0, 0, 0 }, gEvent075Text04, 0, 370 },
    { 2, 2, 1, 3, { 0, 0, 0 }, gEvent075Text05, 0, 390 },
    { 17, 2, 0, 3, { 0, 0, 0 }, gEvent075Text06, 0, 400 },
    { 0, 0, 3, 3, { 0, 0, 0 }, gEvent075Text07, 0, 410 },
    { 0, 5, 4, 3, { 0, 0, 0 }, gEvent075Text08, 0, 412 },
    { 17, 2, 0, 3, { 0, 0, 0 }, gEvent075Text09, 0, 430 },
    { 17, 2, 4, 3, { 0, 0, 0 }, gEvent075Text10, 0, 432 },
    { 0, 0, 3, 3, { 0, 0, 0 }, gEvent075Text11, 0, 470 },
    { 17, 0, 0, 3, { 0, 0, 0 }, gEvent075Text12, 0, 480 },
    { 6, 1, 3, 3, { 0, 0, 0 }, gEvent075Text13, 0, 490 },
    { 17, 2, 0, 3, { 0, 0, 0 }, gEvent075Text14, 0, 500 },
    { 0, 3, 3, 3, { 0, 0, 0 }, gEvent075Text15, 0, 580 },
    { 1, 0, 2, 3, { 0, 0, 0 }, gEvent075Text16, 0, 590 },
    { 17, 0, 0, 3, { 0, 0, 0 }, gEvent075Text17, 0, 600 },
    { 17, 0, 4, 3, { 0, 0, 0 }, gEvent075Text18, 0, 602 },
    { 17, 1, 4, 3, { 0, 0, 0 }, gEvent075Text19, 0, 604 },
    { 6, 1, 3, 3, { 0, 0, 0 }, gEvent075Text20, 0, 620 },
    { 6, 1, 4, 3, { 0, 0, 0 }, gEvent075Text21, 0, 625 },
    { 0, 1, 3, 3, { 0, 0, 0 }, gEvent075Text22, 0, 660 },
    { 0, 0, 4, 3, { 0, 0, 0 }, gEvent075Text23, MSG_SCRIPT_FLAG_END, 662 },
};

#include "event_075_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent075Script[22] = {
    { 6, 2, 2, 1, { 0, 0, 0 }, &gEvent075Text00, 0, 110 },
    { 17, 0, 0, 1, { 0, 0, 0 }, &gEvent075Text01, 0, 210 },
    { 6, 2, 2, 1, { 0, 0, 0 }, &gEvent075Text02, 0, 220 },
    { 17, 0, 0, 1, { 0, 0, 0 }, &gEvent075Text03, 0, 230 },
    { 1, 5, 2, 1, { 0, 0, 0 }, &gEvent075Text04, 0, 370 },
    { 2, 2, 1, 1, { 0, 0, 0 }, &gEvent075Text05, 0, 390 },
    { 17, 2, 0, 1, { 0, 0, 0 }, &gEvent075Text06, 0, 400 },
    { 0, 0, 3, 1, { 0, 0, 0 }, &gEvent075Text07, 0, 410 },
    { 0, 5, 4, 1, { 0, 0, 0 }, &gEvent075Text08, 0, 412 },
    { 17, 2, 0, 1, { 0, 0, 0 }, &gEvent075Text09, 0, 430 },
    { 17, 2, 4, 1, { 0, 0, 0 }, &gEvent075Text10, 0, 432 },
    { 0, 0, 3, 1, { 0, 0, 0 }, &gEvent075Text11, 0, 470 },
    { 17, 0, 0, 1, { 0, 0, 0 }, &gEvent075Text12, 0, 480 },
    { 6, 1, 3, 1, { 0, 0, 0 }, &gEvent075Text13, 0, 490 },
    { 17, 2, 0, 1, { 0, 0, 0 }, &gEvent075Text14, 0, 500 },
    { 0, 3, 3, 1, { 0, 0, 0 }, &gEvent075Text15, 0, 580 },
    { 1, 0, 2, 1, { 0, 0, 0 }, &gEvent075Text16, 0, 590 },
    { 17, 0, 0, 1, { 0, 0, 0 }, &gEvent075Text17, 0, 600 },
    { 17, 1, 4, 1, { 0, 0, 0 }, &gEvent075Text18, 0, 604 },
    { 6, 1, 3, 1, { 0, 0, 0 }, &gEvent075Text19, 0, 620 },
    { 0, 1, 3, 1, { 0, 0, 0 }, &gEvent075Text20, 0, 660 },
    { 0, 0, 4, 1, { 0, 0, 0 }, &gEvent075Text21, MSG_SCRIPT_FLAG_END, 662 },
};
#endif

static const EventCameraKeyframe sEvent075Camera[7] = {
    { -65496, 30464, 46592, 0, 255, { 0, 0, 0 }, 0, 0, { 0, 0 }, NULL },
    { -65286, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -65241, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_OUT_BLACK | CAMERA_MODE_KEEP, 45, { 0, 0 }, NULL },
    { -65221, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -65220, 81408, 76032, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 0, { 0, 0 }, NULL },
    { -65176, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_IN_BLACK | CAMERA_MODE_KEEP, 45, { 0, 0 }, NULL },
    { -65136, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
};

static const EvSoundCue sEvent075SoundCues[6] = {
    { SONG_BGM_PINOCCHIO_FIELD, 0, 0, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 250, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_EVENT4, 430, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT4, 605, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 622, 0, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 775, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent075Track0[23] = {
    { 7, 0, { 0, 0 }, 9728, 51200, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 7, 80, { 0, 0 }, 13568, 59136, 0, 2, { 0, 0 }, 67, NULL, NULL },
    { 2, 200, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 3, 300, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 408, { 0, 0 }, 74496, 77568, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 32, 433, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 15, 459, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 501, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 540, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 4, 560, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 575, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 579, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 31, 581, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 630, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 15, 648, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 661, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 31, 663, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 2, 691, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 1, 693, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 2, 696, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 2, 710, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 12, 750, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 36, NULL, NULL },
    { 12, 760, { 0, 0 }, 0, 0, 0, 83, { 0, 0 }, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track1[15] = {
    { 112, 20, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 117, 21, { 0, 0 }, 9728, 51200, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 117, 100, { 0, 0 }, 5632, 62464, 0, 112, { 0, 0 }, 3, NULL, NULL },
    { 113, 300, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 114, 369, { 0, 0 }, 75264, 87040, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 126, 371, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 114, 589, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 126, 591, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 114, 700, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 110, 705, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 114, 710, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 113, 725, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 112, 785, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 121, 800, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 36, NULL, NULL },
    { 121, 900, { 0, 0 }, 0, 0, 0, 83, { 0, 0 }, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track2[13] = {
    { 144, 20, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 144, 21, { 0, 0 }, 9728, 51200, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 149, 110, { 0, 0 }, 20736, 55296, 0, 144, { 0, 0 }, 67, NULL, NULL },
    { 144, 205, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 145, 300, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 144, 389, { 0, 0 }, 87040, 77824, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 164, 391, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 144, 702, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 145, 708, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 146, 718, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 153, 740, { 0, 0 }, 0, 0, 0, 211, { 0, 0 }, 36, NULL, NULL },
    { 152, 820, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 36, NULL, NULL },
    { 152, 920, { 0, 0 }, 0, 0, 0, 83, { 0, 0 }, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track3[8] = {
    { 229, 115, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 230, 116, { 0, 0 }, 13568, 59136, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 233, 140, { 0, 0 }, 0, 0, 0, 83, { 0, 0 }, 100, EventCharaHop, NULL },
    { 231, 300, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 229, 622, { 0, 0 }, 80640, 81408, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 231, 665, { 0, 0 }, 80640, 81408, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 234, 690, { 0, 0 }, 0, 0, 0, 211, { 0, 0 }, 4, EventCharaHop, NULL },
    { 234, 999, { 0, 0 }, 256000, 256000, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track4[6] = {
    { 341, 111, { 0, 0 }, 54528, 47616, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 341, 162, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 343, 209, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 4, NULL, NULL },
    { 341, 300, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 342, 430, { 0, 0 }, 87040, 87040, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 342, 999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaTrack sEvent075Tracks[5] = {
    { sEvent075Track0, 0, { 0, 0, 0 } },
    { sEvent075Track1, 1, { 0, 0, 0 } },
    { sEvent075Track2, 2, { 0, 0, 0 } },
    { sEvent075Track3, 8, { 0, 0, 0 } },
    { sEvent075Track4, 18, { 0, 0, 0 } },
};

const EventSequenceDef gEvent075 = {
    5,
    { 0, 0, 0 },
    sEvent075Tracks,
    sEvent075Camera,
    sEvent075Script,
    sEvent075SoundCues,
    NULL,
    780,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
