#ifdef VERSION_US
#include "event_075_text.inc"
static const MessageScriptEntry sEvent075Script[22] = {
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 1, gEvent075Text00, 0, 110 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, gEvent075Text01, 0, 210 },
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 1, gEvent075Text02, 0, 220 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, gEvent075Text03, 0, 230 },
    { PORTRAIT_DONALD, 5, 2, 1, gEvent075Text04, 0, 370 },
    { PORTRAIT_GOOFY, 2, 1, 1, gEvent075Text05, 0, 390 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, gEvent075Text06, 0, 400 },
    { PORTRAIT_SORA, 0, 3, 1, gEvent075Text07, 0, 410 },
    { PORTRAIT_SORA, 5, 4, 1, gEvent075Text08, 0, 412 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, gEvent075Text09, 0, 430 },
    { PORTRAIT_GEPPETTO, 2, 4, 1, gEvent075Text10, 0, 432 },
    { PORTRAIT_SORA, 0, 3, 1, gEvent075Text11, 0, 470 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, gEvent075Text12, 0, 480 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 1, gEvent075Text13, 0, 490 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, gEvent075Text14, 0, 500 },
    { PORTRAIT_SORA, 3, 3, 1, gEvent075Text15, 0, 580 },
    { PORTRAIT_DONALD, 0, 2, 1, gEvent075Text16, 0, 590 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, gEvent075Text17, 0, 600 },
    { PORTRAIT_GEPPETTO, 1, 4, 1, gEvent075Text18, 0, 604 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 1, gEvent075Text19, 0, 620 },
    { PORTRAIT_SORA, 1, 3, 1, gEvent075Text20, 0, 660 },
    { PORTRAIT_SORA, 0, 4, 1, gEvent075Text21, MSG_SCRIPT_FLAG_END, 662 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent075Script[24] = {
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 3, gEvent075Text00, 0, 110 },
    { PORTRAIT_GEPPETTO, 0, 0, 3, gEvent075Text01, 0, 210 },
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 3, gEvent075Text02, 0, 220 },
    { PORTRAIT_GEPPETTO, 0, 0, 3, gEvent075Text03, 0, 230 },
    { PORTRAIT_DONALD, 5, 2, 3, gEvent075Text04, 0, 370 },
    { PORTRAIT_GOOFY, 2, 1, 3, gEvent075Text05, 0, 390 },
    { PORTRAIT_GEPPETTO, 2, 0, 3, gEvent075Text06, 0, 400 },
    { PORTRAIT_SORA, 0, 3, 3, gEvent075Text07, 0, 410 },
    { PORTRAIT_SORA, 5, 4, 3, gEvent075Text08, 0, 412 },
    { PORTRAIT_GEPPETTO, 2, 0, 3, gEvent075Text09, 0, 430 },
    { PORTRAIT_GEPPETTO, 2, 4, 3, gEvent075Text10, 0, 432 },
    { PORTRAIT_SORA, 0, 3, 3, gEvent075Text11, 0, 470 },
    { PORTRAIT_GEPPETTO, 0, 0, 3, gEvent075Text12, 0, 480 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 3, gEvent075Text13, 0, 490 },
    { PORTRAIT_GEPPETTO, 2, 0, 3, gEvent075Text14, 0, 500 },
    { PORTRAIT_SORA, 3, 3, 3, gEvent075Text15, 0, 580 },
    { PORTRAIT_DONALD, 0, 2, 3, gEvent075Text16, 0, 590 },
    { PORTRAIT_GEPPETTO, 0, 0, 3, gEvent075Text17, 0, 600 },
    { PORTRAIT_GEPPETTO, 0, 4, 3, gEvent075Text18, 0, 602 },
    { PORTRAIT_GEPPETTO, 1, 4, 3, gEvent075Text19, 0, 604 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 3, gEvent075Text20, 0, 620 },
    { PORTRAIT_JIMINY_CRICKET, 1, 4, 3, gEvent075Text21, 0, 625 },
    { PORTRAIT_SORA, 1, 3, 3, gEvent075Text22, 0, 660 },
    { PORTRAIT_SORA, 0, 4, 3, gEvent075Text23, MSG_SCRIPT_FLAG_END, 662 },
};

#include "event_075_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent075Script[22] = {
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 1, &gEvent075Text00ByLanguage, 0, 110 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, &gEvent075Text01ByLanguage, 0, 210 },
    { PORTRAIT_JIMINY_CRICKET, 2, 2, 1, &gEvent075Text02ByLanguage, 0, 220 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, &gEvent075Text03ByLanguage, 0, 230 },
    { PORTRAIT_DONALD, 5, 2, 1, &gEvent075Text04ByLanguage, 0, 370 },
    { PORTRAIT_GOOFY, 2, 1, 1, &gEvent075Text05ByLanguage, 0, 390 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, &gEvent075Text06ByLanguage, 0, 400 },
    { PORTRAIT_SORA, 0, 3, 1, &gEvent075Text07ByLanguage, 0, 410 },
    { PORTRAIT_SORA, 5, 4, 1, &gEvent075Text08ByLanguage, 0, 412 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, &gEvent075Text09ByLanguage, 0, 430 },
    { PORTRAIT_GEPPETTO, 2, 4, 1, &gEvent075Text10ByLanguage, 0, 432 },
    { PORTRAIT_SORA, 0, 3, 1, &gEvent075Text11ByLanguage, 0, 470 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, &gEvent075Text12ByLanguage, 0, 480 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 1, &gEvent075Text13ByLanguage, 0, 490 },
    { PORTRAIT_GEPPETTO, 2, 0, 1, &gEvent075Text14ByLanguage, 0, 500 },
    { PORTRAIT_SORA, 3, 3, 1, &gEvent075Text15ByLanguage, 0, 580 },
    { PORTRAIT_DONALD, 0, 2, 1, &gEvent075Text16ByLanguage, 0, 590 },
    { PORTRAIT_GEPPETTO, 0, 0, 1, &gEvent075Text17ByLanguage, 0, 600 },
    { PORTRAIT_GEPPETTO, 1, 4, 1, &gEvent075Text18ByLanguage, 0, 604 },
    { PORTRAIT_JIMINY_CRICKET, 1, 3, 1, &gEvent075Text19ByLanguage, 0, 620 },
    { PORTRAIT_SORA, 1, 3, 1, &gEvent075Text20ByLanguage, 0, 660 },
    { PORTRAIT_SORA, 0, 4, 1, &gEvent075Text21ByLanguage, MSG_SCRIPT_FLAG_END, 662 },
};
#endif

static const EventCameraKeyframe sEvent075Camera[7] = {
    { -65496, 30464, 46592, 0, 255, 0, 0, NULL },
    { -65286, 0, 0, 0, 255, CAMERA_MODE_KEEP, 0, NULL },
    { -65241, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_OUT_BLACK | CAMERA_MODE_KEEP, 45, NULL },
    { -65221, 0, 0, 0, 255, CAMERA_MODE_KEEP, 0, NULL },
    { -65220, 81408, 76032, 0, 255, CAMERA_MODE_APPROACH, 0, NULL },
    { -65176, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_BLACK | CAMERA_MODE_KEEP, 45, NULL },
    { -65136, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EvSoundCue sEvent075SoundCues[6] = {
    { SONG_BGM_PINOCCHIO_FIELD, 0, 0, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 250, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_EVENT4, 430, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT4, 605, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 622, 0, 0 },
    { SONG_BGM_PINOCCHIO_FIELD, 775, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent075Track0[23] = {
    { 7, 0, 9728, 51200, 0, 0, 66, NULL, NULL },
    { 7, 80, 13568, 59136, 0, 2, 67, NULL, NULL },
    { 2, 200, 0, 0, 0, 0, 69, NULL, NULL },
    { 3, 300, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 408, 74496, 77568, 0, 0, 66, NULL, NULL },
    { 32, 433, 0, 0, 0, 0, 69, NULL, NULL },
    { 15, 459, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 501, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 540, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 4, 560, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 575, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 579, 0, 0, 0, 0, 69, NULL, NULL },
    { 31, 581, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 630, 0, 0, 0, 0, 69, NULL, NULL },
    { 15, 648, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 661, 0, 0, 0, 0, 69, NULL, NULL },
    { 31, 663, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 691, 0, 0, 0, 0, 69, NULL, NULL },
    { 1, 693, 0, 0, 0, 0, 5, NULL, NULL },
    { 2, 696, 0, 0, 0, 0, 5, NULL, NULL },
    { 2, 710, 0, 0, 0, 0, 5, NULL, NULL },
    { 12, 750, 0, 0, 0, 173, 36, NULL, NULL },
    { 12, 760, 0, 0, 0, 83, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track1[15] = {
    { 112, 20, 0, 0, 0, 0, 2, NULL, NULL },
    { 117, 21, 9728, 51200, 0, 0, 2, NULL, NULL },
    { 117, 100, 5632, 62464, 0, 112, 3, NULL, NULL },
    { 113, 300, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 369, 75264, 87040, 0, 0, 66, NULL, NULL },
    { 126, 371, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 589, 0, 0, 0, 0, 69, NULL, NULL },
    { 126, 591, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 700, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 705, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 710, 0, 0, 0, 0, 5, NULL, NULL },
    { 113, 725, 0, 0, 0, 0, 5, NULL, NULL },
    { 112, 785, 0, 0, 0, 0, 5, NULL, NULL },
    { 121, 800, 0, 0, 0, 173, 36, NULL, NULL },
    { 121, 900, 0, 0, 0, 83, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track2[13] = {
    { 144, 20, 0, 0, 0, 0, 66, NULL, NULL },
    { 144, 21, 9728, 51200, 0, 0, 66, NULL, NULL },
    { 149, 110, 20736, 55296, 0, 144, 67, NULL, NULL },
    { 144, 205, 0, 0, 0, 0, 69, NULL, NULL },
    { 145, 300, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 389, 87040, 77824, 0, 0, 2, NULL, NULL },
    { 164, 391, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 702, 0, 0, 0, 0, 5, NULL, NULL },
    { 145, 708, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 718, 0, 0, 0, 0, 5, NULL, NULL },
    { 153, 740, 0, 0, 0, 211, 36, NULL, NULL },
    { 152, 820, 0, 0, 0, 173, 36, NULL, NULL },
    { 152, 920, 0, 0, 0, 83, 32868, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track3[8] = {
    { 229, 115, 0, 0, 0, 0, 66, NULL, NULL },
    { 230, 116, 13568, 59136, 0, 0, 66, NULL, NULL },
    { 233, 140, 0, 0, 0, 83, 100, EventCharaHop, NULL },
    { 231, 300, 0, 0, 0, 0, 69, NULL, NULL },
    { 229, 622, 80640, 81408, 0, 0, 66, NULL, NULL },
    { 231, 665, 80640, 81408, 0, 0, 2, NULL, NULL },
    { 234, 690, 0, 0, 0, 211, 4, EventCharaHop, NULL },
    { 234, 999, 256000, 256000, 0, 0, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent075Track4[6] = {
    { 341, 111, 54528, 47616, 0, 0, 66, NULL, NULL },
    { 341, 162, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 343, 209, 0, 0, 0, 173, 4, NULL, NULL },
    { 341, 300, 0, 0, 0, 0, 5, NULL, NULL },
    { 342, 430, 87040, 87040, 0, 0, 2, NULL, NULL },
    { 342, 999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaTrack sEvent075Tracks[5] = {
    { sEvent075Track0, EVENT_CHARA_SORA },
    { sEvent075Track1, EVENT_CHARA_DONALD },
    { sEvent075Track2, EVENT_CHARA_GOOFY },
    { sEvent075Track3, EVENT_CHARA_JIMINY_CRICKET },
    { sEvent075Track4, EVENT_CHARA_GEPPETTO },
};

const EventSequenceDef gEvent075 = {
    5,
    sEvent075Tracks,
    sEvent075Camera,
    sEvent075Script,
    sEvent075SoundCues,
    NULL,
    780,
    0,
    0,
    0,
    0,
    1,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
