#ifdef VERSION_US
#include "event_076_text.inc"
#endif

static const MessageScriptEntry sEvent076Script[31] = {
    { PORTRAIT_PINOCCHIO, 10, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text00), 0, 300 },
    { PORTRAIT_JIMINY_CRICKET, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text01), 0, 460 },
    { PORTRAIT_DONALD, 4, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text02), 0, 470 },
    { PORTRAIT_PINOCCHIO, 7, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text03), 0, 480 },
    { PORTRAIT_SORA, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text04), 0, 490 },
    { PORTRAIT_PINOCCHIO, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text05), 0, 500 },
    { PORTRAIT_JIMINY_CRICKET, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text06), 0, 560 },
    { PORTRAIT_PINOCCHIO, 8, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text07), 0, 570 },
    { PORTRAIT_GOOFY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text08), 0, 580 },
    { PORTRAIT_GOOFY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text09), 0, 582 },
    { PORTRAIT_GOOFY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text10), 0, 584 },
    { PORTRAIT_GOOFY, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text11), 0, 586 },
    { PORTRAIT_PINOCCHIO, 8, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text12), 0, 720 },
    { PORTRAIT_PINOCCHIO, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text13), 0, 722 },
    { PORTRAIT_PINOCCHIO, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text14), 0, 724 },
    { PORTRAIT_PINOCCHIO, 8, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text15), 0, 726 },
    { PORTRAIT_JIMINY_CRICKET, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text16), 0, 740 },
    { PORTRAIT_GOOFY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text17), 0, 750 },
    { PORTRAIT_DONALD, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text18), 0, 760 },
    { PORTRAIT_PINOCCHIO, 11, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text19), 0, 770 },
    { PORTRAIT_DONALD, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text20), 0, 780 },
    { PORTRAIT_DONALD, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text21), 0, 782 },
    { PORTRAIT_SORA, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text22), 0, 800 },
    { PORTRAIT_PINOCCHIO, 11, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text23), 0, 810 },
    { PORTRAIT_PINOCCHIO, 5, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text24), 0, 812 },
    { PORTRAIT_JIMINY_CRICKET, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text25), 0, 830 },
    { PORTRAIT_PINOCCHIO, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text26), 0, 840 },
    { PORTRAIT_JIMINY_CRICKET, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text27), 0, 850 },
    { PORTRAIT_SORA, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text28), 0, 900 },
    { PORTRAIT_DONALD, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text29), 0, 910 },
    { PORTRAIT_JIMINY_CRICKET, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent076Text30), MSG_SCRIPT_FLAG_END, 920 },
};

#ifdef VERSION_JP
#include "event_076_text.inc"
#endif

static const EvSoundCue sEvent076SoundCues[6] = {
    { SONG_BGM_PINOCCHIO_FIELD, 0, 0, 0 },
    { SONG_SND_349, 501, 0, 0 },
    { SONG_BGM_EVENT2, 851, 0, 0 },
    { SONG_EV_RUMBLE, 852, 0, 0 },
    { SONG_EV_FLASH02, 1050, 0, 0 },
    { SONG_EV_RUMBLE, 1083, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent076Camera[5] = {
    { -65136, 44800, 93696, 0, EVENT_CHARA_NONE, 0, 0, NULL },
    { -65086, 57344, 91136, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 50, NULL },
    { -64685, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_MODE_KEEP, 0, NULL },
    { -64486, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_SHAKE_MEDIUM | CAMERA_MODE_KEEP, 0, NULL },
    { -64456, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_KEYFRAME_FLAG_SHAKE_MEDIUM | CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 30, NULL },
};

static const EventCharaKeyframe sEvent076Track0[9] = {
    { 4, 301, 9472, 114944, 0, 0, 66, NULL, NULL },
    { 14, 406, 47360, 95232, 0, 4, 99, NULL, NULL },
    { 4, 410, 0, 0, 0, 45, 68, NULL, NULL },
    { 4, 795, 0, 0, 0, 0, 69, NULL, NULL },
    { 36, 802, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 851, 0, 0, 0, 0, 69, NULL, NULL },
    { 27, 900, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 30, 901, 0, 0, 0, 0, 69, NULL, NULL },
    { 29, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent076Track1[13] = {
    { 114, 301, 10496, 117504, 0, 0, 66, NULL, NULL },
    { 120, 445, 62976, 92672, 0, 114, 99, NULL, NULL },
    { 114, 449, 0, 0, 0, 45, 68, NULL, NULL },
    { 114, 458, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 469, 0, 0, 0, 0, 5, NULL, NULL },
    { 131, 471, 0, 0, 0, 0, 0, NULL, CreateSmokeTask },
    { 114, 759, 0, 0, 0, 0, 5, NULL, NULL },
    { 126, 761, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 779, 0, 0, 0, 0, 5, NULL, NULL },
    { 126, 783, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 851, 0, 0, 0, 0, 5, NULL, NULL },
    { 134, 900, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 134, 999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent076Track2[11] = {
    { 146, 301, 9216, 116736, 0, 0, 66, NULL, NULL },
    { 153, 429, 49920, 85760, 0, 146, 99, NULL, NULL },
    { 146, 433, 0, 0, 0, 45, 68, NULL, NULL },
    { 146, 453, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 579, 0, 0, 0, 0, 69, NULL, NULL },
    { 164, 587, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 749, 0, 0, 0, 0, 69, NULL, NULL },
    { 164, 751, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 851, 0, 0, 0, 0, 69, NULL, NULL },
    { 162, 900, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 162, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent076Track3[11] = {
    { 231, 410, 0, 0, 0, 0, 66, NULL, NULL },
    { 231, 411, 47360, 95232, 0, 0, 66, NULL, NULL },
    { 234, 430, 0, 0, 0, 45, 68, EventCharaHop, NULL },
    { 232, 440, 0, 0, 0, 45, 68, NULL, NULL },
    { 231, 459, 0, 0, 0, 0, 69, NULL, NULL },
    { 234, 461, 0, 0, 0, 0, 64, EventCharaHop, NULL },
    { 231, 559, 0, 0, 0, 0, 69, NULL, NULL },
    { 234, 561, 0, 0, 0, 0, 64, EventCharaHop, NULL },
    { 231, 851, 0, 0, 0, 0, 69, NULL, NULL },
    { 231, 900, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 231, 999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent076Track4[25] = {
    { 237, 0, 41984, 80640, 0, 0, 66, NULL, NULL },
    { 246, 80, 0, 0, 0, 83, 100, NULL, NULL },
    { 237, 82, 0, 0, 0, 83, 68, NULL, NULL },
    { 237, 160, 0, 0, 0, 0, 64, NULL, CreateQuestionTask },
    { 240, 165, 0, 0, 0, 0, 69, NULL, NULL },
    { 240, 170, 0, 0, 0, 0, 5, NULL, NULL },
    { 252, 200, 0, 0, 0, 211, 36, NULL, NULL },
    { 240, 204, 0, 0, 0, 211, 4, NULL, NULL },
    { 240, 280, 0, 0, 0, 0, 0, NULL, CreateQuestionTask },
    { 237, 285, 0, 0, 0, 0, 5, NULL, NULL },
    { 255, 320, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 237, 501, 0, 0, 0, 0, 5, NULL, NULL },
    { 238, 559, 0, 0, 0, 0, 0, NULL, CreateGlowNoseTask },
    { 238, 587, 0, 0, 0, 0, 5, NULL, NULL },
    { 238, 719, 0, 0, 0, 0, 0, NULL, CreateBalloonTask },
    { 238, 721, 0, 0, 0, 0, 5, NULL, NULL },
    { 238, 769, 0, 0, 0, 0, 5, NULL, NULL },
    { 238, 801, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 238, 809, 0, 0, 0, 0, 5, NULL, NULL },
    { 256, 811, 0, 0, 0, 0, 5, NULL, NULL },
    { 238, 851, 0, 0, 0, 0, 5, NULL, NULL },
    { 256, 900, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 238, 921, 0, 0, 0, 0, 5, NULL, NULL },
    { 247, 930, 0, 0, 0, 83, 100, NULL, NULL },
    { 247, 1000, 0, 0, 0, 173, 32804, NULL, NULL },
};

static const EventCharaTrack sEvent076Tracks[5] = {
    { sEvent076Track0, EVENT_CHARA_SORA },
    { sEvent076Track1, EVENT_CHARA_DONALD },
    { sEvent076Track2, EVENT_CHARA_GOOFY },
    { sEvent076Track3, EVENT_CHARA_JIMINY_CRICKET },
    { sEvent076Track4, EVENT_CHARA_PINOCCHIO },
};

const EventSequenceDef gEvent076 = {
    5,
    sEvent076Tracks,
    sEvent076Camera,
    sEvent076Script,
    sEvent076SoundCues,
    NULL,
    1090,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    0,
    EVENT_077_MONSTORO_E2_2,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    0,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
