#ifdef VERSION_US
#include "event_087_text.inc"
static const MessageScriptEntry sEvent087Script[18] = {
    { 2, 3, 2, 1, gEvent087Text00, 0, 260 },
    { 1, 1, 0, 1, gEvent087Text01, 0, 280 },
    { 1, 1, 4, 1, gEvent087Text02, 0, 282 },
    { 2, 3, 2, 1, gEvent087Text03, 0, 300 },
    { 1, 4, 0, 1, gEvent087Text04, 0, 315 },
    { 11, 0, 0, 1, gEvent087Text05, MSG_SCRIPT_FLAG_SILHOUETTE, 330 },
    { 1, 5, 3, 1, gEvent087Text06, 0, 650 },
    { 11, 1, 1, 1, gEvent087Text07, 0, 700 },
    { 11, 0, 4, 1, gEvent087Text08, 0, 702 },
    { 11, 0, 1, 1, gEvent087Text09, 0, 740 },
    { 11, 0, 4, 1, gEvent087Text10, 0, 742 },
    { 11, 2, 1, 1, gEvent087Text11, 0, 780 },
    { 11, 0, 4, 1, gEvent087Text12, 0, 782 },
    { 1, 4, 2, 1, gEvent087Text13, 0, 800 },
    { 11, 3, 1, 1, gEvent087Text14, 0, 810 },
    { 0, 0, 2, 1, gEvent087Text15, 0, 820 },
    { 11, 0, 1, 1, gEvent087Text16, 0, 830 },
    { 0, 3, 3, 1, gEvent087Text17, MSG_SCRIPT_FLAG_END, 880 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent087Script[19] = {
    { 2, 3, 2, 3, gEvent087Text00, 0, 260 },
    { 1, 1, 0, 3, gEvent087Text01, 0, 280 },
    { 1, 1, 4, 3, gEvent087Text02, 0, 282 },
    { 2, 3, 2, 3, gEvent087Text03, 0, 300 },
    { 1, 4, 0, 3, gEvent087Text04, 0, 315 },
    { 11, 0, 0, 3, gEvent087Text05, MSG_SCRIPT_FLAG_SILHOUETTE, 330 },
    { 1, 5, 3, 3, gEvent087Text06, 0, 650 },
    { 11, 1, 1, 3, gEvent087Text07, 0, 700 },
    { 11, 0, 4, 3, gEvent087Text08, 0, 702 },
    { 11, 0, 1, 3, gEvent087Text09, 0, 740 },
    { 11, 0, 4, 3, gEvent087Text10, 0, 742 },
    { 11, 2, 1, 3, gEvent087Text11, 0, 780 },
    { 11, 0, 4, 3, gEvent087Text12, 0, 782 },
    { 1, 4, 2, 3, gEvent087Text13, 0, 800 },
    { 11, 3, 1, 3, gEvent087Text14, 0, 810 },
    { 0, 0, 2, 3, gEvent087Text15, 0, 820 },
    { 11, 0, 1, 3, gEvent087Text16, 0, 830 },
    { 11, 2, 4, 3, gEvent087Text17, 0, 832 },
    { 0, 3, 3, 3, gEvent082Text01, MSG_SCRIPT_FLAG_END, 880 },
};

#include "event_087_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent087Script[18] = {
    { 2, 3, 2, 1, &gEvent087Text00ByLanguage, 0, 260 },
    { 1, 1, 0, 1, &gEvent087Text01ByLanguage, 0, 280 },
    { 1, 1, 4, 1, &gEvent087Text02ByLanguage, 0, 282 },
    { 2, 3, 2, 1, &gEvent087Text03ByLanguage, 0, 300 },
    { 1, 4, 0, 1, &gEvent087Text04ByLanguage, 0, 315 },
    { 11, 0, 0, 1, &gEvent087Text05ByLanguage, MSG_SCRIPT_FLAG_SILHOUETTE, 330 },
    { 1, 5, 3, 1, &gEvent087Text06ByLanguage, 0, 650 },
    { 11, 1, 1, 1, &gEvent087Text07ByLanguage, 0, 700 },
    { 11, 0, 4, 1, &gEvent087Text08ByLanguage, 0, 702 },
    { 11, 0, 1, 1, &gEvent087Text09ByLanguage, 0, 740 },
    { 11, 0, 4, 1, &gEvent087Text10ByLanguage, 0, 742 },
    { 11, 2, 1, 1, &gEvent087Text11ByLanguage, 0, 780 },
    { 11, 0, 4, 1, &gEvent087Text12ByLanguage, 0, 782 },
    { 1, 4, 2, 1, &gEvent087Text13ByLanguage, 0, 800 },
    { 11, 3, 1, 1, &gEvent087Text14ByLanguage, 0, 810 },
    { 0, 0, 2, 1, &gEvent087Text15ByLanguage, 0, 820 },
    { 11, 0, 1, 1, &gEvent087Text16ByLanguage, 0, 830 },
    { 0, 3, 3, 1, &gEvent087Text17ByLanguage, MSG_SCRIPT_FLAG_END, 880 },
};
#endif

static const EvSoundCue sEvent087SoundCues[6] = {
    { 65535, 0, 0, 0 },
    { SONG_EV_DL_JUMP, 313, 0, 0 },
    { SONG_SND_347, 490, 0, 0 },
    { SONG_EV_DL_JUMP, 649, 0, 0 },
    { SONG_BGM_HALLOWEEN_FIELD, 700, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT2, 833, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent087Camera[3] = {
    { -65536, 30720, 20480, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE, 0, NULL },
    { -65205, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 80, NULL },
    { -64537, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EventBgEffectEntry sEvent087BgEffects[6] = {
    { 331, 0, 0, 0, 0 },
    { 332, 0, 0, 0, 0x4 },
    { 488, 0, 0, 0, 0 },
    { 640, 0, 0, 0, 0x1 },
    { 680, 0, 0, 0, 0x2 },
    { 701, 0, 0, 0, 0x8008 },
};

static const EventCharaKeyframe sEvent087Track0[22] = {
    { 4, 0, -9728, 43264, 0, 0, 66, NULL, NULL },
    { 9, 150, 20480, 25344, 0, 4, 67, NULL, NULL },
    { 4, 160, 0, 0, 0, 0, 69, NULL, NULL },
    { 0, 170, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 180, 0, 0, 0, 0, 69, NULL, NULL },
    { 0, 190, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 220, 0, 0, 0, 0, 5, NULL, NULL },
    { 0, 230, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 250, 0, 0, 0, 0, 69, NULL, NULL },
    { 1, 331, 0, 0, 0, 0, 5, NULL, NULL },
    { 1, 380, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 2, 390, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 410, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 435, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 450, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 470, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 490, 0, 0, 0, 0, 69, NULL, NULL },
    { 27, 640, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 28, 730, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 4, 819, 0, 0, 0, 0, 69, NULL, NULL },
    { 34, 835, 0, 0, 0, 0, 69, NULL, NULL },
    { 27, 990, 0, 0, 0, 0, 32832, NULL, CreateExclamationTask },
};

static const EventCharaKeyframe sEvent087Track1[11] = {
    { 288, 490, 256000, 256000, 0, 0, 2, NULL, NULL },
    { 295, 640, 37888, 22016, 0, 0, 1026, NULL, NULL },
    { 294, 681, 0, 0, 0, 0, 261, NULL, NULL },
    { 295, 730, 0, 0, 0, 0, 0, EventCharaFadeIn, NULL },
    { 288, 743, 0, 0, 0, 0, 5, NULL, NULL },
    { 289, 748, 0, 0, 0, 0, 69, NULL, NULL },
    { 296, 775, 0, 0, 0, 45, 68, NULL, NULL },
    { 289, 779, 0, 0, 0, 0, 69, NULL, NULL },
    { 292, 809, 0, 0, 0, 0, 5, NULL, NULL },
    { 288, 831, 0, 0, 0, 0, 5, NULL, NULL },
    { 292, 999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent087Track2[31] = {
    { 112, 0, -6400, 52224, 0, 0, 2, NULL, NULL },
    { 119, 150, 25600, 30464, 0, 114, 67, NULL, NULL },
    { 114, 160, 0, 0, 0, 0, 69, NULL, NULL },
    { 111, 170, 0, 0, 0, 0, 5, NULL, NULL },
    { 112, 180, 0, 0, 0, 0, 69, NULL, NULL },
    { 113, 200, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 210, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 220, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 230, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 250, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 261, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 270, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 279, 0, 0, 0, 0, 5, NULL, NULL },
    { 126, 283, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 309, 0, 0, 0, 0, 5, NULL, NULL },
    { 130, 316, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 331, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 380, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 110, 390, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 415, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 430, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 450, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 470, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 490, 0, 0, 0, 0, 69, NULL, NULL },
    { 133, 640, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 114, 641, 0, 0, 0, 0, 69, NULL, NULL },
    { 133, 738, 0, 0, 0, 0, 64, EventCharaHopHigh, NULL },
    { 114, 799, 0, 0, 0, 0, 69, NULL, NULL },
    { 131, 801, 0, 0, 0, 0, 64, NULL, CreateSmokeTask },
    { 114, 835, 0, 0, 0, 0, 69, NULL, NULL },
    { 133, 990, 0, 0, 0, 0, 32832, NULL, CreateExclamationTask },
};

static const EventCharaKeyframe sEvent087Track3[27] = {
    { 144, 20, -17920, 45824, 0, 0, 2, NULL, NULL },
    { 151, 150, 12288, 26368, 0, 146, 67, NULL, NULL },
    { 143, 160, 0, 0, 0, 0, 5, NULL, NULL },
    { 143, 170, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 180, 0, 0, 0, 0, 69, NULL, NULL },
    { 143, 190, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 210, 0, 0, 0, 0, 5, NULL, NULL },
    { 145, 220, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 210, 0, 0, 0, 0, 5, NULL, NULL },
    { 143, 230, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 259, 0, 0, 0, 0, 69, NULL, NULL },
    { 164, 261, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 299, 0, 0, 0, 0, 69, NULL, NULL },
    { 164, 301, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 331, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 380, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 144, 390, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 410, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 425, 0, 0, 0, 0, 69, NULL, NULL },
    { 144, 440, 0, 0, 0, 0, 5, NULL, NULL },
    { 144, 460, 0, 0, 0, 0, 69, NULL, NULL },
    { 145, 475, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 490, 0, 0, 0, 0, 69, NULL, NULL },
    { 161, 640, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 161, 734, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 146, 835, 0, 0, 0, 0, 69, NULL, NULL },
    { 161, 999, 0, 0, 0, 0, 32832, NULL, CreateExclamationTask },
};

static const EventCharaKeyframe sEvent087Track4[3] = {
    { 477, 833, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 475, 853, 40448, 32768, 0, 0, 16642, NULL, NULL },
    { 472, 999, 0, 0, 0, 0, 33029, NULL, NULL },
};

static const EventCharaKeyframe sEvent087Track5[3] = {
    { 477, 838, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 475, 858, 38656, 24832, 0, 0, 16642, NULL, NULL },
    { 472, 999, 0, 0, 0, 0, 33029, NULL, NULL },
};

static const EventCharaKeyframe sEvent087Track6[3] = {
    { 477, 843, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 475, 863, 33792, 20224, 0, 0, 16642, NULL, NULL },
    { 472, 999, 0, 0, 0, 0, 33029, NULL, NULL },
};

static const EventCharaKeyframe sEvent087Track7[3] = {
    { 477, 848, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 475, 868, 13824, 16896, 0, 0, 16706, NULL, NULL },
    { 472, 999, 0, 0, 0, 0, 33093, NULL, NULL },
};

static const EventCharaKeyframe sEvent087Track8[11] = {
    { 477, 853, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 475, 873, 6656, 22272, 0, 0, 16706, NULL, NULL },
    { 472, 999, 0, 0, 0, 0, 33093, NULL, NULL },
    { 477, 858, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 476, 878, -7168, 41472, 0, 0, 16706, NULL, NULL },
    { 476, 845, 0, 0, 0, 45, 324, NULL, NULL },
    { 473, 999, 0, 0, 0, 0, 33093, NULL, NULL },
    { 477, 803, 256000, 256000, 0, 0, 8194, NULL, NULL },
    { 476, 804, -6400, 50176, 0, 0, 16706, NULL, NULL },
    { 476, 860, 0, 0, 0, 45, 324, NULL, NULL },
    { 473, 999, 0, 0, 0, 0, 33093, NULL, NULL },
};

static const EventCharaTrack sEvent087Tracks[9] = {
    { sEvent087Track0, 0 },
    { sEvent087Track1, 13 },
    { sEvent087Track2, 1 },
    { sEvent087Track3, 2 },
    { sEvent087Track4, 40 },
    { sEvent087Track5, 40 },
    { sEvent087Track6, 40 },
    { sEvent087Track7, 40 },
    { sEvent087Track8, 40 },
};

const EventSequenceDef gEvent087 = {
    9,
    sEvent087Tracks,
    sEvent087Camera,
    sEvent087Script,
    sEvent087SoundCues,
    sEvent087BgEffects,
    950,
    0,
    1,
    0,
    0,
    0,
    122,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
