#ifdef VERSION_US
#include "event_103_text.inc"
#endif

static const MessageScriptEntry sEvent103Script[30] = {
    { PORTRAIT_SORA, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text00), 0, 140 },
    { PORTRAIT_ARIEL, 4, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text01), 0, 300 },
    { PORTRAIT_ARIEL, 5, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text02), 0, 302 },
    { PORTRAIT_DONALD, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text03), 0, 320 },
    { PORTRAIT_GOOFY, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text04), 0, 340 },
    { PORTRAIT_URSULA, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text05), MSG_SCRIPT_FLAG_SILHOUETTE, 380 },
    { PORTRAIT_URSULA, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text06), 0, 560 },
    { PORTRAIT_URSULA, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text07), 0, 580 },
    { PORTRAIT_URSULA, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text08), 0, 582 },
    { PORTRAIT_ARIEL, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text09), 0, 600 },
    { PORTRAIT_URSULA, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text10), 0, 640 },
    { PORTRAIT_URSULA, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text11), 0, 642 },
    { PORTRAIT_ARIEL, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text12), 0, 700 },
    { PORTRAIT_ARIEL, 5, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text13), 0, 740 },
    { PORTRAIT_URSULA, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text14), 0, 910 },
    { PORTRAIT_URSULA, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text15), 0, 1020 },
    { PORTRAIT_URSULA, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text16), 0, 1022 },
    { PORTRAIT_ARIEL, 5, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text17), 0, 1320 },
    { PORTRAIT_SORA, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text18), 0, 1340 },
    { PORTRAIT_ARIEL, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text19), 0, 1510 },
    { PORTRAIT_SORA, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text20), 0, 1530 },
    { PORTRAIT_DONALD, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text21), 0, 1550 },
    { PORTRAIT_DONALD, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text22), 0, 1552 },
    { PORTRAIT_ARIEL, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text23), 0, 1570 },
    { PORTRAIT_ARIEL, 4, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text24), 0, 1572 },
    { PORTRAIT_ARIEL, 4, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text25), 0, 1574 },
    { PORTRAIT_SORA, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text26), 0, 1600 },
    { PORTRAIT_SORA, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text27), 0, 1700 },
    { PORTRAIT_ARIEL, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text28), 0, 1720 },
    { PORTRAIT_SORA, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent103Text29), MSG_SCRIPT_FLAG_END, 1740 },
};

#ifdef VERSION_JP
#include "event_103_text.inc"
#endif

static const EventCameraKeyframe sEvent103Camera[3] = {
    { -65376, 39168, 61952, 0, EVENT_CHARA_NONE, 0, 0, NULL },
    { -64186, 83200, 45824, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 80, NULL },
    { -55537, 69632, 47616, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_APPROACH, 80, NULL },
};

static const EvSoundCue sEvent103SoundCues[7] = {
    { SONG_NONE, 0, 0, 0 },
    { SONG_BGM_EVENT_SILENCE, 300, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT_SILENCE, 370, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_EVENT_UNREST, 381, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT_UNREST, 1100, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_UNDERTHESEA, 1700, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_UNDERTHESEA, 1845, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent103Track0[21] = {
    { 316, 381, 73984, 45056, 0, 0, 2, NULL, NULL },
    { 316, 410, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 316, 420, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 430, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 599, 0, 0, 0, 0, 69, NULL, NULL },
    { 324, 601, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 710, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 720, 0, 0, 0, 0, 5, NULL, NULL },
    { 316, 1150, 0, 0, 0, 0, 5, NULL, NULL },
    { 314, 1160, 0, 0, 0, 0, 5, NULL, NULL },
    { 314, 1170, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 1310, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 314, 1350, 0, 0, 0, 0, 69, NULL, NULL },
    { 314, 1360, 0, 0, 0, 0, 5, NULL, NULL },
    { 322, 1509, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 323, 1511, 0, 0, 0, 0, 5, NULL, NULL },
    { 314, 1610, 0, 0, 0, 0, 5, NULL, NULL },
    { 314, 1690, 0, 0, 0, 0, 0, NULL, CreateQuestionTask },
    { 314, 1719, 0, 0, 0, 0, 5, NULL, NULL },
    { 322, 1721, 0, 0, 0, 0, 5, NULL, NULL },
    { 314, 9999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent103Track1[7] = {
    { 4, 1, 20992, 71680, 0, 0, 66, NULL, NULL },
    { 9, 60, 0, 0, 0, 45, 68, NULL, NULL },
    { 4, 1350, 0, 0, 0, 0, 69, NULL, NULL },
    { 9, 1490, 0, 0, 0, 45, 68, NULL, NULL },
    { 4, 1529, 0, 0, 0, 0, 69, NULL, NULL },
    { 36, 1531, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent103Track2[8] = {
    { 114, 1, 24832, 76288, 0, 0, 66, NULL, NULL },
    { 119, 60, 0, 0, 0, 45, 68, NULL, NULL },
    { 114, 1350, 0, 0, 0, 0, 69, NULL, NULL },
    { 119, 1490, 0, 0, 0, 45, 68, NULL, NULL },
    { 114, 1549, 0, 0, 0, 0, 69, NULL, NULL },
    { 127, 1553, 0, 0, 0, 0, 69, NULL, NULL },
    { 129, 1560, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent103Track3[5] = {
    { 146, 1, 14592, 71680, 0, 0, 66, NULL, NULL },
    { 151, 60, 0, 0, 0, 45, 68, NULL, NULL },
    { 146, 1350, 0, 0, 0, 0, 69, NULL, NULL },
    { 151, 1490, 0, 0, 0, 45, 68, NULL, NULL },
    { 146, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent103Track4[14] = {
    { 354, 390, 129792, 74496, 0, 0, 2, NULL, NULL },
    { 358, 467, 0, 0, 0, 211, 4, NULL, NULL },
    { 354, 478, 0, 0, 0, 211, 4, NULL, NULL },
    { 358, 540, 0, 0, 0, 211, 4, NULL, NULL },
    { 358, 750, 0, 0, 0, 0, 5, NULL, NULL },
    { 358, 900, 0, 0, 0, 0, 0, NULL, CreateBalloonTask },
    { 358, 920, 0, 0, 0, 0, 5, NULL, NULL },
    { 354, 930, 0, 0, 0, 0, 69, NULL, NULL },
    { 353, 950, 0, 0, 0, 0, 69, NULL, NULL },
    { 357, 1010, 0, 0, 0, 83, 68, NULL, NULL },
    { 357, 1040, 0, 0, 0, 0, 69, NULL, NULL },
    { 353, 1041, 0, 0, 0, 0, 69, NULL, NULL },
    { 357, 1410, 0, 0, 0, 83, 68, NULL, NULL },
    { 353, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaTrack sEvent103Tracks[5] = {
    { sEvent103Track0, EVENT_CHARA_ARIEL },
    { sEvent103Track1, EVENT_CHARA_SORA },
    { sEvent103Track2, EVENT_CHARA_DONALD },
    { sEvent103Track3, EVENT_CHARA_GOOFY },
    { sEvent103Track4, EVENT_CHARA_URSULA },
};

const EventSequenceDef gEvent103 = {
    ARRAY_COUNT(sEvent103Tracks),
    sEvent103Tracks,
    sEvent103Camera,
    sEvent103Script,
    sEvent103SoundCues,
    NULL,
    1850,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    0,
    EVENT_NONE,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    0,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
