#ifdef VERSION_US
#include "event_108_text.inc"
static const MessageScriptEntry sEvent108Script[16] = {
    { PORTRAIT_DONALD, 4, 3, 1, gEvent108Text00, 0, 240 },
    { PORTRAIT_ALADDIN, 2, 3, 1, gEvent108Text01, 0, 270 },
    { PORTRAIT_ALADDIN, 2, 3, 1, gEvent108Text02, 0, 350 },
    { PORTRAIT_ALADDIN, 2, 4, 1, gEvent108Text03, 0, 352 },
    { PORTRAIT_GENIE, 3, 1, 0, gEvent108Text04, 0, 525 },
    { PORTRAIT_GENIE, 3, 4, 0, gEvent108Text05, 0, 527 },
    { PORTRAIT_GOOFY, 2, 3, 1, gEvent108Text06, 0, 750 },
    { PORTRAIT_DONALD, 3, 2, 1, gEvent108Text07, 0, 770 },
    { PORTRAIT_ALADDIN, 0, 1, 1, gEvent108Text08, 0, 800 },
    { PORTRAIT_GENIE, 0, 1, 0, gEvent108Text09, 0, 840 },
    { PORTRAIT_GENIE, 3, 4, 0, gEvent108Text10, 0, 842 },
    { PORTRAIT_SORA, 0, 1, 1, gEvent108Text11, 0, 920 },
    { PORTRAIT_ALADDIN, 0, 3, 1, gEvent108Text12, 0, 940 },
    { PORTRAIT_GOOFY, 0, 3, 1, gEvent108Text13, 0, 970 },
    { PORTRAIT_SORA, 4, 1, 1, gEvent108Text14, 0, 1000 },
    { PORTRAIT_ALADDIN, 1, 3, 1, gEvent108Text15, MSG_SCRIPT_FLAG_END, 1020 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent108Script[17] = {
    { PORTRAIT_DONALD, 4, 3, 3, gEvent108Text00, 0, 240 },
    { PORTRAIT_ALADDIN, 2, 3, 3, gEvent108Text01, 0, 270 },
    { PORTRAIT_ALADDIN, 2, 3, 3, gEvent108Text02, 0, 350 },
    { PORTRAIT_ALADDIN, 2, 4, 3, gEvent108Text03, 0, 352 },
    { PORTRAIT_GENIE, 3, 1, 1, gEvent108Text04, 0, 525 },
    { PORTRAIT_GENIE, 3, 4, 1, gEvent108Text05, 0, 527 },
    { PORTRAIT_GOOFY, 2, 3, 3, gEvent108Text06, 0, 750 },
    { PORTRAIT_DONALD, 3, 2, 3, gEvent108Text07, 0, 770 },
    { PORTRAIT_ALADDIN, 0, 1, 3, gEvent108Text08, 0, 800 },
    { PORTRAIT_GENIE, 0, 1, 1, gEvent108Text09, 0, 840 },
    { PORTRAIT_GENIE, 3, 4, 1, gEvent108Text10, 0, 842 },
    { PORTRAIT_GENIE, 3, 4, 1, gEvent108Text11, 0, 844 },
    { PORTRAIT_SORA, 0, 1, 3, gEvent108Text12, 0, 920 },
    { PORTRAIT_ALADDIN, 0, 3, 3, gEvent108Text13, 0, 940 },
    { PORTRAIT_GOOFY, 0, 3, 3, gEvent108Text14, 0, 970 },
    { PORTRAIT_SORA, 4, 1, 3, gEvent108Text15, 0, 1000 },
    { PORTRAIT_ALADDIN, 1, 3, 3, gEvent108Text16, MSG_SCRIPT_FLAG_END, 1020 },
};

#include "event_108_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent108Script[16] = {
    { PORTRAIT_DONALD, 4, 3, 1, &gEvent108Text00ByLanguage, 0, 240 },
    { PORTRAIT_ALADDIN, 2, 3, 1, &gEvent108Text01ByLanguage, 0, 270 },
    { PORTRAIT_ALADDIN, 2, 3, 1, &gEvent108Text02ByLanguage, 0, 350 },
    { PORTRAIT_ALADDIN, 2, 4, 1, &gEvent108Text03ByLanguage, 0, 352 },
    { PORTRAIT_GENIE, 3, 1, 0, &gEvent108Text04ByLanguage, 0, 525 },
    { PORTRAIT_GENIE, 3, 4, 0, &gEvent108Text05ByLanguage, 0, 527 },
    { PORTRAIT_GOOFY, 2, 3, 1, &gEvent108Text06ByLanguage, 0, 750 },
    { PORTRAIT_DONALD, 3, 2, 1, &gEvent108Text07ByLanguage, 0, 770 },
    { PORTRAIT_ALADDIN, 0, 1, 1, &gEvent108Text08ByLanguage, 0, 800 },
    { PORTRAIT_GENIE, 0, 1, 0, &gEvent108Text09ByLanguage, 0, 840 },
    { PORTRAIT_GENIE, 3, 4, 0, &gEvent108Text10ByLanguage, 0, 842 },
    { PORTRAIT_SORA, 0, 1, 1, &gEvent108Text11ByLanguage, 0, 920 },
    { PORTRAIT_ALADDIN, 0, 3, 1, &gEvent108Text12ByLanguage, 0, 940 },
    { PORTRAIT_GOOFY, 0, 3, 1, &gEvent108Text13ByLanguage, 0, 970 },
    { PORTRAIT_SORA, 4, 1, 1, &gEvent108Text14ByLanguage, 0, 1000 },
    { PORTRAIT_ALADDIN, 1, 3, 1, &gEvent108Text15ByLanguage, MSG_SCRIPT_FLAG_END, 1020 },
};
#endif

static const EventCameraKeyframe sEvent108Camera[8] = {
    { -65181, 93184, 56064, 0, EVENT_CHARA_NONE, 0, 0, NULL },
    { -65081, 96000, 40960, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 20, NULL },
    { -64996, 96000, 20736, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 30, NULL },
    { -64796, 91136, 46080, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 40, NULL },
    { -64726, 83712, 53504, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 50, NULL },
    { -64686, 88832, 53504, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 40, NULL },
    { -64676, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, NULL },
    { -55537, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EvSoundCue sEvent108SoundCues[5] = {
    { SONG_BGM_ALADDIN_BATTLE, 0, 0, 0 },
    { SONG_BGM_ALADDIN_BATTLE, 410, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_VO_GE_EVENT00, 480, 0, 0 },
    { SONG_BGM_ALADDIN_FIELD, 750, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_ALADDIN_FIELD, 1115, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventBgEffectEntry sEvent108BgEffects[3] = {
    { 381, 0, 0, 0, 0 },
    { 500, 0, 0, 0, 0x4 },
    { 701, 0, 0, 0, 0x8008 },
};

static const EventCharaKeyframe sEvent108Track9[3] = {
    { 743, 410, 0, 0, 0, 0, 8194, NULL, NULL },
    { 743, 460, 94720, 49664, -7680, 0, 16658, NULL, NULL },
    { 743, 470, 0, 0, 0, 0, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track10[3] = {
    { 744, 865, 0, 0, 0, 0, 8194, NULL, NULL },
    { 744, 930, 89088, 60160, -7680, 0, 16658, NULL, NULL },
    { 744, 9999, 0, 0, 0, 0, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track0[16] = {
    { 664, 450, 0, 0, 0, 0, 8258, NULL, NULL },
    { 668, 460, 94720, 47104, -7680, 0, 16706, NULL, NULL },
    { 668, 490, 94720, 47104, -23040, 664, 4419, NULL, NULL },
    { 668, 523, 0, 0, 0, 0, 262469, NULL, NULL },
    { 664, 530, 0, 0, 0, 0, 262405, NULL, NULL },
    { 666, 560, 71168, 58112, -2560, 664, 262147, NULL, NULL },
    { 664, 570, 0, 0, 0, 0, 262149, NULL, NULL },
    { 664, 580, 0, 0, 0, 0, 262213, NULL, NULL },
    { 670, 750, 0, 0, 0, 0, 69, NULL, NULL },
    { 664, 810, 0, 0, 0, 0, 262213, NULL, NULL },
    { 664, 820, 82944, 58368, -2560, 664, 67, NULL, NULL },
    { 664, 830, 91648, 60160, -2560, 664, 67, NULL, NULL },
    { 664, 840, 0, 0, 0, 0, 262149, NULL, NULL },
    { 669, 850, 91648, 60160, 0, 0, 262146, NULL, NULL },
    { 664, 851, 0, 0, 0, 0, 65602, NULL, NULL },
    { 664, 9999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track1[20] = {
    { 278, 160, 88576, 58112, 0, 0, 66, NULL, NULL },
    { 278, 260, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 278, 272, 0, 0, 0, 0, 69, NULL, NULL },
    { 282, 280, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 290, 0, 0, 0, 0, 69, NULL, NULL },
    { 276, 500, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 540, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 580, 0, 0, 0, 0, 5, NULL, NULL },
    { 282, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 286, 752, 0, 0, 0, 0, 69, NULL, NULL },
    { 282, 780, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 790, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 799, 0, 0, 0, 0, 5, NULL, NULL },
    { 270, 801, 0, 0, 0, 0, 5, NULL, NULL },
    { 270, 930, 0, 0, 0, 0, 5, NULL, NULL },
    { 270, 950, 0, 0, 0, 0, 69, NULL, NULL },
    { 270, 1010, 0, 0, 0, 0, 5, NULL, NULL },
    { 270, 1050, 0, 0, 0, 0, 69, NULL, NULL },
    { 282, 1060, 0, 0, 0, 0, 69, NULL, NULL },
    { 283, 9999, 0, 0, 0, 45, 32836, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track3[21] = {
    { 21, 160, 95744, 64768, 0, 0, 66, NULL, NULL },
    { 21, 220, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 21, 280, 0, 0, 0, 0, 69, NULL, NULL },
    { 22, 290, 0, 0, 0, 0, 69, NULL, NULL },
    { 0, 550, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 585, 0, 0, 0, 0, 5, NULL, NULL },
    { 0, 590, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 27, 760, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 780, 0, 0, 0, 0, 69, NULL, NULL },
    { 0, 785, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 850, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 900, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 4, 919, 0, 0, 0, 0, 5, NULL, NULL },
    { 34, 921, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 980, 0, 0, 0, 0, 5, NULL, NULL },
    { 16, 995, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 1050, 0, 0, 0, 0, 5, NULL, NULL },
    { 0, 1055, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 1060, 0, 0, 0, 0, 69, NULL, NULL },
    { 9, 9999, 0, 0, 0, 45, 32836, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track2[18] = {
    { 158, 160, 77824, 64256, 0, 0, 66, NULL, NULL },
    { 158, 220, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 158, 285, 0, 0, 0, 0, 69, NULL, NULL },
    { 159, 295, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 550, 0, 0, 0, 0, 69, NULL, NULL },
    { 142, 555, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 590, 0, 0, 0, 0, 5, NULL, NULL },
    { 142, 595, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 161, 760, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 850, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 900, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 146, 950, 0, 0, 0, 0, 69, NULL, NULL },
    { 145, 969, 0, 0, 0, 0, 69, NULL, NULL },
    { 167, 971, 0, 0, 0, 0, 69, NULL, NULL },
    { 145, 1065, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 1070, 0, 0, 0, 0, 69, NULL, NULL },
    { 151, 9999, 0, 0, 0, 45, 32836, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track4[18] = {
    { 123, 160, 86272, 68096, 0, 0, 66, NULL, NULL },
    { 123, 220, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 123, 290, 0, 0, 0, 0, 69, NULL, NULL },
    { 124, 300, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 540, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 550, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 585, 0, 0, 0, 0, 5, NULL, NULL },
    { 110, 590, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 133, 760, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 769, 0, 0, 0, 0, 69, NULL, NULL },
    { 126, 771, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 780, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 850, 0, 0, 0, 0, 5, NULL, NULL },
    { 110, 900, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 110, 1060, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 1065, 0, 0, 0, 0, 69, NULL, NULL },
    { 119, 9999, 0, 0, 0, 45, 32836, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track5[6] = {
    { 472, 150, 0, 0, 0, 0, 8450, NULL, NULL },
    { 475, 170, 96000, 45056, 0, 0, 16642, NULL, NULL },
    { 472, 670, 0, 0, 0, 0, 261, NULL, NULL },
    { 478, 690, 0, 0, 0, 0, 261, NULL, NULL },
    { 472, 691, 0, 0, 0, 0, 258, NULL, NULL },
    { 472, 9999, 0, 0, 0, 0, 98565, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track6[6] = {
    { 472, 160, 0, 0, 0, 0, 8450, NULL, NULL },
    { 475, 180, 105728, 51456, 0, 0, 16642, NULL, NULL },
    { 472, 690, 0, 0, 0, 0, 261, NULL, NULL },
    { 478, 710, 0, 0, 0, 0, 261, NULL, NULL },
    { 472, 711, 0, 0, 0, 0, 258, NULL, NULL },
    { 472, 9999, 0, 0, 0, 0, 98565, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track7[6] = {
    { 472, 170, 0, 0, 0, 0, 8450, NULL, NULL },
    { 475, 190, 118272, 48384, 0, 0, 16642, NULL, NULL },
    { 472, 710, 0, 0, 0, 0, 261, NULL, NULL },
    { 478, 730, 0, 0, 0, 0, 261, NULL, NULL },
    { 472, 731, 0, 0, 0, 0, 258, NULL, NULL },
    { 472, 9999, 0, 0, 0, 0, 98565, NULL, NULL },
};

static const EventCharaKeyframe sEvent108Track8[6] = {
    { 472, 180, 0, 0, 0, 0, 8450, NULL, NULL },
    { 475, 200, 108288, 43008, 0, 0, 16642, NULL, NULL },
    { 472, 730, 0, 0, 0, 0, 261, NULL, NULL },
    { 478, 750, 0, 0, 0, 0, 261, NULL, NULL },
    { 472, 751, 0, 0, 0, 0, 258, NULL, NULL },
    { 472, 9999, 0, 0, 0, 0, 98565, NULL, NULL },
};

static const EventCharaTrack sEvent108Tracks[11] = {
    { sEvent108Track0, EVENT_CHARA_GENIE },
    { sEvent108Track1, EVENT_CHARA_ALADDIN },
    { sEvent108Track2, EVENT_CHARA_GOOFY },
    { sEvent108Track3, EVENT_CHARA_SORA },
    { sEvent108Track4, EVENT_CHARA_DONALD },
    { sEvent108Track5, EVENT_CHARA_SHADOW },
    { sEvent108Track6, EVENT_CHARA_SHADOW },
    { sEvent108Track7, EVENT_CHARA_SHADOW },
    { sEvent108Track8, EVENT_CHARA_SHADOW },
    { sEvent108Track9, EVENT_CHARA_SMOKE_CLOUD },
    { sEvent108Track10, EVENT_CHARA_SMOKE_CLOUD },
};

const EventSequenceDef gEvent108 = {
    11,
    sEvent108Tracks,
    sEvent108Camera,
    sEvent108Script,
    sEvent108SoundCues,
    sEvent108BgEffects,
    1120,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    0,
    EVENT_NONE,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    1,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
