#ifdef VERSION_US
#include "event_114_text.inc"
static const MessageScriptEntry sEvent114Script[31] = {
    { 1, 3, 1, 1, { 0, 0, 0 }, gEvent114Text00, 0, 90 },
    { 2, 0, 1, 1, { 0, 0, 0 }, gEvent114Text01, 0, 120 },
    { 21, 0, 3, 1, { 0, 0, 0 }, gEvent114Text02, 0, 220 },
    { 21, 4, 4, 1, { 0, 0, 0 }, gEvent114Text03, 0, 222 },
    { 21, 3, 4, 1, { 0, 0, 0 }, gEvent114Text04, 0, 224 },
    { 15, 3, 3, 1, { 0, 0, 0 }, gEvent114Text05, 0, 430 },
    { 15, 0, 1, 1, { 0, 0, 0 }, gEvent114Text06, 0, 500 },
    { 21, 2, 3, 1, { 0, 0, 0 }, gEvent114Text07, 0, 850 },
    { 15, 1, 1, 1, { 0, 0, 0 }, gEvent114Text08, 0, 880 },
    { 21, 0, 3, 1, { 0, 0, 0 }, gEvent114Text09, 0, 910 },
    { 21, 2, 4, 1, { 0, 0, 0 }, gEvent114Text10, 0, 915 },
    { 15, 0, 1, 1, { 0, 0, 0 }, gEvent114Text11, 0, 970 },
    { 15, 3, 4, 1, { 0, 0, 0 }, gEvent114Text12, 0, 972 },
    { 15, 0, 1, 1, { 0, 0, 0 }, gEvent114Text13, 0, 1050 },
    { 15, 1, 4, 1, { 0, 0, 0 }, gEvent114Text14, 0, 1052 },
    { 0, 4, 0, 1, { 0, 0, 0 }, gEvent114Text15, 0, 1080 },
    { 15, 1, 3, 1, { 0, 0, 0 }, gEvent114Text16, 0, 1140 },
    { 0, 3, 0, 1, { 0, 0, 0 }, gEvent114Text17, 0, 1160 },
    { 15, 0, 3, 1, { 0, 0, 0 }, gEvent114Text18, 0, 1190 },
    { 15, 1, 4, 1, { 0, 0, 0 }, gEvent114Text19, 0, 1192 },
    { 0, 5, 0, 1, { 0, 0, 0 }, gEvent114Text20, 0, 1240 },
    { 15, 1, 1, 1, { 0, 0, 0 }, gEvent114Text21, 0, 1450 },
    { 21, 3, 3, 1, { 0, 0, 0 }, gEvent114Text22, 0, 1470 },
    { 21, 3, 3, 1, { 0, 0, 0 }, gEvent114Text23, 0, 1740 },
    { 21, 3, 4, 1, { 0, 0, 0 }, gEvent114Text24, 0, 1744 },
    { 15, 1, 1, 1, { 0, 0, 0 }, gEvent114Text25, 0, 1810 },
    { 0, 3, 0, 1, { 0, 0, 0 }, gEvent114Text26, 0, 1860 },
    { 21, 3, 3, 1, { 0, 0, 0 }, gEvent114Text27, 0, 1890 },
    { 21, 0, 4, 1, { 0, 0, 0 }, gEvent114Text28, 0, 1892 },
    { 0, 4, 0, 1, { 0, 0, 0 }, gEvent114Text29, 0, 1922 },
    { 15, 1, 3, 1, { 0, 0, 0 }, gEvent114Text30, MSG_SCRIPT_FLAG_END, 1960 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent114Script[31] = {
    { 1, 3, 1, 3, { 0, 0, 0 }, gEvent114Text00, 0, 90 },
    { 2, 0, 1, 3, { 0, 0, 0 }, gEvent114Text01, 0, 120 },
    { 21, 0, 3, 3, { 0, 0, 0 }, gEvent114Text02, 0, 220 },
    { 21, 4, 4, 3, { 0, 0, 0 }, gEvent114Text03, 0, 222 },
    { 21, 3, 4, 3, { 0, 0, 0 }, gEvent114Text04, 0, 224 },
    { 15, 3, 3, 3, { 0, 0, 0 }, gEvent114Text05, 0, 430 },
    { 15, 0, 1, 3, { 0, 0, 0 }, gEvent114Text06, 0, 500 },
    { 21, 2, 3, 3, { 0, 0, 0 }, gEvent114Text07, 0, 850 },
    { 15, 1, 1, 3, { 0, 0, 0 }, gEvent114Text08, 0, 880 },
    { 21, 0, 3, 3, { 0, 0, 0 }, gEvent114Text09, 0, 910 },
    { 21, 2, 4, 3, { 0, 0, 0 }, gEvent114Text10, 0, 915 },
    { 15, 0, 1, 3, { 0, 0, 0 }, gEvent114Text11, 0, 970 },
    { 15, 3, 4, 3, { 0, 0, 0 }, gEvent114Text12, 0, 972 },
    { 15, 0, 1, 3, { 0, 0, 0 }, gEvent114Text13, 0, 1050 },
    { 15, 1, 4, 3, { 0, 0, 0 }, gEvent114Text14, 0, 1052 },
    { 0, 4, 0, 3, { 0, 0, 0 }, gEvent114Text15, 0, 1080 },
    { 15, 1, 3, 3, { 0, 0, 0 }, gEvent114Text16, 0, 1140 },
    { 0, 3, 0, 3, { 0, 0, 0 }, gEvent076Text19, 0, 1160 },
    { 15, 0, 3, 3, { 0, 0, 0 }, gEvent114Text18, 0, 1190 },
    { 15, 1, 4, 3, { 0, 0, 0 }, gEvent114Text19, 0, 1192 },
    { 0, 5, 0, 3, { 0, 0, 0 }, gEvent114Text20, 0, 1240 },
    { 15, 1, 1, 3, { 0, 0, 0 }, gEvent114Text21, 0, 1450 },
    { 21, 3, 3, 3, { 0, 0, 0 }, gEvent114Text22, 0, 1470 },
    { 21, 3, 3, 3, { 0, 0, 0 }, gEvent114Text23, 0, 1740 },
    { 21, 3, 4, 3, { 0, 0, 0 }, gEvent114Text24, 0, 1744 },
    { 15, 1, 1, 3, { 0, 0, 0 }, gEvent114Text25, 0, 1810 },
    { 0, 3, 0, 3, { 0, 0, 0 }, gEvent114Text26, 0, 1860 },
    { 21, 3, 3, 3, { 0, 0, 0 }, gEvent114Text27, 0, 1890 },
    { 21, 0, 4, 3, { 0, 0, 0 }, gEvent114Text28, 0, 1892 },
    { 0, 4, 0, 3, { 0, 0, 0 }, gEvent114Text29, 0, 1922 },
    { 15, 1, 3, 3, { 0, 0, 0 }, gEvent114Text30, MSG_SCRIPT_FLAG_END, 1960 },
};

#include "event_114_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent114Script[31] = {
    { 1, 3, 1, 1, { 0, 0, 0 }, &gEvent114Text00, 0, 90 },
    { 2, 0, 1, 1, { 0, 0, 0 }, &gEvent114Text01, 0, 120 },
    { 21, 0, 3, 1, { 0, 0, 0 }, &gEvent114Text02, 0, 220 },
    { 21, 4, 4, 1, { 0, 0, 0 }, &gEvent114Text03, 0, 222 },
    { 21, 3, 4, 1, { 0, 0, 0 }, &gEvent114Text04, 0, 224 },
    { 15, 3, 3, 1, { 0, 0, 0 }, &gEvent114Text05, 0, 430 },
    { 15, 0, 1, 1, { 0, 0, 0 }, &gEvent114Text06, 0, 500 },
    { 21, 2, 3, 1, { 0, 0, 0 }, &gEvent114Text07, 0, 850 },
    { 15, 1, 1, 1, { 0, 0, 0 }, &gEvent114Text08, 0, 880 },
    { 21, 0, 3, 1, { 0, 0, 0 }, &gEvent114Text09, 0, 910 },
    { 21, 2, 4, 1, { 0, 0, 0 }, &gEvent114Text10, 0, 915 },
    { 15, 0, 1, 1, { 0, 0, 0 }, &gEvent114Text11, 0, 970 },
    { 15, 3, 4, 1, { 0, 0, 0 }, &gEvent114Text12, 0, 972 },
    { 15, 0, 1, 1, { 0, 0, 0 }, &gEvent114Text13, 0, 1050 },
    { 15, 1, 4, 1, { 0, 0, 0 }, &gEvent114Text14, 0, 1052 },
    { 0, 4, 0, 1, { 0, 0, 0 }, &gEvent114Text15, 0, 1080 },
    { 15, 1, 3, 1, { 0, 0, 0 }, &gEvent114Text16, 0, 1140 },
    { 0, 3, 0, 1, { 0, 0, 0 }, &gEvent114Text17, 0, 1160 },
    { 15, 0, 3, 1, { 0, 0, 0 }, &gEvent114Text18, 0, 1190 },
    { 15, 1, 4, 1, { 0, 0, 0 }, &gEvent114Text19, 0, 1192 },
    { 0, 5, 0, 1, { 0, 0, 0 }, &gEvent114Text20, 0, 1240 },
    { 15, 1, 1, 1, { 0, 0, 0 }, &gEvent114Text21, 0, 1450 },
    { 21, 3, 3, 1, { 0, 0, 0 }, &gEvent114Text22, 0, 1470 },
    { 21, 3, 3, 1, { 0, 0, 0 }, &gEvent114Text23, 0, 1740 },
    { 21, 3, 4, 1, { 0, 0, 0 }, &gEvent114Text24, 0, 1744 },
    { 15, 1, 1, 1, { 0, 0, 0 }, &gEvent114Text25, 0, 1810 },
    { 0, 3, 0, 1, { 0, 0, 0 }, &gEvent114Text26, 0, 1860 },
    { 21, 3, 3, 1, { 0, 0, 0 }, &gEvent114Text27, 0, 1890 },
    { 21, 0, 4, 1, { 0, 0, 0 }, &gEvent114Text28, 0, 1892 },
    { 0, 4, 0, 1, { 0, 0, 0 }, &gEvent114Text29, 0, 1922 },
    { 15, 1, 3, 1, { 0, 0, 0 }, &gEvent114Text30, MSG_SCRIPT_FLAG_END, 1960 },
};
#endif

static const EventCameraKeyframe sEvent114Camera[9] = {
    { -64936, 87808, 38912, 0, 255, { 0, 0, 0 }, 0, 0, { 0, 0 }, NULL },
    { -64926, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -64916, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -64876, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 20, { 0, 0 }, NULL },
    { -64811, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_MODE_KEEP, 60, { 0, 0 }, NULL },
    { -64751, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 60, { 0, 0 }, NULL },
    { -64536, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -60536, 85760, 41472, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 40, { 0, 0 }, NULL },
    { -55537, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
};

static const EvSoundCue sEvent114SoundCues[4] = {
    { 65535, 0, 0, 0 },
    { SONG_EV_WHITEOUT, 660, 0, 0 },
    { SONG_BGM_EVENT4, 855, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT4, 2095, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent114Track0[14] = {
    { 4, 510, { 0, 0 }, 95488, 54272, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 4, 560, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 4, 1075, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 36, 1162, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 4, 1230, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 16, 1480, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 4, 1530, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 27, 1580, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 27, 1590, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 4, 1719, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 75, 1840, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 76, 2055, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 3, 2065, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 2, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track1[11] = {
    { 112, 85, { 0, 0 }, 102400, 47360, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 125, 92, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 112, 510, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 112, 560, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 112, 770, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 113, 775, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 114, 800, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 131, 830, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 114, 925, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 113, 935, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 112, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track2[7] = {
    { 144, 115, { 0, 0 }, 97280, 41216, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 164, 122, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 144, 510, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 144, 560, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 144, 805, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 145, 930, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 144, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track3[24] = {
    { 282, 170, { 0, 0 }, 84736, 50176, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 287, 270, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 287, 400, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateBalloonTask },
    { 287, 440, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 282, 460, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 282, 940, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 287, 985, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 282, 995, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 271, 1030, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 4, NULL, NULL },
    { 270, 1100, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1340, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 270, 1390, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 270, 1410, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 282, 1420, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 282, 1490, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1500, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1760, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 270, 1770, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 282, 1910, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1920, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 270, 1980, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 270, 2000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 272, 9999, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 32804, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track4[8] = {
    { 664, 510, { 0, 0 }, 75008, 44032, -2560, 0, { 0, 0 }, 262210, NULL, NULL },
    { 664, 570, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 262213, NULL, NULL },
    { 673, 721, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 674, 912, { 0, 0 }, 75008, 44032, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 671, 1480, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 675, 1742, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 671, 2050, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 671, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track5[3] = {
    { 743, 660, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 743, 710, { 0, 0 }, 74752, 42496, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 743, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track6[3] = {
    { 744, 785, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 744, 835, { 0, 0 }, 75264, 33792, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 744, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track7[3] = {
    { 744, 1520, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 744, 1570, { 0, 0 }, 92416, 38656, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 744, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track8[5] = {
    { 593, 1520, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 595, 1670, { 0, 0 }, 92416, 38656, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 595, 1719, { 0, 0 }, 92416, 46592, 0, 593, { 0, 0 }, 275, NULL, NULL },
    { 602, 1840, { 0, 0 }, 95488, 54272, 0, 0, { 0, 0 }, 274, NULL, NULL },
    { 593, 9999, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent114Track9[3] = {
    { 928, 510, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8258, NULL, NULL },
    { 927, 560, { 0, 0 }, 71680, 24576, 0, 0, { 0, 0 }, 16722, NULL, NULL },
    { 928, 2000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98370, NULL, NULL },
};

static const EventCharaTrack sEvent114Tracks[10] = {
    { sEvent114Track0, 0, { 0, 0, 0 } },
    { sEvent114Track1, 1, { 0, 0, 0 } },
    { sEvent114Track2, 2, { 0, 0, 0 } },
    { sEvent114Track3, 12, { 0, 0, 0 } },
    { sEvent114Track4, 59, { 0, 0, 0 } },
    { sEvent114Track5, 68, { 0, 0, 0 } },
    { sEvent114Track6, 68, { 0, 0, 0 } },
    { sEvent114Track7, 68, { 0, 0, 0 } },
    { sEvent114Track8, 51, { 0, 0, 0 } },
    { sEvent114Track9, 93, { 0, 0, 0 } },
};

const EventSequenceDef gEvent114 = {
    10,
    { 0, 0, 0 },
    sEvent114Tracks,
    sEvent114Camera,
    sEvent114Script,
    sEvent114SoundCues,
    NULL,
    2100,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
