#ifdef VERSION_US
#include "event_119_text.inc"
#endif

static const MessageScriptEntry sEvent119Script[30] = {
    { PORTRAIT_SORA, 4, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text00), 0, 100 },
    { PORTRAIT_PETER_PAN, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text01), 0, 120 },
    { PORTRAIT_PETER_PAN, 4, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text02), 0, 122 },
    { PORTRAIT_PETER_PAN, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text03), 0, 140 },
    { PORTRAIT_WENDY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text04), 0, 160 },
    { PORTRAIT_PETER_PAN, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text05), 0, 310 },
    { PORTRAIT_PETER_PAN, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text06), 0, 312 },
    { PORTRAIT_WENDY, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text07), 0, 460 },
    { PORTRAIT_PETER_PAN, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text08), 0, 480 },
    { PORTRAIT_PETER_PAN, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text09), 0, 482 },
    { PORTRAIT_PETER_PAN, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text10), 0, 484 },
    { PORTRAIT_SORA, 5, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text11), 0, 500 },
    { PORTRAIT_SORA, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text12), 0, 600 },
    { PORTRAIT_SORA, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text13), 0, 602 },
    { PORTRAIT_SORA, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text14), 0, 604 },
    { PORTRAIT_SORA, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text15), 0, 606 },
    { PORTRAIT_WENDY, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text16), 0, 630 },
    { PORTRAIT_PETER_PAN, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text17), 0, 650 },
    { PORTRAIT_PETER_PAN, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text18), 0, 652 },
    { PORTRAIT_PETER_PAN, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text19), 0, 654 },
    { PORTRAIT_PETER_PAN, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text20), 0, 810 },
    { PORTRAIT_WENDY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text21), 0, 920 },
    { PORTRAIT_PETER_PAN, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text22), 0, 960 },
    { PORTRAIT_PETER_PAN, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text23), 0, 1000 },
    { PORTRAIT_SORA, 3, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text24), 0, 1340 },
    { PORTRAIT_SORA, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text25), 0, 1700 },
    { PORTRAIT_DONALD, 3, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text26), 0, 1720 },
    { PORTRAIT_DONALD, 4, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text27), 0, 1760 },
    { PORTRAIT_GOOFY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text28), 0, 1790 },
    { PORTRAIT_DONALD, 4, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent119Text29), MSG_SCRIPT_FLAG_END, 1810 },
};

#ifdef VERSION_JP
#include "event_119_text.inc"
#endif

static const EventCameraKeyframe sEvent119Camera[2] = {
    { -64316, 41984, 62464, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_SWAY, 0, NULL },
    { -64236, 47104, 67584, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_SWAY | CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_APPROACH, 60, NULL },
};

static const EvSoundCue sEvent119SoundCues[13] = {
    { SONG_NONE, 0, 0, 0 },
    { SONG_SND_387, 1, 0, 0 },
    { SONG_BGM_EVENT4, 500, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_EV_HUKUROUJUMP, 850, 0, 0 },
    { SONG_BGM_EVENT4, 1001, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_SND_387, 1020, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_PETERPAN_FIELD, 1100, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_SND_387, 1200, 0, 0 },
    { SONG_SND_387, 1650, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_SYS_PO_FALL, 1731, 0, 0 },
    { SONG_SND_354, 1750, 0, 0 },
    { SONG_SND_324, 1780, 0, 0 },
    { SONG_BGM_PETERPAN_FIELD, 1895, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCharaKeyframe sEvent119Track0[13] = {
    { 4, 0, 47872, 75008, 0, 0, 2, NULL, NULL },
    { 4, 320, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 450, 0, 0, 0, 0, 0, NULL, CreateBalloonTask },
    { 4, 490, 0, 0, 0, 0, 5, NULL, NULL },
    { 16, 505, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 601, 0, 0, 0, 0, 5, NULL, NULL },
    { 30, 603, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 1660, 0, 0, 0, 0, 5, NULL, NULL },
    { 75, 1725, 0, 0, 0, 0, 5, NULL, NULL },
    { 76, 1770, 0, 0, 0, 0, 5, NULL, NULL },
    { 0, 1775, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 1811, 0, 0, 0, 0, 69, NULL, NULL },
    { 37, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track1[7] = {
    { 114, 0, 54016, 70912, 0, 0, 2, NULL, NULL },
    { 114, 1680, 0, 0, 0, 0, 5, NULL, NULL },
    { 113, 1685, 0, 0, 0, 0, 5, NULL, NULL },
    { 112, 1719, 0, 0, 0, 0, 5, NULL, NULL },
    { 125, 1721, 0, 0, 0, 0, 5, NULL, NULL },
    { 113, 1750, 0, 0, 0, 0, 5, NULL, NULL },
    { 137, 9999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track2[6] = {
    { 146, 0, 38400, 78080, 0, 0, 2, NULL, NULL },
    { 146, 1260, 0, 0, 0, 0, 5, NULL, NULL },
    { 142, 1265, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 1270, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 1811, 0, 0, 0, 0, 69, NULL, NULL },
    { 166, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track3[16] = {
    { 299, 0, 32512, 65536, 0, 0, 66, NULL, NULL },
    { 299, 130, 0, 0, 0, 0, 69, NULL, NULL },
    { 300, 170, 0, 0, 0, 0, 69, NULL, NULL },
    { 300, 300, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 300, 510, 0, 0, 0, 0, 69, NULL, NULL },
    { 300, 560, 0, 0, 0, 0, 64, NULL, CreateQuestionTask },
    { 299, 660, 0, 0, 0, 0, 69, NULL, NULL },
    { 299, 790, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 299, 820, 0, 0, 0, 0, 69, NULL, NULL },
    { 300, 830, 0, 0, 0, 0, 69, NULL, NULL },
    { 302, 850, 40704, 61440, 0, 300, 67, NULL, NULL },
    { 307, 860, 40704, 61440, -2560, 299, 4291, NULL, NULL },
    { 307, 1010, 0, 0, 0, 0, 197, NULL, NULL },
    { 307, 1080, 40704, 61440, -25600, 299, 67, NULL, NULL },
    { 299, 0, 0, 0, 0, 0, 66, NULL, NULL },
    { 299, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track4[8] = {
    { 681, 0, 40704, 61696, 0, 0, 66, NULL, NULL },
    { 681, 150, 0, 0, 0, 0, 69, NULL, NULL },
    { 681, 850, 0, 0, 0, 0, 5, NULL, NULL },
    { 683, 860, 40704, 61696, -2560, 681, 4291, NULL, NULL },
    { 683, 1010, 0, 0, 0, 0, 197, NULL, NULL },
    { 683, 1080, 40704, 61696, -25600, 681, 67, NULL, NULL },
    { 681, 0, 0, 0, 0, 0, 66, NULL, NULL },
    { 681, 9999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track5[12] = {
    { 455, 0, 27392, 64512, -5632, 0, 66, NULL, NULL },
    { 456, 1020, 0, 0, 0, 0, 197, NULL, NULL },
    { 456, 1080, 27392, 64512, -25600, 455, 67, NULL, NULL },
    { 456, 1200, 8192, 49408, -25600, 0, 194, NULL, NULL },
    { 456, 1280, 43520, 72448, -5632, 455, 195, NULL, NULL },
    { 456, 1350, 0, 0, 0, 0, 197, NULL, NULL },
    { 456, 1370, 40960, 72448, -10752, 455, 131, NULL, NULL },
    { 456, 1550, 0, 0, 0, 0, 192, EventCharaCircleSlow, NULL },
    { 456, 1580, 40960, 72448, -10752, 455, 131, NULL, NULL },
    { 456, 1600, 0, 0, 0, 0, 197, NULL, NULL },
    { 458, 1680, 8192, 49408, -25600, 459, 131, NULL, NULL },
    { 456, 9999, 0, 0, 0, 0, 32965, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track6[6] = {
    { 260, 1730, 0, 0, 0, 0, 8258, NULL, NULL },
    { 260, 1731, 54016, 71168, -25600, 0, 16386, NULL, NULL },
    { 260, 1750, 0, 0, 0, 0, 0, EventCharaDrop, NULL },
    { 260, 1770, 0, 0, 0, 0, 5, NULL, NULL },
    { 263, 1800, 0, 0, 0, 211, 4, EventCharaHop, NULL },
    { 263, 9999, 0, 0, 0, 211, 32804, NULL, NULL },
};

static const EventCharaKeyframe sEvent119Track7[6] = {
    { 593, 1580, 0, 0, 0, 0, 8194, NULL, NULL },
    { 595, 1581, 45568, 61440, 0, 0, 16658, NULL, NULL },
    { 595, 1630, 0, 0, 0, 0, 272, NULL, CreateTinkerbellTask },
    { 595, 1660, 45568, 66560, 0, 593, 275, NULL, NULL },
    { 602, 1725, 47872, 75008, 0, 0, 274, NULL, NULL },
    { 593, 9999, 0, 0, 0, 0, 98306, NULL, NULL },
};

static const EventCharaTrack sEvent119Tracks[8] = {
    { sEvent119Track0, EVENT_CHARA_SORA },
    { sEvent119Track1, EVENT_CHARA_DONALD },
    { sEvent119Track2, EVENT_CHARA_GOOFY },
    { sEvent119Track3, EVENT_CHARA_PETER_PAN },
    { sEvent119Track4, EVENT_CHARA_WENDY },
    { sEvent119Track5, EVENT_CHARA_TINKER_BELL },
    { sEvent119Track6, EVENT_CHARA_MOOGLE },
    { sEvent119Track7, EVENT_CHARA_B_STATES_2 },
};

const EventSequenceDef gEvent119 = {
    8,
    sEvent119Tracks,
    sEvent119Camera,
    sEvent119Script,
    sEvent119SoundCues,
    NULL,
    1900,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    TRUE,
    0,
    EVENT_NONE,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    0,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
