#ifdef VERSION_US
#include "event_124_text.inc"
#endif

static const MessageScriptEntry sEvent124Script[27] = {
    { PORTRAIT_HERCULES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text00), 0, 130 },
    { PORTRAIT_CLOUD, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text01), 0, 200 },
    { PORTRAIT_HERCULES, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text02), 0, 240 },
    { PORTRAIT_CLOUD, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text03), 0, 280 },
    { PORTRAIT_HERCULES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text04), 0, 300 },
    { PORTRAIT_SORA, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text05), 0, 410 },
    { PORTRAIT_HERCULES, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text06), 0, 430 },
    { PORTRAIT_CLOUD, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text07), 0, 450 },
    { PORTRAIT_SORA, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text08), 0, 520 },
    { PORTRAIT_HADES, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text09), 0, 570 },
    { PORTRAIT_HERCULES, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text10), 0, 700 },
    { PORTRAIT_HADES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text11), 0, 810 },
    { PORTRAIT_HADES, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text12), 0, 812 },
    { PORTRAIT_CLOUD, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text13), 0, 900 },
    { PORTRAIT_HADES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text14), 0, 960 },
    { PORTRAIT_CLOUD, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text15), 0, 990 },
    { PORTRAIT_HADES, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text16), 0, 1040 },
    { PORTRAIT_SORA, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text17), 0, 1200 },
    { PORTRAIT_HADES, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text18), 0, 1230 },
    { PORTRAIT_HERCULES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text19), 0, 1260 },
    { PORTRAIT_HADES, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text20), 0, 1350 },
    { PORTRAIT_HADES, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text21), 0, 1352 },
    { PORTRAIT_HADES, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text22), 0, 1354 },
    { PORTRAIT_SORA, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text23), 0, 1390 },
    { PORTRAIT_HERCULES, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text24), 0, 1650 },
    { PORTRAIT_SORA, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text25), 0, 1680 },
    { PORTRAIT_HADES, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent124Text26), MSG_SCRIPT_FLAG_END, 1720 },
};

#ifdef VERSION_JP
#include "event_124_text.inc"
#endif

static const EvSoundCue sEvent124SoundCues[5] = {
    { SONG_BGM_EVENT2, 0, 0, 0 },
    { SONG_BGM_EVENT2, 540, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_BGM_EVENT_UNREST, 571, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT_UNREST, 1360, 0, 0 },
    { SONG_BGM_EVENT2, 1390, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent124Camera[6] = {
    { -65535, 32768, 76032, 0, EVENT_CHARA_NONE, 0, 0, NULL },
    { -64831, 65280, 57088, 0, EVENT_CHARA_NONE, CAMERA_MODE_APPROACH, 100, NULL },
    { -64443, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_MODE_KEEP, 0, NULL },
    { -64406, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_SHAKE_MEDIUM | CAMERA_MODE_KEEP, 0, NULL },
    { -64366, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_SHAKE_SMALL | CAMERA_MODE_KEEP, 0, NULL },
    { -60536, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EventBgEffectEntry sEvent124BgEffects[4] = {
    { 1050, 0, 0, 0, 0 },
    { 1080, 0, 0, 0, 0x4 },
    { 1232, 0, 0, 0, 0x2 },
    { 1292, 0, 0, 0, 0x8008 },
};

static const EventCharaKeyframe sEvent124Track0[24] = {
    { 4, 1, 19456, 86784, 0, 0, 66, NULL, NULL },
    { 14, 110, 70912, 66560, 0, 4, 99, NULL, NULL },
    { 4, 310, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 315, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 320, 0, 0, 0, 0, 5, NULL, NULL },
    { 14, 345, 0, 0, 0, 211, 36, NULL, NULL },
    { 4, 348, 0, 0, 0, 211, 4, NULL, NULL },
    { 4, 360, 0, 0, 0, 0, 5, NULL, NULL },
    { 0, 365, 0, 0, 0, 0, 5, NULL, NULL },
    { 4, 380, 0, 0, 0, 0, 69, NULL, NULL },
    { 19, 460, 0, 0, 0, 0, 69, NULL, NULL },
    { 25, 510, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 26, 575, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 702, 0, 0, 0, 0, 69, NULL, NULL },
    { 3, 707, 0, 0, 0, 0, 69, NULL, NULL },
    { 2, 1100, 0, 0, 0, 0, 69, NULL, NULL },
    { 27, 1150, 16384, 85248, 0, 4, 67, NULL, NULL },
    { 4, 1115, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 1391, 27136, 76800, 0, 0, 66, NULL, NULL },
    { 14, 1465, 60672, 61440, 0, 4, 99, NULL, NULL },
    { 4, 1480, 0, 0, 0, 0, 69, NULL, NULL },
    { 3, 1485, 0, 0, 0, 0, 69, NULL, NULL },
    { 18, 5000, 0, 0, 0, 0, 69, NULL, NULL },
    { 4, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track1[15] = {
    { 114, 1, 16640, 94464, 0, 0, 66, NULL, NULL },
    { 120, 120, 60928, 76544, 0, 114, 99, NULL, NULL },
    { 114, 350, 0, 0, 0, 0, 69, NULL, NULL },
    { 110, 702, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 710, 0, 0, 0, 0, 5, NULL, NULL },
    { 120, 760, 52736, 69120, 0, 114, 35, NULL, NULL },
    { 110, 765, 0, 0, 0, 0, 5, NULL, NULL },
    { 114, 1100, 0, 0, 0, 0, 69, NULL, NULL },
    { 133, 1150, 12288, 91136, 0, 114, 67, NULL, NULL },
    { 114, 1391, 33024, 87552, 0, 0, 66, NULL, NULL },
    { 120, 1470, 60416, 74496, 0, 114, 99, NULL, NULL },
    { 114, 1490, 0, 0, 0, 0, 69, NULL, NULL },
    { 122, 1505, 0, 0, 0, 0, 69, NULL, NULL },
    { 123, 5000, 0, 0, 0, 0, 69, NULL, NULL },
    { 114, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track2[15] = {
    { 146, 1, 7424, 90112, 0, 0, 66, NULL, NULL },
    { 153, 125, 49152, 76544, 0, 146, 99, NULL, NULL },
    { 146, 350, 0, 0, 0, 0, 69, NULL, NULL },
    { 142, 702, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 707, 0, 0, 0, 0, 5, NULL, NULL },
    { 153, 750, 46080, 66304, 0, 146, 35, NULL, NULL },
    { 142, 755, 0, 0, 0, 0, 5, NULL, NULL },
    { 146, 1100, 0, 0, 0, 0, 69, NULL, NULL },
    { 161, 1150, 5376, 88064, 0, 146, 67, NULL, NULL },
    { 146, 1391, 21248, 82688, 0, 0, 66, NULL, NULL },
    { 153, 1470, 51200, 70656, 0, 146, 99, NULL, NULL },
    { 146, 1490, 0, 0, 0, 0, 69, NULL, NULL },
    { 157, 1505, 0, 0, 0, 0, 69, NULL, NULL },
    { 158, 5000, 0, 0, 0, 0, 69, NULL, NULL },
    { 146, 9999, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track3[7] = {
    { 346, 160, 84480, 56576, 0, 0, 2, NULL, NULL },
    { 347, 202, 0, 0, 0, 0, 5, NULL, NULL },
    { 344, 825, 0, 0, 0, 0, 5, NULL, NULL },
    { 344, 875, 0, 0, 0, 0, 0, NULL, CreateExclamationTask },
    { 344, 1100, 0, 0, 0, 0, 5, NULL, NULL },
    { 346, 1130, 116736, 34560, 0, 344, 3, NULL, NULL },
    { 344, 9999, 0, 0, 0, 0, 98309, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track4[6] = {
    { 392, 675, 55552, 57088, 0, 0, 66, NULL, NULL },
    { 387, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 394, 705, 0, 0, 0, 0, 69, NULL, NULL },
    { 387, 1110, 0, 0, 0, 0, 69, NULL, NULL },
    { 394, 1170, 48896, 58368, 0, 387, 4163, NULL, NULL },
    { 393, 1620, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track5[8] = {
    { 396, 572, 103680, 86528, 0, 0, 2, NULL, NULL },
    { 398, 685, 76288, 65024, 0, 396, 3, NULL, NULL },
    { 396, 760, 0, 0, 0, 0, 5, NULL, NULL },
    { 396, 920, 0, 0, 0, 0, 69, NULL, NULL },
    { 395, 1060, 0, 0, 0, 0, 5, NULL, NULL },
    { 399, 1107, 0, 0, 0, 0, 5, NULL, NULL },
    { 400, 1275, 0, 0, 0, 0, 5, NULL, NULL },
    { 395, 9999, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track6[3] = {
    { 922, 1100, 256000, 57088, 0, 0, 8194, NULL, NULL },
    { 922, 1126, 76288, 57088, 0, 0, 16658, NULL, NULL },
    { 922, 9999, 256000, 57088, 0, 0, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent124Track7[3] = {
    { 923, 1100, 256000, 57088, 0, 0, 8194, NULL, NULL },
    { 923, 1165, 76288, 65024, 0, 0, 16658, NULL, NULL },
    { 923, 9999, 256000, 57088, 0, 0, 98306, NULL, NULL },
};

static const EventCharaTrack sEvent124Tracks[8] = {
    { sEvent124Track0, EVENT_CHARA_SORA },
    { sEvent124Track1, EVENT_CHARA_DONALD },
    { sEvent124Track2, EVENT_CHARA_GOOFY },
    { sEvent124Track3, EVENT_CHARA_CLOUD },
    { sEvent124Track4, EVENT_CHARA_HERCULES },
    { sEvent124Track5, EVENT_CHARA_HADES },
    { sEvent124Track6, EVENT_CHARA_SHOUGEKIHA },
    { sEvent124Track7, EVENT_CHARA_SHOUGEKIHA_2 },
};

const EventSequenceDef gEvent124 = {
    8,
    sEvent124Tracks,
    sEvent124Camera,
    sEvent124Script,
    sEvent124SoundCues,
    sEvent124BgEffects,
    1800,
    0,
    1,
    0,
    0,
    0,
    0,
    EVENT_125_COLISEUM_BOSS,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    0,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
