#ifdef VERSION_US
#include "event_149_text.inc"
static const MessageScriptEntry sEvent149Script[19] = {
    { 26, 5, 1, 1, { 0, 0, 0 }, gEvent149Text00, 0, 250 },
    { 26, 5, 1, 1, { 0, 0, 0 }, gEvent149Text01, 0, 400 },
    { 52, 0, 2, 1, { 0, 0, 0 }, gEvent149Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 440 },
    { 26, 2, 1, 1, { 0, 0, 0 }, gEvent149Text03, 0, 590 },
    { 52, 0, 2, 1, { 0, 0, 0 }, gEvent149Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 690 },
    { 26, 3, 1, 1, { 0, 0, 0 }, gEvent149Text05, 0, 720 },
    { 26, 3, 1, 1, { 0, 0, 0 }, gEvent149Text06, 0, 880 },
    { 26, 2, 1, 1, { 0, 0, 0 }, gEvent149Text07, 0, 1050 },
    { 52, 0, 2, 1, { 0, 0, 0 }, gEvent149Text08, MSG_SCRIPT_FLAG_SILHOUETTE, 1090 },
    { 52, 0, 4, 1, { 0, 0, 0 }, gEvent149Text09, MSG_SCRIPT_FLAG_SILHOUETTE, 1092 },
    { 26, 2, 1, 1, { 0, 0, 0 }, gEvent149Text10, 0, 1120 },
    { 52, 0, 2, 1, { 0, 0, 0 }, gEvent149Text11, MSG_SCRIPT_FLAG_SILHOUETTE, 1160 },
    { 52, 0, 2, 1, { 0, 0, 0 }, gEvent149Text12, MSG_SCRIPT_FLAG_SILHOUETTE, 1370 },
    { 26, 3, 3, 1, { 0, 0, 0 }, gEvent149Text13, 0, 1590 },
    { 52, 0, 0, 1, { 0, 0, 0 }, gEvent149Text14, MSG_SCRIPT_FLAG_SILHOUETTE, 1630 },
    { 52, 0, 4, 1, { 0, 0, 0 }, gEvent149Text15, MSG_SCRIPT_FLAG_SILHOUETTE, 1632 },
    { 52, 0, 1, 1, { 0, 0, 0 }, gEvent149Text16, MSG_SCRIPT_FLAG_SILHOUETTE, 1730 },
    { 26, 1, 3, 1, { 0, 0, 0 }, gEvent149Text17, 0, 2020 },
    { 52, 0, 1, 1, { 0, 0, 0 }, gEvent149Text18, MSG_SCRIPT_FLAG_SILHOUETTE | MSG_SCRIPT_FLAG_END, 2060 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent149Script[19] = {
    { 26, 5, 1, 3, { 0, 0, 0 }, gEvent149Text00, 0, 250 },
    { 26, 5, 1, 3, { 0, 0, 0 }, gEvent149Text01, 0, 400 },
    { 52, 0, 2, 3, { 0, 0, 0 }, gEvent149Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 440 },
    { 26, 2, 1, 3, { 0, 0, 0 }, gEvent000Text21, 0, 590 },
    { 52, 0, 2, 3, { 0, 0, 0 }, gEvent149Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 690 },
    { 26, 3, 1, 3, { 0, 0, 0 }, gEvent149Text05, 0, 720 },
    { 26, 3, 1, 3, { 0, 0, 0 }, gEvent149Text06, 0, 880 },
    { 26, 2, 1, 3, { 0, 0, 0 }, gEvent149Text07, 0, 1050 },
    { 52, 0, 2, 3, { 0, 0, 0 }, gEvent149Text08, MSG_SCRIPT_FLAG_SILHOUETTE, 1090 },
    { 52, 0, 4, 3, { 0, 0, 0 }, gEvent149Text09, MSG_SCRIPT_FLAG_SILHOUETTE, 1092 },
    { 26, 2, 1, 3, { 0, 0, 0 }, gEvent149Text10, 0, 1120 },
    { 52, 0, 2, 3, { 0, 0, 0 }, gEvent149Text11, MSG_SCRIPT_FLAG_SILHOUETTE, 1160 },
    { 52, 0, 2, 3, { 0, 0, 0 }, gEvent149Text12, MSG_SCRIPT_FLAG_SILHOUETTE, 1370 },
    { 26, 3, 3, 3, { 0, 0, 0 }, gEvent149Text13, 0, 1590 },
    { 52, 0, 0, 3, { 0, 0, 0 }, gEvent149Text14, MSG_SCRIPT_FLAG_SILHOUETTE, 1630 },
    { 52, 0, 4, 3, { 0, 0, 0 }, gEvent149Text15, MSG_SCRIPT_FLAG_SILHOUETTE, 1632 },
    { 52, 0, 1, 3, { 0, 0, 0 }, gEvent149Text16, MSG_SCRIPT_FLAG_SILHOUETTE, 1730 },
    { 26, 1, 3, 3, { 0, 0, 0 }, gEvent149Text17, 0, 2020 },
    { 52, 0, 1, 3, { 0, 0, 0 }, gEvent149Text18, MSG_SCRIPT_FLAG_SILHOUETTE | MSG_SCRIPT_FLAG_END, 2060 },
};

#include "event_149_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent149Script[19] = {
    { 26, 5, 1, 1, { 0, 0, 0 }, &gEvent149Text00, 0, 250 },
    { 26, 5, 1, 1, { 0, 0, 0 }, &gEvent149Text01, 0, 400 },
    { 52, 0, 2, 1, { 0, 0, 0 }, &gEvent149Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 440 },
    { 26, 2, 1, 1, { 0, 0, 0 }, &gEvent149Text03, 0, 590 },
    { 52, 0, 2, 1, { 0, 0, 0 }, &gEvent149Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 690 },
    { 26, 3, 1, 1, { 0, 0, 0 }, &gEvent149Text05, 0, 720 },
    { 26, 3, 1, 1, { 0, 0, 0 }, &gEvent149Text06, 0, 880 },
    { 26, 2, 1, 1, { 0, 0, 0 }, &gEvent149Text07, 0, 1050 },
    { 52, 0, 2, 1, { 0, 0, 0 }, &gEvent149Text08, MSG_SCRIPT_FLAG_SILHOUETTE, 1090 },
    { 52, 0, 4, 1, { 0, 0, 0 }, &gEvent149Text09, MSG_SCRIPT_FLAG_SILHOUETTE, 1092 },
    { 26, 2, 1, 1, { 0, 0, 0 }, &gEvent149Text10, 0, 1120 },
    { 52, 0, 2, 1, { 0, 0, 0 }, &gEvent149Text11, MSG_SCRIPT_FLAG_SILHOUETTE, 1160 },
    { 52, 0, 2, 1, { 0, 0, 0 }, &gEvent149Text12, MSG_SCRIPT_FLAG_SILHOUETTE, 1370 },
    { 26, 3, 3, 1, { 0, 0, 0 }, &gEvent149Text13, 0, 1590 },
    { 52, 0, 0, 1, { 0, 0, 0 }, &gEvent149Text14, MSG_SCRIPT_FLAG_SILHOUETTE, 1630 },
    { 52, 0, 4, 1, { 0, 0, 0 }, &gEvent149Text15, MSG_SCRIPT_FLAG_SILHOUETTE, 1632 },
    { 52, 0, 1, 1, { 0, 0, 0 }, &gEvent149Text16, MSG_SCRIPT_FLAG_SILHOUETTE, 1730 },
    { 26, 1, 3, 1, { 0, 0, 0 }, &gEvent149Text17, 0, 2020 },
    { 52, 0, 1, 1, { 0, 0, 0 }, &gEvent149Text18, MSG_SCRIPT_FLAG_SILHOUETTE | MSG_SCRIPT_FLAG_END, 2060 },
};
#endif

static const EvSoundCue sEvent149SoundCues[5] = {
    { 65535, 0, 0, 0 },
    { SONG_EV_FLASH01, 2100, 0, 0 },
    { SONG_EV_FLASH01, 2120, 0, 0 },
    { SONG_EV_FLASH01, 2130, 0, 0 },
    { SONG_EV_FLASH02, 2220, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent149Camera[13] = {
    { -65456, 32256, 98816, 0, 255, { 0, 0, 0 }, 0, 0, { 0, 0 }, NULL },
    { -65436, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_OUT_BLACK | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -65356, 32256, 41216, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 1, { 0, 0 }, NULL },
    { -65306, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_IN_BLACK | CAMERA_MODE_KEEP, 60, { 0, 0 }, NULL },
    { -65236, 32256, 41216, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 1, { 0, 0 }, NULL },
    { -64986, 32256, 36096, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 50, { 0, 0 }, NULL },
    { -64371, 32256, 32512, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 30, { 0, 0 }, NULL },
    { -63436, 32256, 29952, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 50, { 0, 0 }, NULL },
    { -63416, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -63406, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -63386, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -63316, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -63136, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_KEYFRAME_FLAG_END | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 50, { 0, 0 }, NULL },
};

static const EventCharaKeyframe sEvent149Track0[26] = {
    { 547, 300, { 0, 0 }, 29696, 39424, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 545, 460, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 545, 530, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 546, 552, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 820, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 870, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 514, 875, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 526, 882, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 900, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1030, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateBalloonTask },
    { 514, 1115, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 524, 1165, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1285, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1335, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateExclamationTask },
    { 514, 1450, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 515, 1510, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1520, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1550, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 1750, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 530, 1880, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateBalloonTask },
    { 515, 1930, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 518, 1950, { 0, 0 }, 35584, 37376, 0, 515, { 0, 0 }, 67, NULL, NULL },
    { 515, 1990, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 558, 2150, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 558, 2200, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 558, 5000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent149Track1[8] = {
    { 921, 1164, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8258, NULL, NULL },
    { 921, 1165, { 0, 0 }, 25088, 8448, 0, 0, { 0, 0 }, 16450, NULL, NULL },
    { 921, 1265, { 0, 0 }, 25088, 24832, 0, 921, { 0, 0 }, 339, NULL, NULL },
    { 921, 1400, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 469, NULL, NULL },
    { 921, 1650, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 336, EventCharaCircleSlow, NULL },
    { 921, 1700, { 0, 0 }, 39680, 22528, 0, 921, { 0, 0 }, 339, NULL, NULL },
    { 921, 2230, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 469, NULL, NULL },
    { 921, 3000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98370, NULL, NULL },
};

static const EventCharaKeyframe sEvent149Track2[5] = {
    { 591, 1960, { 0, 0 }, 256000, 0, 0, 0, { 0, 0 }, 322, NULL, NULL },
    { 591, 1961, { 0, 0 }, 39680, 22272, 0, 0, { 0, 0 }, 322, NULL, NULL },
    { 592, 2004, { 0, 0 }, 39680, 28672, 0, 591, { 0, 0 }, 323, NULL, NULL },
    { 603, 2900, { 0, 0 }, 35584, 37376, 0, 0, { 0, 0 }, 338, NULL, NULL },
    { 591, 3000, { 0, 0 }, 256000, 0, 0, 0, { 0, 0 }, 33090, NULL, NULL },
};

static const EventCharaKeyframe sEvent149Track3[3] = {
    { 928, 460, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 927, 510, { 0, 0 }, 27904, 29952, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 928, 2000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaTrack sEvent149Tracks[4] = {
    { sEvent149Track0, 44, { 0, 0, 0 } },
    { sEvent149Track1, 88, { 0, 0, 0 } },
    { sEvent149Track2, 50, { 0, 0, 0 } },
    { sEvent149Track3, 93, { 0, 0, 0 } },
};

#if defined(VERSION_US) || defined(VERSION_JP)
const EventSequenceDef gEvent149 = {
    4,
    { 0, 0, 0 },
    sEvent149Tracks,
    sEvent149Camera,
    sEvent149Script,
    sEvent149SoundCues,
    NULL,
    2390,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    150,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
#elif defined(VERSION_EU)
const EventSequenceDef gEvent149 = {
    4,
    { 0, 0, 0 },
    sEvent149Tracks,
    sEvent149Camera,
    sEvent149Script,
    sEvent149SoundCues,
    NULL,
    2390,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    148,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
#endif
