#ifdef VERSION_US
#include "event_151_text.inc"
#endif

static const MessageScriptEntry sEvent151Script[14] = {
    { PORTRAIT_RIKU, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text00), 0, 215 },
    { PORTRAIT_RIKU, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text01), 0, 310 },
    { PORTRAIT_DIZ, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text02), MSG_SCRIPT_FLAG_SILHOUETTE, 355 },
    { PORTRAIT_RIKU, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text03), 0, 365 },
    { PORTRAIT_DIZ, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text04), MSG_SCRIPT_FLAG_SILHOUETTE, 400 },
    { PORTRAIT_DIZ, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text05), MSG_SCRIPT_FLAG_SILHOUETTE, 402 },
    { PORTRAIT_RIKU, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text06), 0, 450 },
    { PORTRAIT_RIKU, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text07), 0, 570 },
    { PORTRAIT_DIZ, 0, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text08), MSG_SCRIPT_FLAG_SILHOUETTE, 610 },
    { PORTRAIT_RIKU, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text09), 0, 640 },
    { PORTRAIT_RIKU, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text10), 0, 735 },
    { PORTRAIT_RIKU, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text11), 0, 835 },
    { PORTRAIT_RIKU, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text12), 0, 837 },
    { PORTRAIT_RIKU, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent151Text13), MSG_SCRIPT_FLAG_END, 839 },
};

#ifdef VERSION_JP
#include "event_151_text.inc"
#endif

static const EvSoundCue sEvent151SoundCues[2] = {
    { SONG_BGM_HOLLOW_FIELD, 0, 0, 0 },
    { SONG_BGM_HOLLOW_FIELD, 955, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent151Camera[2] = {
    { -65536, 55552, 75264, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE, 0, NULL },
    { -64537, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 80, NULL },
};

static const EventCharaKeyframe sEvent151Track0[23] = {
    { 514, 1, 18944, 63744, 0, 0, 66, NULL, NULL },
    { 516, 155, 0, 0, 0, 83, 68, NULL, NULL },
    { 514, 160, 0, 0, 0, 0, 69, NULL, NULL },
    { 526, 210, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 526, 220, 0, 0, 0, 0, 69, NULL, NULL },
    { 514, 305, 0, 0, 0, 0, 69, NULL, NULL },
    { 524, 357, 0, 0, 0, 0, 69, NULL, NULL },
    { 514, 342, 0, 0, 0, 0, 69, NULL, NULL },
    { 526, 368, 0, 0, 0, 0, 69, NULL, NULL },
    { 514, 500, 0, 0, 0, 0, 69, NULL, NULL },
    { 514, 550, 0, 0, 0, 0, 5, NULL, NULL },
    { 543, 690, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 700, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 730, 0, 0, 0, 0, 5, NULL, NULL },
    { 538, 780, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 800, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 830, 0, 0, 0, 0, 5, NULL, NULL },
    { 524, 840, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 870, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 880, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 900, 0, 0, 0, 0, 69, NULL, NULL },
    { 522, 1500, 0, 0, 0, 45, 100, NULL, NULL },
    { 514, 5000, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaTrack sEvent151Tracks[1] = {
    { sEvent151Track0, EVENT_CHARA_RIKU },
};

const EventSequenceDef gEvent151 = {
    1,
    sEvent151Tracks,
    sEvent151Camera,
    sEvent151Script,
    sEvent151SoundCues,
    NULL,
    960,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    FALSE,
    0,
    EVENT_NONE,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    1,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
