#ifdef VERSION_US
#include "event_153_text.inc"
#endif

static const MessageScriptEntry sEvent153Script[17] = {
    { 26, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text00), 0, 150 },
    { 26, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text01), 0, 260 },
    { 26, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text02), 0, 440 },
    { 26, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text03), 0, 442 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text04), MSG_SCRIPT_FLAG_SILHOUETTE, 490 },
    { 26, 5, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text05), 0, 720 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text06), MSG_SCRIPT_FLAG_SILHOUETTE, 760 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text07), MSG_SCRIPT_FLAG_SILHOUETTE, 850 },
    { 52, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text08), MSG_SCRIPT_FLAG_SILHOUETTE, 852 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text09), 0, 880 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text10), MSG_SCRIPT_FLAG_SILHOUETTE, 920 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text11), MSG_SCRIPT_FLAG_SILHOUETTE, 1100 },
    { 52, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text12), MSG_SCRIPT_FLAG_SILHOUETTE, 1102 },
    { 52, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text13), MSG_SCRIPT_FLAG_SILHOUETTE, 1104 },
    { 52, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text14), MSG_SCRIPT_FLAG_SILHOUETTE, 1106 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text15), 0, 1125 },
    { 52, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent153Text16), MSG_SCRIPT_FLAG_SILHOUETTE | MSG_SCRIPT_FLAG_END, 1160 },
};

#ifdef VERSION_JP
#include "event_153_text.inc"
#endif

static const EvSoundCue sEvent153SoundCues[2] = {
    { SONG_BGM_EVENT_SILENCE, 0, 0, 0 },
    { SONG_BGM_EVENT_SILENCE, 1205, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent153Camera[1] = {
    { -64537, 69888, 80896, 0, 255, CAMERA_KEYFRAME_FLAG_END, 0, NULL },
};

static const EventCharaKeyframe sEvent153Track0[23] = {
    { 515, 1, 104448, 105984, 0, 0, 2, NULL, NULL },
    { 518, 120, 0, 0, 0, 211, 4, NULL, NULL },
    { 515, 180, 0, 0, 0, 0, 5, NULL, NULL },
    { 518, 210, 0, 0, 0, 211, 4, NULL, NULL },
    { 515, 230, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 270, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 400, 0, 0, 0, 0, 0, NULL, CreateBalloonTask },
    { 514, 420, 0, 0, 0, 0, 5, NULL, NULL },
    { 543, 500, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 520, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 530, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 550, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 680, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 515, 780, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 830, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 515, 875, 0, 0, 0, 0, 69, NULL, NULL },
    { 538, 882, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 940, 0, 0, 0, 0, 69, NULL, NULL },
    { 540, 1070, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 540, 1110, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 1120, 0, 0, 0, 0, 69, NULL, NULL },
    { 538, 1130, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 5000, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaTrack sEvent153Tracks[1] = {
    { sEvent153Track0, 44 },
};

const EventSequenceDef gEvent153 = {
    1,
    sEvent153Tracks,
    sEvent153Camera,
    sEvent153Script,
    sEvent153SoundCues,
    NULL,
    1210,
    0,
    0,
    0,
    0,
    1,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
