#ifdef VERSION_US
#include "event_154_text.inc"
#endif

static const MessageScriptEntry sEvent154Script[25] = {
    { 44, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text00), 0, 280 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text01), 0, 310 },
    { 44, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text02), 0, 340 },
    { 26, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text03), 0, 510 },
    { 44, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text04), 0, 540 },
    { 44, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text05), 0, 542 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text06), 0, 570 },
    { 44, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text07), 0, 600 },
    { 44, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text08), 0, 602 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text09), 0, 630 },
    { 44, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text10), 0, 660 },
    { 44, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text11), 0, 662 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text12), 0, 850 },
    { 26, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text13), 0, 852 },
    { 26, 2, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text14), 0, 1030 },
    { 26, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text15), 0, 1032 },
    { 26, 2, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text16), 0, 1120 },
    { 44, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text17), 0, 1150 },
    { 44, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text18), 0, 1152 },
    { 26, 2, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text19), 0, 1190 },
    { 26, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text20), 0, 1192 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text21), 0, 1280 },
    { 26, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text22), 0, 1345 },
    { 44, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text23), 0, 1385 },
    { 44, 2, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent154Text24), MSG_SCRIPT_FLAG_END, 1390 },
};

#ifdef VERSION_JP
#include "event_154_text.inc"
#endif

static const EvSoundCue sEvent154SoundCues[7] = {
    { 65535, 0, 0, 0 },
    { SONG_BGM_EVENT_UNREST, 285, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_SND_359, 1300, 0, 0 },
    { SONG_SND_375, 1402, 0, 0 },
    { SONG_EV_FLASH01, 1520, 0, 0 },
    { SONG_EV_FLASH01, 1530, 0, 0 },
    { SONG_EV_FLASH02, 1540, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent154Camera[6] = {
    { -65375, 34048, 84224, 0, 255, 0, 0, NULL },
    { -64136, 61696, 65280, 0, 255, CAMERA_MODE_APPROACH, 100, NULL },
    { -64016, 61696, 60928, 0, 255, CAMERA_MODE_APPROACH, 80, NULL },
    { -64006, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, NULL },
    { -63996, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 10, NULL },
    { -63966, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_KEYFRAME_FLAG_END | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 30, NULL },
};

static const EventBgEffectEntry sEvent154BgEffects[3] = {
    { 1392, 0, 0, 0, 0 },
    { 1402, 0, 0, 0, 0x4 },
    { 1412, 6, 64000, 40448, 0x8001 },
};

static const EventCharaKeyframe sEvent154Track0[26] = {
    { 515, 1, 6912, 99328, 0, 0, 66, NULL, NULL },
    { 522, 70, 0, 0, 0, 45, 100, NULL, NULL },
    { 515, 73, 0, 0, 0, 45, 68, NULL, NULL },
    { 515, 80, 0, 0, 0, 0, 69, NULL, NULL },
    { 532, 130, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 515, 170, 0, 0, 0, 0, 69, NULL, NULL },
    { 518, 230, 50944, 76544, 0, 515, 67, NULL, NULL },
    { 515, 305, 0, 0, 0, 0, 69, NULL, NULL },
    { 538, 312, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 350, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 480, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 515, 690, 0, 0, 0, 0, 69, NULL, NULL },
    { 540, 820, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 540, 880, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 900, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 910, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 940, 0, 0, 0, 0, 5, NULL, NULL },
    { 516, 970, 0, 0, 0, 173, 4, NULL, NULL },
    { 514, 1000, 0, 0, 0, 0, 5, NULL, NULL },
    { 543, 1050, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 1070, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 1080, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 1210, 0, 0, 0, 0, 69, NULL, NULL },
    { 518, 1240, 0, 0, 0, 45, 68, NULL, NULL },
    { 515, 1300, 0, 0, 0, 0, 69, NULL, NULL },
    { 560, 9000, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent154Track1[6] = {
    { 410, 661, 71424, 66560, 0, 0, 2, NULL, NULL },
    { 415, 663, 0, 0, 0, 0, 5, NULL, NULL },
    { 416, 690, 0, 0, 0, 0, 5, NULL, NULL },
    { 410, 1387, 0, 0, 0, 0, 5, NULL, NULL },
    { 414, 5000, 0, 0, 0, 0, 1029, NULL, NULL },
    { 414, 9000, 0, 0, 0, 0, 33797, NULL, NULL },
};

static const EventCharaTrack sEvent154Tracks[2] = {
    { sEvent154Track0, 44 },
    { sEvent154Track1, 30 },
};

const EventSequenceDef gEvent154 = {
    2,
    sEvent154Tracks,
    sEvent154Camera,
    sEvent154Script,
    sEvent154SoundCues,
    sEvent154BgEffects,
    1620,
    0,
    1,
    0,
    0,
    0,
    153,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
