#ifdef VERSION_US
#include "event_155_text.inc"
static const MessageScriptEntry sEvent155Script[26] = {
    { 52, 0, 0, 1, { 0, 0, 0 }, gEvent155Text00, MSG_SCRIPT_FLAG_SILHOUETTE, 210 },
    { 26, 0, 3, 1, { 0, 0, 0 }, gEvent155Text01, 0, 240 },
    { 52, 0, 0, 1, { 0, 0, 0 }, gEvent155Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 280 },
    { 26, 0, 3, 1, { 0, 0, 0 }, gEvent155Text03, 0, 310 },
    { 52, 0, 0, 1, { 0, 0, 0 }, gEvent155Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 350 },
    { 56, 0, 4, 1, { 0, 0, 0 }, gEvent155Text05, MSG_SCRIPT_FLAG_SILHOUETTE, 360 },
    { 26, 0, 3, 1, { 0, 0, 0 }, gEvent155Text06, 0, 620 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent155Text07, 0, 650 },
    { 26, 0, 3, 1, { 0, 0, 0 }, gEvent155Text08, 0, 680 },
    { 26, 2, 4, 1, { 0, 0, 0 }, gEvent155Text09, 0, 682 },
    { 56, 1, 1, 1, { 0, 0, 0 }, gEvent155Text10, 0, 715 },
    { 26, 2, 3, 1, { 0, 0, 0 }, gEvent155Text11, 0, 745 },
    { 26, 2, 2, 1, { 0, 0, 0 }, gEvent155Text12, 0, 1030 },
    { 56, 1, 1, 1, { 0, 0, 0 }, gEvent155Text13, 0, 1060 },
    { 26, 2, 2, 1, { 0, 0, 0 }, gEvent155Text14, 0, 1090 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent155Text15, 0, 1120 },
    { 26, 2, 2, 1, { 0, 0, 0 }, gEvent155Text16, 0, 1190 },
    { 56, 1, 1, 1, { 0, 0, 0 }, gEvent155Text17, 0, 1220 },
    { 61, 0, 2, 1, { 0, 0, 0 }, gEvent155Text18, MSG_SCRIPT_FLAG_SILHOUETTE, 1250 },
    { 26, 3, 2, 1, { 0, 0, 0 }, gEvent155Text19, 0, 1460 },
    { 26, 3, 2, 1, { 0, 0, 0 }, gEvent155Text20, 0, 1530 },
    { 61, 1, 2, 1, { 0, 0, 0 }, gEvent155Text21, 0, 1560 },
    { 61, 3, 2, 1, { 0, 0, 0 }, gEvent155Text22, 0, 1800 },
    { 26, 4, 3, 1, { 0, 0, 0 }, gEvent155Text23, 0, 1830 },
    { 26, 2, 3, 1, { 0, 0, 0 }, gEvent155Text24, 0, 1910 },
    { 56, 1, 1, 1, { 0, 0, 0 }, gEvent155Text25, MSG_SCRIPT_FLAG_END, 2000 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent155Script[26] = {
    { 52, 0, 0, 3, { 0, 0, 0 }, gEvent155Text00, MSG_SCRIPT_FLAG_SILHOUETTE, 210 },
    { 26, 0, 3, 3, { 0, 0, 0 }, gEvent155Text01, 0, 240 },
    { 52, 0, 0, 3, { 0, 0, 0 }, gEvent155Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 280 },
    { 26, 0, 3, 3, { 0, 0, 0 }, gEvent151Text09, 0, 310 },
    { 52, 0, 0, 3, { 0, 0, 0 }, gEvent155Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 350 },
    { 56, 0, 4, 3, { 0, 0, 0 }, gEvent155Text05, MSG_SCRIPT_FLAG_SILHOUETTE, 360 },
    { 26, 0, 3, 3, { 0, 0, 0 }, gEvent155Text06, 0, 620 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent155Text07, 0, 650 },
    { 26, 0, 3, 3, { 0, 0, 0 }, gEvent155Text08, 0, 680 },
    { 26, 2, 4, 3, { 0, 0, 0 }, gEvent155Text09, 0, 682 },
    { 56, 1, 1, 3, { 0, 0, 0 }, gEvent155Text10, 0, 715 },
    { 26, 2, 3, 3, { 0, 0, 0 }, gEvent155Text11, 0, 745 },
    { 26, 2, 2, 3, { 0, 0, 0 }, gEvent155Text12, 0, 1030 },
    { 56, 1, 1, 3, { 0, 0, 0 }, gEvent155Text13, 0, 1060 },
    { 26, 2, 2, 3, { 0, 0, 0 }, gEvent155Text14, 0, 1090 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent155Text15, 0, 1120 },
    { 26, 2, 2, 3, { 0, 0, 0 }, gEvent155Text16, 0, 1190 },
    { 56, 1, 1, 3, { 0, 0, 0 }, gEvent155Text17, 0, 1220 },
    { 61, 0, 2, 3, { 0, 0, 0 }, gEvent155Text18, MSG_SCRIPT_FLAG_SILHOUETTE, 1250 },
    { 26, 3, 2, 3, { 0, 0, 0 }, gEvent155Text19, 0, 1460 },
    { 26, 3, 2, 3, { 0, 0, 0 }, gEvent155Text20, 0, 1530 },
    { 61, 1, 2, 3, { 0, 0, 0 }, gEvent155Text21, 0, 1560 },
    { 61, 3, 2, 3, { 0, 0, 0 }, gEvent155Text22, 0, 1800 },
    { 26, 4, 3, 3, { 0, 0, 0 }, gEvent155Text23, 0, 1830 },
    { 26, 2, 3, 3, { 0, 0, 0 }, gEvent155Text24, 0, 1910 },
    { 56, 1, 1, 3, { 0, 0, 0 }, gEvent155Text25, MSG_SCRIPT_FLAG_END, 2000 },
};

#include "event_155_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent155Script[26] = {
    { 52, 0, 0, 1, { 0, 0, 0 }, &gEvent155Text00, MSG_SCRIPT_FLAG_SILHOUETTE, 210 },
    { 26, 0, 3, 1, { 0, 0, 0 }, &gEvent155Text01, 0, 240 },
    { 52, 0, 0, 1, { 0, 0, 0 }, &gEvent155Text02, MSG_SCRIPT_FLAG_SILHOUETTE, 280 },
    { 26, 0, 3, 1, { 0, 0, 0 }, &gEvent155Text03, 0, 310 },
    { 52, 0, 0, 1, { 0, 0, 0 }, &gEvent155Text04, MSG_SCRIPT_FLAG_SILHOUETTE, 350 },
    { 56, 0, 4, 1, { 0, 0, 0 }, &gEvent155Text05, MSG_SCRIPT_FLAG_SILHOUETTE, 360 },
    { 26, 0, 3, 1, { 0, 0, 0 }, &gEvent155Text06, 0, 620 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent155Text07, 0, 650 },
    { 26, 0, 3, 1, { 0, 0, 0 }, &gEvent155Text08, 0, 680 },
    { 26, 2, 4, 1, { 0, 0, 0 }, &gEvent155Text09, 0, 682 },
    { 56, 1, 1, 1, { 0, 0, 0 }, &gEvent155Text10, 0, 715 },
    { 26, 2, 3, 1, { 0, 0, 0 }, &gEvent155Text11, 0, 745 },
    { 26, 2, 2, 1, { 0, 0, 0 }, &gEvent155Text12, 0, 1030 },
    { 56, 1, 1, 1, { 0, 0, 0 }, &gEvent155Text13, 0, 1060 },
    { 26, 2, 2, 1, { 0, 0, 0 }, &gEvent155Text14, 0, 1090 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent155Text15, 0, 1120 },
    { 26, 2, 2, 1, { 0, 0, 0 }, &gEvent155Text16, 0, 1190 },
    { 56, 1, 1, 1, { 0, 0, 0 }, &gEvent155Text17, 0, 1220 },
    { 61, 0, 2, 1, { 0, 0, 0 }, &gEvent155Text18, MSG_SCRIPT_FLAG_SILHOUETTE, 1250 },
    { 26, 3, 2, 1, { 0, 0, 0 }, &gEvent155Text19, 0, 1460 },
    { 26, 3, 2, 1, { 0, 0, 0 }, &gEvent155Text20, 0, 1530 },
    { 61, 1, 2, 1, { 0, 0, 0 }, &gEvent155Text21, 0, 1560 },
    { 61, 3, 2, 1, { 0, 0, 0 }, &gEvent155Text22, 0, 1800 },
    { 26, 4, 3, 1, { 0, 0, 0 }, &gEvent155Text23, 0, 1830 },
    { 26, 2, 3, 1, { 0, 0, 0 }, &gEvent155Text24, 0, 1910 },
    { 56, 1, 1, 1, { 0, 0, 0 }, &gEvent155Text25, MSG_SCRIPT_FLAG_END, 2000 },
};
#endif

static const EvSoundCue sEvent155SoundCues[9] = {
    { SONG_BGM_EVENT_UNREST, 0, 0, 0 },
    { SONG_SND_379, 560, 0, 0 },
    { SONG_SND_376, 758, 0, 0 },
    { SONG_EV_FLASH00, 780, 0, 0 },
    { SONG_EV_WOMAN_RSTONEL, 1150, 0, 0 },
    { SONG_BGM_EVENT_UNREST, 1245, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_EV_FLASH00, 1660, 0, 0 },
    { SONG_BGM_EVENT2, 1968, 0, 0 },
    { SONG_SND_359, 1970, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent155Camera[14] = {
    { -65166, 186112, 65792, 0, 255, { 0, 0, 0 }, 0, 0, { 0, 0 }, NULL },
    { -65156, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -65116, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 20, { 0, 0 }, NULL },
    { -65106, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 10, { 0, 0 }, NULL },
    { -65026, 195840, 58368, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 80, { 0, 0 }, NULL },
    { -64976, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_HALF_FLASH | CAMERA_MODE_KEEP, 50, { 0, 0 }, NULL },
    { -64776, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -64756, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_MODE_KEEP, 20, { 0, 0 }, NULL },
    { -64736, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 20, { 0, 0 }, NULL },
    { -64656, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -63876, 168448, 71168, 0, 255, { 0, 0, 0 }, CAMERA_MODE_APPROACH, 100, { 0, 0 }, NULL },
    { -63826, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_KEYFRAME_FLAG_NO_FLASH_SOUND | CAMERA_MODE_KEEP, 50, { 0, 0 }, NULL },
    { -62536, 0, 0, 0, 255, { 0, 0, 0 }, CAMERA_MODE_KEEP, 0, { 0, 0 }, NULL },
    { -60536, 189952, 64768, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_APPROACH, 100, { 0, 0 }, NULL },
};

static const EventCharaKeyframe sEvent155Track0[14] = {
    { 515, 1, { 0, 0 }, 152064, 88064, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 518, 150, { 0, 0 }, 0, 0, 0, 45, { 0, 0 }, 68, NULL, NULL },
    { 515, 746, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 563, 760, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 548, 780, { 0, 0 }, 200704, 62976, 0, 515, { 0, 0 }, 67, NULL, NULL },
    { 550, 810, { 0, 0 }, 161024, 80384, 0, 515, { 0, 0 }, 67, NULL, NULL },
    { 547, 1380, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 547, 1480, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 545, 1860, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 546, 1882, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1930, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 514, 1940, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 1970, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 560, 3000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent155Track1[8] = {
    { 688, 560, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 688, 780, { 0, 0 }, 205824, 60160, 0, 0, { 0, 0 }, 18, EventCharaFadeIn, NULL },
    { 688, 880, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 21, NULL, NULL },
    { 690, 1000, { 0, 0 }, 179968, 72448, 0, 688, { 0, 0 }, 19, NULL, NULL },
    { 688, 1140, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 690, 1160, { 0, 0 }, 0, 0, 0, 173, { 0, 0 }, 4, NULL, NULL },
    { 688, 3000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 688, 5000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent155Track2[10] = {
    { 920, 1251, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8274, NULL, NULL },
    { 920, 1252, { 0, 0 }, 153600, 47360, 0, 0, { 0, 0 }, 16722, NULL, NULL },
    { 920, 1300, { 0, 0 }, 153600, 71680, 0, 920, { 0, 0 }, 339, NULL, NULL },
    { 920, 1350, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 469, NULL, NULL },
    { 920, 1540, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 336, EventCharaCircleSlow, NULL },
    { 920, 1570, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 469, NULL, NULL },
    { 920, 1610, { 0, 0 }, 161024, 62976, 0, 920, { 0, 0 }, 339, NULL, NULL },
    { 920, 1640, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 341, NULL, NULL },
    { 920, 1660, { 0, 0 }, 161024, 66560, 0, 0, { 0, 0 }, 4435, EventCharaFadeOut, NULL },
    { 920, 2000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98370, NULL, NULL },
};

static const EventCharaKeyframe sEvent155Track3[3] = {
    { 928, 1380, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8194, NULL, NULL },
    { 927, 1430, { 0, 0 }, 156928, 77824, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 928, 2000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98306, NULL, NULL },
};

static const EventCharaTrack sEvent155Tracks[4] = {
    { sEvent155Track0, 44, { 0, 0, 0 } },
    { sEvent155Track1, 64, { 0, 0, 0 } },
    { sEvent155Track2, 87, { 0, 0, 0 } },
    { sEvent155Track3, 93, { 0, 0, 0 } },
};

const EventSequenceDef gEvent155 = {
    4,
    { 0, 0, 0 },
    sEvent155Tracks,
    sEvent155Camera,
    sEvent155Script,
    sEvent155SoundCues,
    NULL,
    2060,
    0,
    1,
    0,
    0,
    0,
    0,
    166,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
