#ifdef VERSION_US
#include "event_156_text.inc"
static const MessageScriptEntry sEvent156Script[21] = {
    { 26, 2, 3, 1, { 0, 0, 0 }, gEvent156Text00, 0, 120 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent156Text01, 0, 150 },
    { 26, 3, 3, 1, { 0, 0, 0 }, gEvent156Text02, 0, 250 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent156Text03, 0, 280 },
    { 56, 0, 4, 1, { 0, 0, 0 }, gEvent156Text04, 0, 282 },
    { 26, 0, 3, 1, { 0, 0, 0 }, gEvent156Text05, 0, 310 },
    { 26, 1, 4, 1, { 0, 0, 0 }, gEvent156Text06, 0, 312 },
    { 56, 1, 1, 1, { 0, 0, 0 }, gEvent156Text07, 0, 540 },
    { 26, 2, 3, 1, { 0, 0, 0 }, gEvent156Text08, 0, 860 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent156Text09, 0, 890 },
    { 26, 2, 3, 1, { 0, 0, 0 }, gEvent156Text10, 0, 920 },
    { 56, 0, 1, 1, { 0, 0, 0 }, gEvent156Text11, 0, 950 },
    { 56, 0, 0, 1, { 0, 0, 0 }, gEvent156Text12, 0, 1070 },
    { 62, 0, 0, 1, { 0, 0, 0 }, gEvent156Text13, 0, 1130 },
    { 62, 0, 4, 1, { 0, 0, 0 }, gEvent156Text14, 0, 1132 },
    { 62, 0, 4, 1, { 0, 0, 0 }, gEvent156Text15, 0, 1134 },
    { 62, 0, 0, 1, { 0, 0, 0 }, gEvent156Text16, 0, 1160 },
    { 62, 0, 4, 1, { 0, 0, 0 }, gEvent156Text17, 0, 1162 },
    { 62, 0, 4, 1, { 0, 0, 0 }, gEvent156Text18, 0, 1164 },
    { 62, 0, 0, 1, { 0, 0, 0 }, gEvent156Text19, 0, 1190 },
    { 62, 0, 4, 1, { 0, 0, 0 }, gEvent156Text20, MSG_SCRIPT_FLAG_END, 1192 },
};
#endif

#ifdef VERSION_JP
static const MessageScriptEntry sEvent156Script[21] = {
    { 26, 2, 3, 3, { 0, 0, 0 }, gEvent156Text00, 0, 120 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent156Text01, 0, 150 },
    { 26, 3, 3, 3, { 0, 0, 0 }, gEvent156Text02, 0, 250 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent156Text03, 0, 280 },
    { 56, 0, 4, 3, { 0, 0, 0 }, gEvent156Text04, 0, 282 },
    { 26, 0, 3, 3, { 0, 0, 0 }, gEvent156Text05, 0, 310 },
    { 26, 1, 4, 3, { 0, 0, 0 }, gEvent156Text06, 0, 312 },
    { 56, 1, 1, 3, { 0, 0, 0 }, gEvent156Text07, 0, 540 },
    { 26, 2, 3, 3, { 0, 0, 0 }, gEvent156Text08, 0, 860 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent156Text09, 0, 890 },
    { 26, 2, 3, 3, { 0, 0, 0 }, gEvent156Text10, 0, 920 },
    { 56, 0, 1, 3, { 0, 0, 0 }, gEvent156Text11, 0, 950 },
    { 56, 1, 0, 3, { 0, 0, 0 }, gEvent156Text12, 0, 1070 },
    { 62, 0, 0, 3, { 0, 0, 0 }, gEvent156Text13, 0, 1130 },
    { 62, 0, 4, 3, { 0, 0, 0 }, gEvent156Text14, 0, 1132 },
    { 62, 0, 4, 3, { 0, 0, 0 }, gEvent156Text15, 0, 1134 },
    { 62, 0, 0, 3, { 0, 0, 0 }, gEvent156Text16, 0, 1160 },
    { 62, 0, 4, 3, { 0, 0, 0 }, gEvent156Text17, 0, 1162 },
    { 62, 0, 4, 3, { 0, 0, 0 }, gEvent156Text18, 0, 1164 },
    { 62, 0, 0, 3, { 0, 0, 0 }, gEvent156Text19, 0, 1190 },
    { 62, 0, 4, 3, { 0, 0, 0 }, gEvent156Text20, MSG_SCRIPT_FLAG_END, 1192 },
};

#include "event_156_text.inc"
#endif
#ifdef VERSION_EU
static const MessageScriptEntry sEvent156Script[21] = {
    { 26, 2, 3, 1, { 0, 0, 0 }, &gEvent156Text00, 0, 120 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent156Text01, 0, 150 },
    { 26, 3, 3, 1, { 0, 0, 0 }, &gEvent156Text02, 0, 250 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent156Text03, 0, 280 },
    { 56, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text04, 0, 282 },
    { 26, 0, 3, 1, { 0, 0, 0 }, &gEvent156Text05, 0, 310 },
    { 26, 1, 4, 1, { 0, 0, 0 }, &gEvent156Text06, 0, 312 },
    { 56, 1, 1, 1, { 0, 0, 0 }, &gEvent156Text07, 0, 540 },
    { 26, 2, 3, 1, { 0, 0, 0 }, &gEvent156Text08, 0, 860 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent156Text09, 0, 890 },
    { 26, 2, 3, 1, { 0, 0, 0 }, &gEvent156Text10, 0, 920 },
    { 56, 0, 1, 1, { 0, 0, 0 }, &gEvent156Text11, 0, 950 },
    { 56, 0, 0, 1, { 0, 0, 0 }, &gEvent156Text12, 0, 1070 },
    { 62, 0, 0, 1, { 0, 0, 0 }, &gEvent156Text13, 0, 1130 },
    { 62, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text14, 0, 1132 },
    { 62, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text15, 0, 1134 },
    { 62, 0, 0, 1, { 0, 0, 0 }, &gEvent156Text16, 0, 1160 },
    { 62, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text17, 0, 1162 },
    { 62, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text18, 0, 1164 },
    { 62, 0, 0, 1, { 0, 0, 0 }, &gEvent156Text19, 0, 1190 },
    { 62, 0, 4, 1, { 0, 0, 0 }, &gEvent156Text20, MSG_SCRIPT_FLAG_END, 1192 },
};
#endif

static const EvSoundCue sEvent156SoundCues[5] = {
    { SONG_BGM_EVENT_UNREST, 0, 0, 0 },
    { SONG_EV_CARDTHR, 507, 0, 0 },
    { SONG_SND_377, 640, 0, 0 },
    { SONG_SND_379, 990, 0, 0 },
    { SONG_BGM_EVENT_UNREST, 1245, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent156Camera[2] = {
    { -64496, 193024, 61184, 0, 255, { 0, 0, 0 }, 0, 0, { 0, 0 }, NULL },
    { -62536, 182016, 66560, 0, 255, { 0, 0, 0 }, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_APPROACH, 50, { 0, 0 }, NULL },
};

static const EventBgEffectEntry sEvent156BgEffects[5] = {
    { 580, 0, 0, 0, 0 },
    { 640, 0, 60, 0, 0x4 },
    { 736, 5, 169728, 54016, 0x1 },
    { 740, 0, 0, 0, 0x2 },
    { 840, 0, 0, 0, 0x8008 },
};

static const EventCharaKeyframe sEvent156Track0[14] = {
    { 561, 220, { 0, 0 }, 181760, 73216, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 562, 230, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 512, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 559, 600, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 670, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 720, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 515, 855, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 538, 862, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 915, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 538, 922, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 990, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 1040, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 64, NULL, CreateExclamationTask },
    { 515, 3000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 69, NULL, NULL },
    { 515, 5000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent156Track1[9] = {
    { 688, 170, { 0, 0 }, 203520, 62720, 0, 0, { 0, 0 }, 2, NULL, NULL },
    { 691, 340, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 691, 470, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 0, NULL, CreateBalloonTask },
    { 691, 490, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 692, 550, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 688, 970, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 5, NULL, NULL },
    { 688, 990, { 0, 0 }, 0, 0, 0, 45, { 0, 0 }, 4, NULL, NULL },
    { 688, 1050, { 0, 0 }, 0, 0, 0, 45, { 0, 0 }, 260, EventCharaFadeOut, NULL },
    { 688, 3000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 32770, NULL, NULL },
};

static const EventCharaKeyframe sEvent156Track2[10] = {
    { 591, 186, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 8258, NULL, NULL },
    { 607, 490, { 0, 0 }, 203520, 62720, 0, 0, { 0, 0 }, 16658, NULL, NULL },
    { 591, 506, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 591, 507, { 0, 0 }, 197632, 56832, 0, 0, { 0, 0 }, 322, NULL, NULL },
    { 591, 517, { 0, 0 }, 186880, 63232, 0, 591, { 0, 0 }, 323, NULL, NULL },
    { 591, 520, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 325, NULL, NULL },
    { 591, 526, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 604, 600, { 0, 0 }, 181760, 73216, 0, 0, { 0, 0 }, 338, NULL, NULL },
    { 591, 700, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 66, NULL, NULL },
    { 591, 5000, { 0, 0 }, 0, 0, 0, 0, { 0, 0 }, 98373, NULL, NULL },
};

static const EventCharaTrack sEvent156Tracks[3] = {
    { sEvent156Track0, 44, { 0, 0, 0 } },
    { sEvent156Track1, 64, { 0, 0, 0 } },
    { sEvent156Track2, 50, { 0, 0, 0 } },
};

#if defined(VERSION_US) || defined(VERSION_JP)
const EventSequenceDef gEvent156 = {
    3,
    { 0, 0, 0 },
    sEvent156Tracks,
    sEvent156Camera,
    sEvent156Script,
    sEvent156SoundCues,
    sEvent156BgEffects,
    1250,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    157,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
#elif defined(VERSION_EU)
const EventSequenceDef gEvent156 = {
    3,
    { 0, 0, 0 },
    sEvent156Tracks,
    sEvent156Camera,
    sEvent156Script,
    sEvent156SoundCues,
    sEvent156BgEffects,
    1250,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    155,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
#endif
