#ifdef VERSION_US
#include "event_182_text.inc"
#endif

static const MessageScriptEntry sEvent182Script[18] = {
    { PORTRAIT_RIKU, 5, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text00), 0, 200 },
    { PORTRAIT_KAIRI, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text01), 0, 420 },
    { PORTRAIT_KAIRI, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text02), 0, 580 },
    { PORTRAIT_KAIRI, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text03), 0, 582 },
    { PORTRAIT_RIKU, 3, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text04), 0, 610 },
    { PORTRAIT_KAIRI, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text05), 0, 640 },
    { PORTRAIT_KAIRI, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text06), 0, 642 },
    { PORTRAIT_RIKU, 0, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text07), 0, 670 },
    { PORTRAIT_KAIRI, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text08), 0, 700 },
    { PORTRAIT_KAIRI, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text09), 0, 702 },
    { PORTRAIT_KAIRI, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text10), 0, 704 },
    { PORTRAIT_RIKU, 0, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text11), 0, 730 },
    { PORTRAIT_KAIRI, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text12), 0, 760 },
    { PORTRAIT_RIKU, 5, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text13), 0, 860 },
    { PORTRAIT_KAIRI, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text14), 0, 970 },
    { PORTRAIT_RIKU, 0, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text15), 0, 1020 },
    { PORTRAIT_RIKU, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text16), 0, 1210 },
    { PORTRAIT_RIKU, 2, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent182Text17), MSG_SCRIPT_FLAG_END, 1350 },
};

#ifdef VERSION_JP
#include "event_182_text.inc"
#endif

static const EvSoundCue sEvent182SoundCues[4] = {
    { SONG_NONE, 0, 0, 0 },
    { SONG_EV_FLASH02, 1270, 0, 0 },
    { SONG_SND_702, 1440, 0, 0 },
    { SONG_SND_381, 1670, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent182Camera[7] = {
    { -65536, 98048, 32512, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE, 0, NULL },
    { -64296, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 60, NULL },
    { -64266, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_MODE_KEEP, 30, NULL },
    { -64236, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_MODE_KEEP, 30, NULL },
    { -63916, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_MODE_KEEP, 0, NULL },
    { -63856, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_FADE_OUT_WHITE | CAMERA_MODE_KEEP, 60, NULL },
    { -60536, 0, 0, 0, EVENT_CHARA_NONE, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EventBgEffectEntry sEvent182BgEffects[5] = {
    { 1380, 0, 0, 0, 0 },
    { 1440, 0, 0, 0, 0x14 },
    { 1490, 2, 87040, 22784, 0x1 },
    { 1600, 0, 0, 0, 0x2 },
    { 3500, 0, 0, 0, 0x8008 },
};

static const EventCharaKeyframe sEvent182Track0[11] = {
    { 565, 100, 97792, 33024, 0, 0, 258, NULL, NULL },
    { 565, 300, 0, 0, 0, 0, 1048837, NULL, NULL },
    { 565, 350, 0, 0, 0, 0, 1048832, EventCharaFadeOut, NULL },
    { 565, 1100, 41472, 17920, 0, 0, 258, NULL, NULL },
    { 514, 1205, 97280, 38400, 0, 0, 2306, EventCharaFadeIn, NULL },
    { 543, 1271, 0, 0, 0, 0, 2309, NULL, NULL },
    { 543, 1370, 0, 0, 0, 0, 261, NULL, NULL },
    { 514, 1460, 0, 0, 0, 0, 261, NULL, NULL },
    { 514, 1500, 0, 0, 0, 0, 524549, NULL, NULL },
    { 514, 2170, 41472, 17920, 0, 0, 258, NULL, NULL },
    { 514, 9000, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent182Track1[6] = {
    { 420, 450, 29696, 39424, 0, 0, 8194, NULL, NULL },
    { 420, 930, 97792, 38400, 0, 0, 16642, EventCharaFadeIn, NULL },
    { 421, 1030, 0, 0, 0, 0, 261, NULL, NULL },
    { 421, 1060, 0, 0, 0, 0, 256, EventCharaFadeOut, NULL },
    { 420, 1100, 29696, 39424, 0, 0, 2, NULL, NULL },
    { 420, 9000, 0, 0, 0, 0, 98309, NULL, NULL },
};

static const EventCharaKeyframe sEvent182Track2[7] = {
    { 695, 1459, 29696, 39424, 0, 0, 258, NULL, NULL },
    { 695, 1500, 97280, 38400, 0, 0, 524546, NULL, NULL },
    { 695, 1590, 97280, 38400, 0, 0, 258, NULL, NULL },
    { 696, 1610, 97280, 38400, 0, 0, 258, NULL, NULL },
    { 696, 1650, 0, 0, 0, 0, 325, NULL, NULL },
    { 701, 1625, 0, 0, 0, 0, 325, NULL, NULL },
    { 702, 9000, 0, 0, 0, 0, 33093, NULL, NULL },
};

static const EventCharaTrack sEvent182Tracks[3] = {
    { sEvent182Track0, EVENT_CHARA_RIKU },
    { sEvent182Track1, EVENT_CHARA_KAIRI },
    { sEvent182Track2, EVENT_CHARA_RIKU_REPLICA },
};

const EventSequenceDef gEvent182 = {
    ARRAY_COUNT(sEvent182Tracks),
    sEvent182Tracks,
    sEvent182Camera,
    sEvent182Script,
    sEvent182SoundCues,
    sEvent182BgEffects,
    1770,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    FALSE,
    0,
    EVENT_183_RIKU_B3F_E2_3,
    0,
    { 0, 0 },
    EVENT_EXIT_NONE,
    0,
    WORLD_NONE,
    POOH_LEVEL_NONE,
};
