#ifdef VERSION_US
#include "event_185_text.inc"
#endif

static const MessageScriptEntry sEvent185Script[25] = {
    { PORTRAIT_ANSEM, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text00), MSG_SCRIPT_FLAG_SILHOUETTE, 141 },
    { PORTRAIT_RIKU, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text01), 0, 170 },
    { PORTRAIT_RIKU, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text02), 0, 260 },
    { PORTRAIT_ANSEM, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text03), 0, 290 },
    { PORTRAIT_ANSEM, 1, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text04), 0, 390 },
    { PORTRAIT_RIKU, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text05), 0, 420 },
    { PORTRAIT_ANSEM, 1, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text06), 0, 450 },
    { PORTRAIT_RIKU, 3, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text07), 0, 660 },
    { PORTRAIT_ANSEM, 0, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text08), 0, 690 },
    { PORTRAIT_ANSEM, 2, 0, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text09), 0, 1240 },
    { PORTRAIT_MICKEY, 0, 2, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text10), MSG_SCRIPT_FLAG_SILHOUETTE, 1290 },
    { PORTRAIT_MICKEY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text11), 0, 1530 },
    { PORTRAIT_RIKU, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text12), 0, 1730 },
    { PORTRAIT_MICKEY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text13), 0, 1760 },
    { PORTRAIT_MICKEY, 2, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text14), 0, 1940 },
    { PORTRAIT_RIKU, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text15), 0, 1970 },
    { PORTRAIT_MICKEY, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text16), 0, 2000 },
    { PORTRAIT_RIKU, 4, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text17), 0, 2150 },
    { PORTRAIT_RIKU, 4, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text18), 0, 2152 },
    { PORTRAIT_RIKU, 3, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text19), 0, 2220 },
    { PORTRAIT_MICKEY, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text20), 0, 2300 },
    { PORTRAIT_MICKEY, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text21), 0, 2400 },
    { PORTRAIT_MICKEY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text22), 0, 2402 },
    { PORTRAIT_MICKEY, 1, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text23), 0, 2404 },
    { PORTRAIT_RIKU, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent185Text24), MSG_SCRIPT_FLAG_END, 2550 },
};

#ifdef VERSION_JP
#include "event_185_text.inc"
#endif

static const EvSoundCue sEvent185SoundCues[7] = {
    { 65535, 0, 0, 0 },
    { SONG_BGM_EVENT_UNREST, 289, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_BGM_EVENT_UNREST, 810, EV_SOUND_FLAG_FADE_OUT, 0 },
    { SONG_SND_382, 1900, 0, 0 },
    { SONG_BGM_EVENT4, 1965, EV_SOUND_FLAG_FADE_IN, 0 },
    { SONG_EV_HUKUROUJUMP, 2050, 0, 0 },
    { SONG_BGM_EVENT4, 2605, EV_SOUND_FLAG_FADE_OUT | EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent185Camera[9] = {
    { -64956, 175616, 68864, 0, 255, 0, 0, NULL },
    { -64346, 175616, 63744, 0, 255, CAMERA_MODE_APPROACH, 80, NULL },
    { -64326, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_MODE_KEEP, 20, NULL },
    { -64294, 0, 0, 0, 255, CAMERA_MODE_KEEP, 0, NULL },
    { -64284, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FLASH | CAMERA_MODE_KEEP, 10, NULL },
    { -64076, 185600, 65280, 0, 255, CAMERA_MODE_APPROACH, 20, NULL },
    { -63726, 179968, 61952, 0, 255, CAMERA_MODE_APPROACH, 50, NULL },
    { -62966, 176640, 60160, 0, 255, CAMERA_MODE_APPROACH, 50, NULL },
    { -60536, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 0, NULL },
};

static const EventCharaKeyframe sEvent185Track0[33] = {
    { 515, 1, 141568, 92416, 0, 0, 66, NULL, NULL },
    { 518, 140, 174592, 76288, 0, 515, 67, NULL, NULL },
    { 515, 190, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 240, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 515, 415, 0, 0, 0, 0, 69, NULL, NULL },
    { 538, 422, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 480, 0, 0, 0, 0, 69, NULL, NULL },
    { 532, 530, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 532, 570, 0, 0, 0, 0, 69, NULL, NULL },
    { 532, 630, 174592, 76288, -6912, 515, 4163, NULL, NULL },
    { 556, 1250, 0, 0, 0, 0, 69, NULL, NULL },
    { 532, 1260, 186112, 71168, 0, 515, 67, NULL, NULL },
    { 556, 1282, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 1300, 0, 0, 0, 0, 69, NULL, NULL },
    { 532, 1350, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 532, 1370, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 1400, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 1410, 0, 0, 0, 0, 5, NULL, NULL },
    { 514, 1460, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 1560, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 1690, 0, 0, 0, 0, 0, NULL, CreateBalloonTask },
    { 515, 1800, 0, 0, 0, 0, 5, NULL, NULL },
    { 518, 1850, 178944, 65536, 0, 515, 3, NULL, NULL },
    { 515, 1870, 0, 0, 0, 0, 5, NULL, NULL },
    { 536, 1930, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 2050, 0, 0, 0, 0, 5, NULL, NULL },
    { 554, 2060, 0, 0, 0, 83, 4, NULL, NULL },
    { 554, 2430, 0, 0, 0, 0, 5, NULL, NULL },
    { 556, 2445, 180992, 66560, 0, 0, 2, NULL, NULL },
    { 515, 2460, 0, 0, 0, 0, 5, NULL, NULL },
    { 536, 2490, 0, 0, 0, 0, 5, NULL, NULL },
    { 515, 2535, 0, 0, 0, 0, 5, NULL, NULL },
    { 558, 5000, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaKeyframe sEvent185Track1[8] = {
    { 920, 720, 0, 0, 0, 0, 8194, NULL, NULL },
    { 920, 721, 137728, 59136, 0, 0, 16642, NULL, NULL },
    { 920, 800, 166912, 53760, 0, 920, 275, NULL, NULL },
    { 920, 1050, 0, 0, 0, 0, 272, EventCharaCircleSlow, NULL },
    { 920, 1130, 174592, 52992, 0, 920, 275, NULL, NULL },
    { 920, 1160, 0, 0, 0, 0, 261, NULL, NULL },
    { 920, 1190, 174592, 57344, 0, 0, 4355, EventCharaFadeOut, NULL },
    { 920, 1000, 0, 0, 0, 0, 98306, NULL, NULL },
};

static const EventCharaKeyframe sEvent185Track2[13] = {
    { 746, 1350, 0, 0, 0, 0, 8258, NULL, NULL },
    { 746, 1356, 148224, 78336, 0, 0, 16450, NULL, NULL },
    { 754, 1480, 174080, 64000, 0, 746, 67, NULL, NULL },
    { 746, 1500, 0, 0, 0, 0, 69, NULL, NULL },
    { 745, 1840, 0, 0, 0, 0, 69, NULL, NULL },
    { 745, 1890, 0, 0, 0, 0, 64, NULL, CreateQuestionTask },
    { 749, 1920, 0, 0, 0, 0, 64, EventCharaHop, NULL },
    { 745, 2070, 0, 0, 0, 0, 69, NULL, NULL },
    { 745, 2120, 0, 0, 0, 0, 64, NULL, CreateExclamationTask },
    { 745, 2250, 0, 0, 0, 0, 69, NULL, NULL },
    { 752, 2330, 0, 0, 0, 0, 69, NULL, NULL },
    { 748, 2480, 0, 0, 0, 0, 69, NULL, NULL },
    { 745, 5000, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent185Track3[3] = {
    { 591, 2549, 0, 0, 0, 0, 8194, NULL, NULL },
    { 603, 5000, 180992, 66560, 0, 0, 16658, NULL, NULL },
    { 591, 9999, 0, 0, 0, 0, 32770, NULL, NULL },
};

static const EventCharaTrack sEvent185Tracks[4] = {
    { sEvent185Track0, 44 },
    { sEvent185Track1, 87 },
    { sEvent185Track2, 69 },
    { sEvent185Track3, 50 },
};

const EventSequenceDef gEvent185 = {
    4,
    sEvent185Tracks,
    sEvent185Camera,
    sEvent185Script,
    sEvent185SoundCues,
    NULL,
    2610,
    1,
    0,
    0,
    0,
    0,
    0,
    65535,
    0,
    { 0, 0 },
    65535,
    0,
    255,
    255,
};
