#ifdef VERSION_US
#include "event_195_text.inc"
#endif

static const MessageScriptEntry sEvent195Script[15] = {
    { PORTRAIT_MICKEY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text00), 0, 100 },
    { PORTRAIT_RIKU, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text01), 0, 130 },
    { PORTRAIT_RIKU, 0, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text02), 0, 200 },
    { PORTRAIT_RIKU, 5, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text03), 0, 202 },
    { PORTRAIT_RIKU, 5, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text04), 0, 330 },
    { PORTRAIT_MICKEY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text05), 0, 360 },
    { PORTRAIT_MICKEY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text06), 0, 550 },
    { PORTRAIT_MICKEY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text07), 0, 552 },
    { PORTRAIT_MICKEY, 0, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text08), 0, 650 },
    { PORTRAIT_MICKEY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text09), 0, 652 },
    { PORTRAIT_MICKEY, 0, 4, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text10), 0, 654 },
    { PORTRAIT_MICKEY, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text11), 0, 780 },
    { PORTRAIT_RIKU, 1, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text12), 0, 850 },
    { PORTRAIT_MICKEY, 1, 1, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text13), 0, 880 },
    { PORTRAIT_RIKU, 4, 3, EVENT_TEXT_DELAY, EVENT_TEXT(gEvent195Text14), MSG_SCRIPT_FLAG_END, 1060 },
};

#ifdef VERSION_JP
#include "event_195_text.inc"
#endif

static const EvSoundCue sEvent195SoundCues[2] = {
    { 65535, 0, 0, 0 },
    { SONG_SND_358, 836, EV_SOUND_FLAG_END, 0 },
};

static const EventCameraKeyframe sEvent195Camera[2] = {
    { -65536, 106752, 103168, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE, 0, NULL },
    { -64537, 0, 0, 0, 255, CAMERA_KEYFRAME_FLAG_FADE_IN_WHITE | CAMERA_KEYFRAME_FLAG_END | CAMERA_MODE_KEEP, 80, NULL },
};

static const EventCharaKeyframe sEvent195Track0[10] = {
    { 515, 150, 102400, 111360, 0, 0, 66, NULL, NULL },
    { 558, 270, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 295, 0, 0, 0, 0, 69, NULL, NULL },
    { 540, 380, 0, 0, 0, 0, 69, NULL, NULL },
    { 540, 510, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 540, 570, 0, 0, 0, 0, 69, NULL, NULL },
    { 515, 820, 0, 0, 0, 0, 69, NULL, NULL },
    { 536, 900, 0, 0, 0, 0, 69, NULL, NULL },
    { 536, 1030, 0, 0, 0, 0, 64, NULL, CreateBalloonTask },
    { 536, 5000, 0, 0, 0, 0, 32837, NULL, NULL },
};

static const EventCharaKeyframe sEvent195Track1[4] = {
    { 745, 670, 114944, 104704, 0, 0, 2, NULL, NULL },
    { 747, 700, 109568, 108800, 0, 745, 3, NULL, NULL },
    { 745, 730, 0, 0, 0, 0, 5, NULL, NULL },
    { 750, 1000, 0, 0, 0, 0, 32773, NULL, NULL },
};

static const EventCharaTrack sEvent195Tracks[2] = {
    { sEvent195Track0, 44 },
    { sEvent195Track1, 69 },
};

const EventSequenceDef gEvent195 = {
    2,
    sEvent195Tracks,
    sEvent195Camera,
    sEvent195Script,
    sEvent195SoundCues,
    NULL,
    1120,
    0,
    0,
    0,
    0,
    0,
    0,
    65535,
    0,
    { 0, 0 },
    13,
    0,
    255,
    255,
};
