pool: common_text
objects:
  us:
    name: common_text.s
    start: 0x08159DF0
    end: 0x0815C388
    encoding: game
    align: 2
    ctype: u16
  jp:
    name: common_text.s
    start: 0x0814E57C
    end: 0x0814FC14
    encoding: game
    align: 4
    ctype: u8
entries:
  us:
  - {name: gUnk_08159DF0, declare: false}
  - {name: gUnk_08159E10, declare: false}
  - {name: gUnk_08159E18, declare: false}
  - {name: gUnk_08159E1E, declare: false}
  - {name: gUnk_08159E4A, declare: false}
  - {name: gUnk_08159EC4, declare: false}
  - {name: common_text_006, declare: false}
  - {name: common_text_007, declare: false}
  - {name: gUnk_08159F38, declare: false}
  - {name: common_text_009, declare: false}
  - {name: gUnk_08159FBC, declare: false}
  - {name: gUnk_08159FE0, declare: false}
  - gUnk_0815A002
  - gUnk_0815A00E
  - gUnk_0815A024
  - {name: gUnk_0815A03A, declare: false}
  - {name: gUnk_0815A066, declare: false}
  - {name: gUnk_0815A078, declare: false}
  - {name: gUnk_0815A09A, declare: false}
  - {name: gUnk_0815A0A0, declare: false}
  - {name: gUnk_0815A0BA, declare: false}
  - {name: gUnk_0815A0CC, declare: false}
  - {name: gUnk_0815A0EE, declare: false}
  - {name: gUnk_0815A0F4, declare: false}
  - {name: gUnk_0815A116, declare: false}
  - {name: gUnk_0815A130, declare: false}
  - {name: gUnk_0815A152, declare: false}
  - {name: gUnk_0815A158, declare: false}
  - {name: gUnk_0815A176, declare: false}
  - {name: gUnk_0815A198, declare: false}
  - {name: common_text_030, declare: false}
  - {name: common_text_031, declare: false}
  - {name: gUnk_0815A20C, declare: false}
  - {name: gUnk_0815A23C, declare: false}
  - {name: common_text_034, declare: false}
  - {name: common_text_035, declare: false}
  - {name: gUnk_0815A2BE, declare: false}
  - {name: gUnk_0815A394, declare: false}
  - {name: gUnk_0815A3C0, declare: false}
  - {name: gUnk_0815A404, declare: false}
  - {name: gUnk_0815A428, declare: false}
  - {name: common_text_041, declare: false}
  - {name: gUnk_0815A4B6, declare: false}
  - gUnk_0815A518
  - gUnk_0815A534
  - gUnk_0815A54A
  - gUnk_0815A56C
  - gUnk_0815A57C
  - gUnk_0815A59A
  - gUnk_0815A5AA
  - gUnk_0815A5BE
  - gUnk_0815A5D4
  - gUnk_0815A5F2
  - gUnk_0815A60E
  - gUnk_0815A62A
  - gUnk_0815A64A
  - gUnk_0815A66A
  - gUnk_0815A682
  - gUnk_0815A69C
  - gUnk_0815A6AE
  - gUnk_0815A6C6
  - gUnk_0815A6DC
  - gUnk_0815A6F6
  - gUnk_0815A70E
  - gUnk_0815A72A
  - gUnk_0815A73A
  - gUnk_0815A74E
  - gUnk_0815A762
  - gUnk_0815A77A
  - gUnk_0815A790
  - gUnk_0815A7A2
  - gUnk_0815A7BE
  - gUnk_0815A7D8
  - gUnk_0815A7FA
  - gUnk_0815A804
  - gUnk_0815A816
  - gUnk_0815A826
  - gUnk_0815A830
  - gUnk_0815A840
  - gUnk_0815A84A
  - gUnk_0815A854
  - gUnk_0815A860
  - gUnk_0815A86C
  - gUnk_0815A878
  - gUnk_0815A884
  - gUnk_0815A89C
  - gUnk_0815A8A8
  - gUnk_0815A8B4
  - gUnk_0815A8C2
  - gUnk_0815A8D6
  - gUnk_0815A8EE
  - gUnk_0815A8FA
  - gUnk_0815A910
  - gUnk_0815A91E
  - gUnk_0815A932
  - gUnk_0815A94A
  - gUnk_0815A956
  - gUnk_0815A966
  - gUnk_0815A972
  - gUnk_0815A97C
  - gUnk_0815A990
  - gUnk_0815A9A4
  - gUnk_0815A9B2
  - gUnk_0815A9C2
  - gUnk_0815A9D6
  - gUnk_0815A9EC
  - gUnk_0815AA02
  - gUnk_0815AA18
  - gUnk_0815AA2A
  - gUnk_0815AA38
  - gUnk_0815AA46
  - gUnk_0815AA60
  - gUnk_0815AA7C
  - gUnk_0815AA96
  - gUnk_0815AAB2
  - gUnk_0815AAC0
  - gUnk_0815AAD8
  - gUnk_0815AAF4
  - gUnk_0815AB0E
  - gUnk_0815AB24
  - gUnk_0815AB36
  - gUnk_0815AB50
  - gUnk_0815AB62
  - gUnk_0815AB78
  - gUnk_0815AB8A
  - gUnk_0815AB98
  - gUnk_0815ABAA
  - gUnk_0815ABC8
  - gUnk_0815ABE2
  - gUnk_0815ABFE
  - gUnk_0815AC18
  - gUnk_0815AC2C
  - gUnk_0815AC40
  - gUnk_0815AC58
  - gUnk_0815AC64
  - gUnk_0815AC7C
  - gUnk_0815AC88
  - gUnk_0815AC96
  - gUnk_0815ACB0
  - gUnk_0815ACCC
  - gUnk_0815ACD6
  - gUnk_0815ACFA
  - gUnk_0815AD0C
  - gUnk_0815AD16
  - {name: common_text_144, declare: false}
  - gUnk_0815AD40
  - gUnk_0815AD4C
  - gUnk_0815AD5E
  - gUnk_0815AD7C
  - gUnk_0815AD9A
  - gUnk_0815ADAA
  - gMapNameTextUs_0815ADB6
  - gUnk_0815ADD2
  - gUnk_0815ADF4
  - gUnk_0815AE18
  - gUnk_0815AE34
  - gUnk_0815AE56
  - gUnk_0815AE7A
  - gUnk_0815AE9E
  - gUnk_0815AEBE
  - gUnk_0815AEE2
  - gUnk_0815AEFA
  - gUnk_0815AF14
  - gUnk_0815AF38
  - gUnk_0815AF52
  - gUnk_0815AF70
  - gUnk_0815AF8E
  - gUnk_0815AFA8
  - gUnk_0815AFBE
  - gUnk_0815AFD4
  - gUnk_0815AFEC
  - gUnk_0815B00E
  - gUnk_0815B02E
  - gUnk_0815B04C
  - gUnk_0815B06C
  - gUnk_0815B090
  - gUnk_0815B0B0
  - gUnk_0815B0CA
  - gUnk_0815B0E8
  - gUnk_0815B0F2
  - gUnk_0815B0FC
  - gUnk_0815B108
  - gUnk_0815B116
  - gUnk_0815B124
  - gUnk_0815B132
  - {name: common_text_185, declare: false}
  - gUnk_0815B14E
  - {name: common_text_187, declare: false}
  - gUnk_0815B16C
  - gUnk_0815B17C
  - gUnk_0815B188
  - gUnk_0815B190
  - {name: gUnk_0815B1A8, declare: false}
  - {name: gUnk_0815B1D2, declare: false}
  - gUnk_0815B1E4
  - gUnk_0815B1F4
  - gUnk_0815B1FE
  - gUnk_0815B21A
  - gUnk_0815B226
  - gUnk_0815B246
  - gUnk_0815B25A
  - gUnk_0815B26C
  - gUnk_0815B27E
  - gUnk_0815B296
  - gUnk_0815B2A2
  - gUnk_0815B2CA
  - gUnk_0815B2EC
  - gUnk_0815B30E
  - gUnk_0815B322
  - gUnk_0815B334
  - gUnk_0815B340
  - gUnk_0815B34A
  - gUnk_0815B356
  - gUnk_0815B36C
  - gUnk_0815B38C
  - gUnk_0815B39A
  - gUnk_0815B3A2
  - gUnk_0815B3AA
  - gUnk_0815B3B8
  - gUnk_0815B3C6
  - {name: gUnk_0815B3D4, declare: false}
  - {name: gUnk_0815B3FA, declare: false}
  - gUnk_0815B418
  - gUnk_0815B434
  - gUnk_0815B452
  - gUnk_0815B46C
  - gUnk_0815B484
  - gUnk_0815B49A
  - gUnk_0815B4B4
  - gUnk_0815B4CC
  - gUnk_0815B4E6
  - gUnk_0815B502
  - gUnk_0815B51E
  - gUnk_0815B53C
  - gUnk_0815B55C
  - gMapWorldNameTextUs_0815B57A
  - {name: gUnk_0815B5A6, declare: false}
  - gMapNameTextUs_0815B5C4
  - gUnk_0815B5E2
  - gMapNameTextUs_0815B5F6
  - gMapNameTextUs_0815B630
  - gMapNameTextUs_0815B66C
  - gMapNameTextUs_0815B6A6
  - gMapNameTextUs_0815B6E2
  - gMapNameTextUs_0815B71C
  - gMapNameTextUs_0815B756
  - gMapNameTextUs_0815B794
  - gMapNameTextUs_0815B7D0
  - gMapNameTextUs_0815B80A
  - gMapNameTextUs_0815B844
  - gMapNameTextUs_0815B884
  - gMapNameTextUs_0815B8C2
  - gMapNameTextUs_0815B906
  - gMapNameTextUs_0815B948
  - gMapNameTextUs_0815B98A
  - gMapNameTextUs_0815B9C6
  - gMapNameTextUs_0815BA04
  - gMapNameTextUs_0815BA44
  - gMapNameTextUs_0815BA84
  - gMapNameTextUs_0815BAC0
  - gMapNameTextUs_0815BAFE
  - gMapNameTextUs_0815BB3C
  - gMapNameTextUs_0815BB7C
  - gMapNameTextUs_0815BBB8
  - {name: common_text_264, declare: false}
  - {name: common_text_265, declare: false}
  - {name: common_text_266, declare: false}
  - {name: common_text_267, declare: false}
  - {name: common_text_268, declare: false}
  - {name: common_text_269, declare: false}
  - {name: common_text_270, declare: false}
  - {name: common_text_271, declare: false}
  - {name: common_text_272, declare: false}
  - {name: common_text_273, declare: false}
  - {name: common_text_274, declare: false}
  - {name: common_text_275, declare: false}
  - {name: common_text_276, declare: false}
  - {name: common_text_277, declare: false}
  - {name: common_text_278, declare: false}
  - {name: common_text_279, declare: false}
  - {name: common_text_280, declare: false}
  - {name: common_text_281, declare: false}
  - {name: common_text_282, declare: false}
  - {name: common_text_283, declare: false}
  - {name: common_text_284, declare: false}
  - {name: common_text_285, declare: false}
  - {name: common_text_286, declare: false}
  - {name: common_text_287, declare: false}
  - {name: common_text_288, declare: false}
  - {name: common_text_289, declare: false}
  - {name: common_text_290, declare: false}
  - {name: common_text_291, declare: false}
  - {name: common_text_292, declare: false}
  - {name: common_text_293, declare: false}
  - {name: common_text_294, declare: false}
  - {name: common_text_295, declare: false}
  - {name: common_text_296, declare: false}
  - {name: common_text_297, declare: false}
  - {name: common_text_298, declare: false}
  - {name: common_text_299, declare: false}
  - {name: common_text_300, declare: false}
  - {name: common_text_301, declare: false}
  - {name: common_text_302, declare: false}
  - {name: common_text_303, declare: false}
  - {name: common_text_304, declare: false}
  - {name: common_text_305, declare: false}
  - {name: common_text_306, declare: false}
  - {name: common_text_307, declare: false}
  - {name: common_text_308, declare: false}
  - {name: common_text_309, declare: false}
  - {name: common_text_310, declare: false}
  - {name: common_text_311, declare: false}
  - {name: common_text_312, declare: false}
  - gUnk_0815C010
  - gUnk_0815C01E
  - gUnk_0815C03A
  - gUnk_0815C058
  - gUnk_0815C078
  - gUnk_0815C096
  - gUnk_0815C0B2
  - gUnk_0815C0D0
  - gUnk_0815C0EA
  - gUnk_0815C0F2
  - gUnk_0815C10E
  - {name: gUnk_0815C136, declare: false}
  - gUnk_0815C178
  - {name: common_text_326, declare: false}
  - {name: common_text_327, declare: false}
  - {name: common_text_328, declare: false}
  - {name: gUnk_0815C1C2, declare: false}
  - {name: gUnk_0815C204, declare: false}
  - {name: common_text_331, declare: false}
  - {name: common_text_332, declare: false}
  - {name: common_text_333, declare: false}
  - {name: common_text_334, declare: false}
  - gUnk_0815C360
  - gUnk_0815C372
  jp:
  - gUnkJp_0814E57C
  - gUnkJp_0814E590
  - gUnkJp_0814E59C
  - gUnkJp_0814E5AC
  - gUnkJp_0814E5B8
  - gUnkJp_0814E5CC
  - gUnkJp_0814E5E4
  - gUnkJp_0814E5F4
  - gUnkJp_0814E604
  - gUnkJp_0814E618
  - gUnkJp_0814E62C
  - gUnkJp_0814E644
  - gUnkJp_0814E658
  - gUnkJp_0814E664
  - gUnkJp_0814E678
  - gUnkJp_0814E68C
  - gUnkJp_0814E6A0
  - gUnkJp_0814E6B4
  - gUnkJp_0814E6C8
  - gUnkJp_0814E6DC
  - gUnkJp_0814E6F0
  - gUnkJp_0814E700
  - gUnkJp_0814E714
  - gUnkJp_0814E724
  - gUnkJp_0814E734
  - gUnkJp_0814E748
  - gUnkJp_0814E758
  - gUnkJp_0814E76C
  - gUnkJp_0814E780
  - gUnkJp_0814E794
  - gUnkJp_0814E7A0
  - gUnkJp_0814E7AC
  - gUnkJp_0814E7B8
  - gUnkJp_0814E7C4
  - gUnkJp_0814E7CC
  - gUnkJp_0814E7D8
  - gUnkJp_0814E7E4
  - gUnkJp_0814E7EC
  - gUnkJp_0814E7F4
  - {name: common_text_039, declare: false}
  - gUnkJp_0814E80C
  - gUnkJp_0814E814
  - gUnkJp_0814E81C
  - gUnkJp_0814E828
  - gUnkJp_0814E834
  - gUnkJp_0814E840
  - gUnkJp_0814E84C
  - gUnkJp_0814E85C
  - gUnkJp_0814E86C
  - gUnkJp_0814E878
  - gUnkJp_0814E888
  - gUnkJp_0814E894
  - gUnkJp_0814E8A8
  - gUnkJp_0814E8B8
  - gUnkJp_0814E8C4
  - gUnkJp_0814E8DC
  - gUnkJp_0814E8E8
  - gUnkJp_0814E8F4
  - gUnkJp_0814E900
  - gUnkJp_0814E910
  - gUnkJp_0814E91C
  - gUnkJp_0814E924
  - gUnkJp_0814E92C
  - gUnkJp_0814E934
  - gUnkJp_0814E93C
  - gUnkJp_0814E944
  - gUnkJp_0814E950
  - {name: common_text_067, declare: false}
  - gUnkJp_0814E964
  - {name: common_text_069, declare: false}
  - gUnkJp_0814E978
  - gUnkJp_0814E984
  - gUnkJp_0814E990
  - gUnkJp_0814E998
  - {name: common_text_074, declare: false}
  - gUnkJp_0814E9AC
  - gUnkJp_0814E9B8
  - gUnkJp_0814E9C4
  - gUnkJp_0814E9D0
  - gUnkJp_0814E9E0
  - gUnkJp_0814E9EC
  - gUnkJp_0814E9F8
  - gUnkJp_0814EA04
  - gUnkJp_0814EA14
  - gUnkJp_0814EA28
  - gUnkJp_0814EA38
  - gUnkJp_0814EA50
  - gUnkJp_0814EA5C
  - gUnkJp_0814EA6C
  - gUnkJp_0814EA78
  - gUnkJp_0814EA8C
  - gUnkJp_0814EAA0
  - gUnkJp_0814EAB0
  - gUnkJp_0814EAC4
  - gUnkJp_0814EAD0
  - gUnkJp_0814EAE0
  - gUnkJp_0814EAF4
  - gUnkJp_0814EB04
  - gUnkJp_0814EB14
  - gUnkJp_0814EB20
  - gUnkJp_0814EB30
  - gUnkJp_0814EB40
  - gUnkJp_0814EB54
  - gUnkJp_0814EB64
  - gUnkJp_0814EB70
  - gUnkJp_0814EB80
  - gUnkJp_0814EB98
  - gUnkJp_0814EBAC
  - gUnkJp_0814EBC0
  - gUnkJp_0814EBD4
  - gUnkJp_0814EBE0
  - gUnkJp_0814EBF0
  - gUnkJp_0814EC00
  - gUnkJp_0814EC08
  - gUnkJp_0814EC1C
  - gUnkJp_0814EC28
  - gUnkJp_0814EC34
  - gUnkJp_0814EC3C
  - gUnkJp_0814EC50
  - gUnkJp_0814EC58
  - gUnkJp_0814EC70
  - {name: gUnk_0815A066, declare: false}
  - {name: gUnk_0815A0BA, declare: false}
  - {name: gUnk_0815B1D2, declare: false}
  - {name: gUnk_0815A078, declare: false}
  - {name: gUnk_0815A0CC, declare: false}
  - gUnkJp_0814ECDC
  - gUnkJp_0814ECE8
  - gUnkJp_0814ECF4
  - gUnkJp_0814ED00
  - gUnkJp_0814ED08
  - gUnkJp_0814ED1C
  - gUnkJp_0814ED28
  - gUnkJp_0814ED3C
  - gUnkJp_0814ED48
  - gUnkJp_0814ED50
  - gUnkJp_0814ED58
  - gUnkJp_0814ED68
  - gUnkJp_0814ED74
  - gUnkJp_0814ED8C
  - gUnkJp_0814EDA0
  - gUnkJp_0814EDAC
  - gUnkJp_0814EDBC
  - {name: common_text_143, declare: false}
  - gUnkJp_0814EDD4
  - gUnkJp_0814EDE0
  - gUnkJp_0814EDE8
  - gUnkJp_0814EDF0
  - gUnkJp_0814EE00
  - gUnkJp_0814EE08
  - gUnkJp_0814EE14
  - gUnkJp_0814EE1C
  - gUnkJp_0814EE24
  - gUnkJp_0814EE30
  - gUnkJp_0814EE3C
  - {name: gUnk_08159E10, declare: false}
  - {name: gUnk_08159E18, declare: false}
  - {name: gUnk_08159FBC, declare: false}
  - {name: gUnk_08159F38, declare: false}
  - gUnkJp_0814EE88
  - gUnkJp_0814EE94
  - gUnkJp_0814EEA0
  - gUnkJp_0814EEA8
  - {name: gUnk_0815A116, declare: false}
  - {name: gUnk_0815A158, declare: false}
  - {name: gUnk_0815A0F4, declare: false}
  - {name: gUnk_0815A130, declare: false}
  - {name: gUnk_0815A176, declare: false}
  - {name: gUnk_0815A0A0, declare: false}
  - {name: gUnk_0815A09A, declare: false}
  - {name: gUnk_0815A198, declare: false}
  - {name: gUnk_0815A0EE, declare: false}
  - {name: gUnk_0815A152, declare: false}
  - {name: gUnk_0815B1A8, declare: false}
  - {name: gUnk_08159E4A, declare: false}
  - {name: gUnk_0815A20C, declare: false}
  - {name: gUnk_0815A23C, declare: false}
  - {name: gUnk_0815B3D4, declare: false}
  - {name: common_text_178, declare: false}
  - {name: common_text_179, declare: false}
  - {name: gUnk_08159EC4, declare: false}
  - {name: gUnk_0815A394, declare: false}
  - {name: gUnk_0815A3C0, declare: false}
  - {name: gUnk_0815A404, declare: false}
  - {name: gUnk_0815A428, declare: false}
  - {name: gUnk_0815B3FA, declare: false}
  - {name: common_text_186, declare: false}
  - {name: gUnk_0815A4B6, declare: false}
  - {name: gUnk_0814F180, declare: false}
  - gUnkJp_0814F1CC
  - gUnkJp_0814F1DC
  - gUnkJp_0814F1EC
  - gUnkJp_0814F1FC
  - gUnkJp_0814F20C
  - gUnkJp_0814F21C
  - {name: gUnk_08159FE0, declare: false}
  - gUnkJp_0814F23C
  - gUnkJp_0814F24C
  - gUnkJp_0814F25C
  - gUnkJp_0814F270
  - gUnkJp_0814F284
  - gUnkJp_0814F298
  - gUnkJp_0814F2AC
  - gUnkJp_0814F2C0
  - gUnkJp_0814F2CC
  - gMapWorldNameTextJp_0814F2E0
  - {name: gUnk_08159E1E, declare: false}
  - {name: gUnk_0815A03A, declare: false}
  - {name: gUnk_08159DF0, declare: false}
  - {name: gUnk_0815B5A6, declare: false}
  - gUnkJp_0814F358
  - gUnkJp_0814F364
  - gUnkJp_0814F374
  - gUnkJp_0814F380
  - gUnkJp_0814F390
  - gUnkJp_0814F39C
  - gUnkJp_0814F3A8
  - gUnkJp_0814F3B8
  - gUnkJp_0814F3C8
  - gUnkJp_0814F3D8
  - gUnkJp_0814F3E8
  - gUnkJp_0814F3F8
  - gUnkJp_0814F408
  - gUnkJp_0814F418
  - gUnkJp_0814F428
  - gUnkJp_0814F438
  - gUnkJp_0814F448
  - gUnkJp_0814F460
  - gUnkJp_0814F474
  - gUnkJp_0814F484
  - gUnkJp_0814F494
  - gUnkJp_0814F4A4
  - gUnkJp_0814F4B4
  - gUnkJp_0814F4CC
  - gUnkJp_0814F4E4
  - gUnkJp_0814F4F8
  - gMapNameTextJp_0814F510
  - gMapNameTextJp_0814F520
  - gMapNameTextJp_0814F52C
  - gMapNameTextJp_0814F53C
  - gMapNameTextJp_0814F54C
  - gMapNameTextJp_0814F55C
  - gMapNameTextJp_0814F56C
  - gMapNameTextJp_0814F57C
  - gMapNameTextJp_0814F58C
  - gMapNameTextJp_0814F59C
  - gMapNameTextJp_0814F5AC
  - gMapNameTextJp_0814F5BC
  - gMapNameTextJp_0814F5D0
  - gMapNameTextJp_0814F5E4
  - gMapNameTextJp_0814F5F8
  - gMapNameTextJp_0814F60C
  - gMapNameTextJp_0814F624
  - gMapNameTextJp_0814F63C
  - gMapNameTextJp_0814F654
  - gMapNameTextJp_0814F668
  - gMapNameTextJp_0814F67C
  - gMapNameTextJp_0814F690
  - gMapNameTextJp_0814F6A4
  - gMapNameTextJp_0814F6B8
  - gMapNameTextJp_0814F6CC
  - gMapNameTextJp_0814F6E0
  - gMapNameTextJp_0814F6F4
  - {name: common_text_263, declare: false}
  - {name: common_text_264, declare: false}
  - {name: common_text_265, declare: false}
  - {name: common_text_266, declare: false}
  - {name: common_text_267, declare: false}
  - {name: common_text_268, declare: false}
  - {name: common_text_269, declare: false}
  - {name: common_text_270, declare: false}
  - {name: common_text_271, declare: false}
  - {name: common_text_272, declare: false}
  - {name: common_text_273, declare: false}
  - {name: common_text_274, declare: false}
  - {name: common_text_275, declare: false}
  - {name: common_text_276, declare: false}
  - {name: common_text_277, declare: false}
  - {name: common_text_278, declare: false}
  - {name: common_text_279, declare: false}
  - {name: common_text_280, declare: false}
  - {name: common_text_281, declare: false}
  - {name: common_text_282, declare: false}
  - {name: common_text_283, declare: false}
  - {name: common_text_284, declare: false}
  - {name: common_text_285, declare: false}
  - {name: common_text_286, declare: false}
  - {name: common_text_287, declare: false}
  - {name: common_text_288, declare: false}
  - {name: common_text_289, declare: false}
  - {name: common_text_290, declare: false}
  - {name: common_text_291, declare: false}
  - {name: common_text_292, declare: false}
  - {name: common_text_293, declare: false}
  - {name: common_text_294, declare: false}
  - {name: common_text_295, declare: false}
  - {name: common_text_296, declare: false}
  - {name: common_text_297, declare: false}
  - {name: common_text_298, declare: false}
  - {name: common_text_299, declare: false}
  - {name: common_text_300, declare: false}
  - {name: common_text_301, declare: false}
  - {name: common_text_302, declare: false}
  - {name: common_text_303, declare: false}
  - {name: common_text_304, declare: false}
  - {name: common_text_305, declare: false}
  - {name: common_text_306, declare: false}
  - {name: common_text_307, declare: false}
  - {name: common_text_308, declare: false}
  - {name: common_text_309, declare: false}
  - {name: common_text_310, declare: false}
  - {name: common_text_311, declare: false}
  - gUnkJp_0814FA0C
  - gUnkJp_0814FA18
  - gUnkJp_0814FA2C
  - gUnkJp_0814FA40
  - gUnkJp_0814FA54
  - gUnkJp_0814FA68
  - gUnkJp_0814FA7C
  - gUnkJp_0814FA90
  - gUnkJp_0814FAA0
  - gUnkJp_0814FAA8
  - gUnkJp_0814FAB8
  - {name: common_text_323, declare: false}
  - {name: gUnk_0815C204, declare: false}
  - gUnkJp_0814FB0C
  - {name: common_text_326, declare: false}
  - {name: common_text_327, declare: false}
  - {name: common_text_328, declare: false}
  - {name: common_text_329, declare: false}
  - {name: gUnk_0814FBB0, declare: false}
  - {name: gUnk_0814FBBC, declare: false}
  - {name: gUnk_0814FBD4, declare: false}
  - {name: common_text_333, declare: false}
  - {name: gUnk_0815C1C2, declare: false}
