#ifndef GUARD_PLAYER_PROGRESSION_H
#define GUARD_PLAYER_PROGRESSION_H

#include "types.h"
#include "player_progression_types.h"

enum ObtainedCardKind {
    OBTAINED_CARD_KINGDOM_KEY,
    OBTAINED_CARD_THREE_WISHES,
    OBTAINED_CARD_CRABCLAW,
    OBTAINED_CARD_PUMPKINHEAD,
    OBTAINED_CARD_FAIRY_HARP,
    OBTAINED_CARD_WISHING_STAR,
    OBTAINED_CARD_SPELLBINDER,
    OBTAINED_CARD_METAL_CHOCOBO,
    OBTAINED_CARD_OLYMPIA,
    OBTAINED_CARD_LIONHEART,
    OBTAINED_CARD_LADY_LUCK,
    OBTAINED_CARD_DIVINE_ROSE,
    OBTAINED_CARD_OATHKEEPER,
    OBTAINED_CARD_OBLIVION,
    OBTAINED_CARD_ULTIMA_WEAPON,
    OBTAINED_CARD_DIAMOND_DUST,
    OBTAINED_CARD_ONE_WINGED_ANGEL,
    OBTAINED_CARD_FIRE,
    OBTAINED_CARD_BLIZZARD,
    OBTAINED_CARD_THUNDER,
    OBTAINED_CARD_CURE,
    OBTAINED_CARD_GRAVITY,
    OBTAINED_CARD_STOP,
    OBTAINED_CARD_AERO,
    OBTAINED_CARD_SIMBA,
    OBTAINED_CARD_GENIE,
    OBTAINED_CARD_BAMBI,
    OBTAINED_CARD_DUMBO,
    OBTAINED_CARD_TINKER_BELL,
    OBTAINED_CARD_MUSHU,
    OBTAINED_CARD_CLOUD,
    OBTAINED_CARD_POTION,
    OBTAINED_CARD_HI_POTION,
    OBTAINED_CARD_MEGA_POTION,
    OBTAINED_CARD_ETHER,
    OBTAINED_CARD_MEGA_ETHER,
    OBTAINED_CARD_ELIXIR,
    OBTAINED_CARD_MEGALIXIR,
    OBTAINED_CARD_GUARD_ARMOR,
    OBTAINED_CARD_JAFAR,
    OBTAINED_CARD_TRICKMASTER,
    OBTAINED_CARD_URSULA,
    OBTAINED_CARD_PARASITE_CAGE,
    OBTAINED_CARD_DRAGON_MALEFICENT,
    OBTAINED_CARD_DARKSIDE,
    OBTAINED_CARD_OOGIE_BOOGIE,
    OBTAINED_CARD_HOOK = 48,
    OBTAINED_CARD_HADES = 50,
    OBTAINED_CARD_RIKU,
    OBTAINED_CARD_VEXEN = 54,
    OBTAINED_CARD_ANSEM = 56,
    OBTAINED_CARD_LEXAEUS
};

enum LearnedStock {
    LEARNED_STOCK_SLIDING_DASH,
    LEARNED_STOCK_BLITZ,
    LEARNED_STOCK_STUN_IMPACT,
    LEARNED_STOCK_ZANTETSUKEN,
    LEARNED_STOCK_STRIKE_RAID,
    LEARNED_STOCK_SONIC_BLADE,
    LEARNED_STOCK_ARS_ARCANUM,
    LEARNED_STOCK_RAGNAROK,
    LEARNED_STOCK_TRINITY_LIMIT,
    LEARNED_STOCK_FIRA,
    LEARNED_STOCK_FIRAGA,
    LEARNED_STOCK_BLIZZARA,
    LEARNED_STOCK_BLIZZAGA,
    LEARNED_STOCK_THUNDARA,
    LEARNED_STOCK_THUNDAGA,
    LEARNED_STOCK_CURA,
    LEARNED_STOCK_CURAGA,
    LEARNED_STOCK_GRAVIRA,
    LEARNED_STOCK_GRAVIGA,
    LEARNED_STOCK_STOPRA,
    LEARNED_STOCK_STOPGA,
    LEARNED_STOCK_AERORA,
    LEARNED_STOCK_AEROGA,
    LEARNED_STOCK_FIRE_RAID,
    LEARNED_STOCK_BLIZZARD_RAID,
    LEARNED_STOCK_THUNDER_RAID,
    LEARNED_STOCK_GRAVITY_RAID,
    LEARNED_STOCK_STOP_RAID,
    LEARNED_STOCK_JUDGMENT,
    LEARNED_STOCK_REFLECT_RAID,
    LEARNED_STOCK_HOMING_FIRA,
    LEARNED_STOCK_FIRAGA_BREAK,
    LEARNED_STOCK_MEGA_FLARE,
    LEARNED_STOCK_HOMING_BLIZZARA,
    LEARNED_STOCK_AQUA_SPLASH,
    LEARNED_STOCK_SHOCK_IMPACT,
    LEARNED_STOCK_TORNADO,
    LEARNED_STOCK_QUAKE,
    LEARNED_STOCK_WARPINATOR,
    LEARNED_STOCK_WARP,
    LEARNED_STOCK_BIND,
    LEARNED_STOCK_CONFUSE,
    LEARNED_STOCK_TERROR,
    LEARNED_STOCK_SYNCHRO,
    LEARNED_STOCK_GIFTED_MIRACLE,
    LEARNED_STOCK_TELEPORT,
    LEARNED_STOCK_HOLY,
    LEARNED_STOCK_PROUD_ROAR,
    LEARNED_STOCK_SPLASH,
    LEARNED_STOCK_PARADISE,
    LEARNED_STOCK_IDYLL_ROMP,
    LEARNED_STOCK_FLARE_BREATH,
    LEARNED_STOCK_SHOWTIME,
    LEARNED_STOCK_TWINKLE,
    LEARNED_STOCK_CROSS_SLASH,
    LEARNED_STOCK_OMNISLASH,
    LEARNED_STOCK_CROSS_SLASH_PLUS,
    LEARNED_STOCK_MAGIC,
    LEARNED_STOCK_BLAZING_DONALD,
    LEARNED_STOCK_GOOFY_CHARGE,
    LEARNED_STOCK_GOOFY_TORNADO,
    LEARNED_STOCK_SANDSTORM,
    LEARNED_STOCK_SURPRISE,
    LEARNED_STOCK_SPIRAL_WAVE,
    LEARNED_STOCK_HUMMINGBIRD,
    LEARNED_STOCK_FEROCIOUS_LUNGE,
    LEARNED_STOCK_DARK_BREAK,
    LEARNED_STOCK_DARK_FIRAGA,
    LEARNED_STOCK_DARK_AURA,
    LEARNED_STOCK_MM_MIRACLE,
    LEARNED_STOCK_SLEIGHT_57,
    LEARNED_STOCK_SLEIGHT_68
};

void AdvanceLevelExpThreshold(PlayerProgression* progression);
void InitPlayerProgression();

u8 CanLevelUp();
void SetJiminyFlag(u32 flag);
u8 IsLinkStockLearned(u32 stock);
u8 IsLinkPartnerStockLearned(u32 stock);
u8 IsStockNew(u32 stock);
void LearnStock(u32 stock);
u8 IsJiminyFlagSet(u32 flag);
u8 IsJiminyFlagNew(u32 flag);
void ClearJiminyFlagNew(u32 flag);
u8 LevelUp();
void ClearStockNew(u32 stock);
u8 IsStockLearned(u32 stock);
void SetCardKindObtained(s32 kind);
u8 IsCardKindObtained(s32 kind);

#endif
