// Generated by tools/rogue_actors.py. Do not edit.
#ifndef GUARD_ROGUE_ACTOR_ART_H
#define GUARD_ROGUE_ACTOR_ART_H

#include "rogue.h"

struct AnimDef;

// Sephiroth
#define ROGUE_SEPHIROTH_TILES 111
enum {
    ROGUE_SEPHIROTH_CLIP_IDLE,
    ROGUE_SEPHIROTH_CLIP_RUN,
    ROGUE_SEPHIROTH_CLIP_HURT,
    ROGUE_SEPHIROTH_CLIP_DOWN,
    ROGUE_SEPHIROTH_CLIP_GUARD,
    ROGUE_SEPHIROTH_CLIP_SLASH,
    ROGUE_SEPHIROTH_CLIP_SWEEP,
    ROGUE_SEPHIROTH_CLIP_RISE,
    ROGUE_SEPHIROTH_CLIP_THRUST,
    ROGUE_SEPHIROTH_CLIP_FLASH,
    ROGUE_SEPHIROTH_CLIP_PLUNGE,
    ROGUE_SEPHIROTH_CLIP_FLARE,
    ROGUE_SEPHIROTH_CLIP_WAVE,
    ROGUE_SEPHIROTH_CLIP_ANGEL,
    ROGUE_SEPHIROTH_CLIP_OCTA,
    ROGUE_SEPHIROTH_CLIP_WING,
    ROGUE_SEPHIROTH_CLIPS
};
extern const u16 gRogueSephirothActorPalette[16];
extern const struct AnimDef gRogueSephirothPoses[84];
extern const RogueClipStep* const gRogueSephirothClips[ROGUE_SEPHIROTH_CLIPS];
extern const u8 gRogueFxWaveTiles[416];
extern const u16 gRogueFxWavePalette[16];
extern const void* const gRogueFxWaveFrames[];
extern const void* const gRogueFxWaveAnims[];

#endif
