#ifndef GUARD_JIMINY_TEXT_ASSETS_H
#define GUARD_JIMINY_TEXT_ASSETS_H

#ifdef VERSION_EU

extern const JiminyLocalizedName gEnemyCardEffectNameIncrementorByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameComboPlusByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameRetrogradeByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDrawByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameBackAttackByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameGuardByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameRandomizerByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameComboFinishByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameAllZerosByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameFireBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameBlizzardBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameThunderBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameCureBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameSummonBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameBerserkByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameBioByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameVanishByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameItemBracerByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameFloatByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDrainByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameLeafBracerByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDecrementorByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameCardblindByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameReloadLockByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameProtectByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameHyperHealingByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameRandomFlushByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameReloadKinesisByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameReloadHasteByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameAutoReloadByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameQuickReloadByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameWideAttackByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameMagicBoostByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameAttackBracerByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameMimicByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameShellByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameRegenByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDispelByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameSecondChanceByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameOverdriveByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameAttackHasteByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameQuickRecoveryByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameSleightblindByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameSleightLockByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameAutoLifeByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDoubleSleightByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameValueBreakByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameDashByLanguage;
extern const JiminyLocalizedName gEnemyCardEffectNameWarpBreakByLanguage;

#endif

#endif
