#!/usr/bin/env python3
"""Turn the Station of Calling sheet into the hub screen's background.

    build/venv/bin/python tools/rogue_backgrounds.py

Writes src/rogue/rogue_bg_station.c: 8bpp tiles (repeated ones stored once), a
32x20 tile map and a 256-colour palette. The picture is the top of the first
platform of the sheet scaled to the screen, with the lower third darkened so
that the menu drawn over it can be read.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SHEET = ROOT / "mod_assets/station_of_calling.png"
OUT = ROOT / "src/rogue/rogue_bg_station.c"
PLATFORM = (0, 86, 464, 395)
MENU_TOP = 104


def c_array(kind, name, values, width, per_line):
    lines = [f"const {kind} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(f"0x{v:0{width}X}" for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    picture = Image.open(SHEET).convert("RGB").crop(PLATFORM).resize((240, 160), Image.Resampling.LANCZOS)
    pixels = picture.load()
    for y in range(MENU_TOP, 160):
        for x in range(240):
            r, g, b = pixels[x, y]
            pixels[x, y] = (r * 3 // 10, g * 3 // 10, b * 3 // 10)
    # Colour 0 is the backdrop, so the picture gets the other 255.
    quantized = picture.quantize(255, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    flat = quantized.getpalette()[:255 * 3]
    palette = [0] + [flat[i] >> 3 | (flat[i + 1] >> 3) << 5 | (flat[i + 2] >> 3) << 10 for i in range(0, len(flat), 3)]
    palette += [0] * (256 - len(palette))
    indices = quantized.load()

    tiles = {}
    tile_data = []
    tile_map = []
    blank = bytes(64)
    tiles[blank] = 0
    tile_data += blank
    for ty in range(20):
        for tx in range(32):
            if tx < 30:
                tile = bytes(indices[tx * 8 + x, ty * 8 + y] + 1 for y in range(8) for x in range(8))
            else:
                tile = blank
            if tile not in tiles:
                tiles[tile] = len(tiles)
                tile_data += tile
            tile_map.append(tiles[tile])

    OUT.write_text("\n".join([
        "// Generated by tools/rogue_backgrounds.py from mod_assets/station_of_calling.png. Do not edit.",
        '#include "types.h"', "",
        c_array("u8", "gRogueStationTiles", tile_data, 2, 16), "",
        c_array("u16", "gRogueStationMap", tile_map, 4, 16), "",
        c_array("u16", "gRogueStationPalette", palette, 4, 16), "",
    ]))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(tiles)} tiles, {len(tile_data)} bytes")


if __name__ == "__main__":
    main()
