#!/usr/bin/env python3
"""Turn single standing sprites into characters who stand in the hub.

    build/venv/bin/python tools/rogue_npcs.py

Writes src/rogue/rogue_npc_art.c and include/rogue_npc_art.h. The sprites
are cut from sheets of standing poses in mod_assets/, which are drawn at the
size of the game's own characters in the hub (SCALE is there for a sheet
that is not). A sheet of them all is written to mod_assets/npc_preview.png.
"""
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import rogue_sprites as rs  # noqa: E402
import sprite_sheet  # noqa: E402
from rogue_actors import c_bytes, c_palette  # noqa: E402

SCALE = 1
KEY = (255, 0, 255)

# Name: sheet and the box the character stands in.
NPCS = {
    "Aqua": ("zenaki_dump_1.png", (11, 21, 36, 84)),
    "Terra": ("zenaki_dump_1.png", (34, 11, 66, 85)),
    "Ventus": ("zenaki_dump_1.png", (65, 22, 93, 85)),
    "Vanitas": ("zenaki_dump_1.png", (109, 101, 136, 162)),
    "Kairi": ("zenaki_dump_1.png", (200, 271, 221, 327)),
    "Namine": ("zenaki_dump_1.png", (246, 271, 267, 327)),
}


def cut(sheet, box):
    """The character in the box alone: its neighbours on the sheet stand close enough to show at the edges."""
    crop = sheet.crop(box)
    background = sheet.getpixel((0, 0))
    px = crop.load()
    width, height = crop.size
    seen = set()
    best = []
    for y in range(height):
        for x in range(width):
            if (x, y) in seen or px[x, y] == background:
                continue
            stack, group = [(x, y)], []
            seen.add((x, y))
            while stack:
                cx, cy = stack.pop()
                group.append((cx, cy))
                for nx, ny in ((cx + 1, cy), (cx - 1, cy), (cx, cy + 1), (cx, cy - 1)):
                    if 0 <= nx < width and 0 <= ny < height and (nx, ny) not in seen and px[nx, ny] != background:
                        seen.add((nx, ny))
                        stack.append((nx, ny))
            if len(group) > len(best):
                best = group
    alone = Image.new("RGB", crop.size, KEY)
    mask = Image.new("L", crop.size, 0)
    for x, y in best:
        alone.putpixel((x, y), px[x, y])
        mask.putpixel((x, y), 255)
    return alone, mask


def small(image, mask):
    size = (round(image.width * SCALE), round(image.height * SCALE))
    # The colours are averaged over the character's own pixels only, so the
    # edge does not take the colour of what was behind it.
    solid = image.copy()
    solid.paste((0, 0, 0), mask=Image.eval(mask, lambda v: 255 - v))
    colour = solid.resize(size, Image.BOX)
    weight = mask.resize(size, Image.BOX)
    out = Image.new("RGB", size, KEY)
    for y in range(size[1]):
        for x in range(size[0]):
            w = weight.getpixel((x, y))
            if w >= 128:
                out.putpixel((x, y), tuple(min(255, c * 255 // w) for c in colour.getpixel((x, y))))
    return out


def main():
    out = ['// Generated by tools/rogue_npcs.py. Do not edit.', '#include "rogue.h"', '#include "anim.h"', '#include "msg_portrait_data.h"', '#include "rogue_npc_art.h"', '']
    declare = ["// Generated by tools/rogue_npcs.py. Do not edit.", "#ifndef GUARD_ROGUE_NPC_ART_H", "#define GUARD_ROGUE_NPC_ART_H", "",
               '#include "types.h"', ""]
    pictures = []
    faces = []
    for name, (sheet_name, box) in NPCS.items():
        sheet = Image.open(ROOT / "mod_assets" / sheet_name).convert("RGB")
        picture = small(*cut(sheet, box))
        rs.PALETTE = None
        poses = rs.Poses(["0"], {"0": picture}, KEY)
        poses.anchors["0"] = (picture.width // 2, picture.height)
        oam, block = poses.encode(["0"])
        out.append(c_bytes(f"gRogueNpc{name}Tiles", block, "const"))
        out.append(c_palette(f"gRogueNpc{name}Palette", poses.palette))
        out.append(f"static const u16 s{name}Frame[] = {{\n{rs.words(sprite_sheet.frame_words(oam[0]))}\n}};")
        out.append(f"const void* const gRogueNpc{name}Frames[] = {{ s{name}Frame }};")
        out.append(f"static const u16 s{name}Anim[] = {{ 0x0040, 0x0040, 0x0001, 0x0000, 0x00FF }};")
        out.append(f"const void* const gRogueNpc{name}Anims[] = {{ s{name}Anim }};")
        out.append("")
        declare += [f"extern const u8 gRogueNpc{name}Tiles[{len(block)}];", f"extern const u16 gRogueNpc{name}Palette[16];",
                    f"extern const void* const gRogueNpc{name}Frames[];", f"extern const void* const gRogueNpc{name}Anims[];"]
        # The face shown as they speak: the game's are busts of 64 by 96, so
        # theirs is the top of the sprite at twice its size, in its colours.
        top = picture.crop((0, 0, picture.width, 48))
        bust = Image.new("RGB", (64, 96), KEY)
        bust.paste(top.resize((top.width * 2, 96), Image.NEAREST).crop((max(0, top.width - 32), 0, max(0, top.width - 32) + 64, 96)),
                   (max(0, 32 - top.width), 0))
        rs.PALETTE = poses.palette[1:]
        face = rs.Poses(["0"], {"0": bust}, KEY)
        face.anchors["0"] = (32, 64)
        oam, block = face.encode(["0"])
        block = block + bytes(0xD80 - len(block))
        out.append(c_bytes(f"s{name}FaceTiles", block))
        out.append(f"static const u16 s{name}FaceFrame[] = {{\n{rs.words(sprite_sheet.frame_words(oam[0]))}\n}};")
        out.append(f"static const void* const s{name}FaceFrames[] = {{ s{name}FaceFrame }};")
        faces.append(f"    {{ (void*)s{name}FaceTiles, (void*)gRogueNpc{name}Palette, (void**)s{name}FaceFrames, (AnimHeader**)gRogueNpc{name}Anims, 1, 1, {{ 0, 0 }} }},")
        out.append("")
        shown = Image.new("RGB", picture.size, (64, 128, 128))
        for y, row in enumerate(poses.pixels["0"]):
            for x, value in enumerate(row):
                if value:
                    shown.putpixel((x, y), poses.palette[value])
        pictures.append(shown)
        print(f"{name}: {picture.width}x{picture.height}, {len(block) // 32} tiles")
    out += ["// The faces, in the order of the characters: portrait ROGUE_FACE_FIRST and on.",
            f"const MsgFaceAnim gRogueNpcFaces[{len(faces)}] = {{"] + faces + ["};"]
    declare += ["", "struct MsgFaceAnim;", f"extern const struct MsgFaceAnim gRogueNpcFaces[{len(faces)}];", "", "#endif"]
    (ROOT / "src/rogue/rogue_npc_art.c").write_text("\n".join(out) + "\n")
    (ROOT / "include/rogue_npc_art.h").write_text("\n".join(declare) + "\n")
    strip = Image.new("RGB", (sum(p.width + 4 for p in pictures), max(p.height for p in pictures)), (64, 128, 128))
    x = 0
    for p in pictures:
        strip.paste(p, (x, strip.height - p.height))
        x += p.width + 4
    strip.resize((strip.width * 4, strip.height * 4), Image.NEAREST).save(ROOT / "mod_assets/npc_preview.png")


if __name__ == "__main__":
    main()
