#!/usr/bin/env python3
"""Turn the Station of Calling sheet into the hub screen's background.

    build/venv/bin/python tools/rogue_backgrounds.py

Writes src/rogue/rogue_bg_station.c: 8bpp tiles (repeated ones stored once), a
32x20 tile map and a 256-colour palette. The picture is the middle of the
glass of the sheet's first platform at its own size, so that characters
standing on it look the right size, with the bottom rows darkened so that the
text drawn over them can be read.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SHEET = ROOT / "mod_assets/station_of_calling.png"
OUT = ROOT / "src/rogue/rogue_bg_station.c"
# The middle of the first platform's glass, at its own size.
GLASS = (112, 150, 352, 310)
TEXT_TOP = 130


def c_array(kind, name, values, width, per_line):
    lines = [f"const {kind} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(f"0x{v:0{width}X}" for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


# The whole top of the green station: the hub is larger than the screen and
# the picture is loaded a column or a row at a time as the camera moves, so
# its tiles are stored one after the other as they lie, none shared.
WORLD = (0, 60, 464, 348)


def main():
    picture = Image.open(SHEET).convert("RGB").crop(WORLD)
    # Round the station the sheet is white: that is the dark it stands in.
    from PIL import ImageDraw
    for corner in ((0, 0), (picture.width - 1, 0), (0, picture.height - 1), (picture.width - 1, picture.height - 1)):
        if sum(picture.getpixel(corner)) > 600:
            ImageDraw.floodfill(picture, corner, (8, 8, 16), thresh=60)
    # Colour 0 is the backdrop and the last two rows of sixteen belong to the
    # dialogue window drawn over the picture, so it gets the 223 in between.
    quantized = picture.quantize(223, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    flat = quantized.getpalette()[:223 * 3]
    palette = [0] + [flat[i] >> 3 | (flat[i + 1] >> 3) << 5 | (flat[i + 2] >> 3) << 10 for i in range(0, len(flat), 3)]
    palette += [0] * (256 - len(palette))
    indices = quantized.load()
    columns, rows = picture.width // 8, picture.height // 8
    tile_data = []
    for ty in range(rows):
        for tx in range(columns):
            tile_data += bytes(indices[tx * 8 + x, ty * 8 + y] + 1 for y in range(8) for x in range(8))

    OUT.write_text("\n".join([
        "// Generated by tools/rogue_backgrounds.py from mod_assets/station_of_calling.png. Do not edit.",
        '#include "types.h"', "",
        f"// {columns} by {rows} tiles of 8 by 8, 64 bytes each, row after row.",
        c_array("u8", "gRogueStationWorld", tile_data, 2, 32).replace("] = {", "] __attribute__((aligned(4))) = {"), "",
        c_array("u16", "gRogueStationPalette", palette, 4, 16), "",
    ]))
    print(f"station: {columns}x{rows} tiles, {len(tile_data) // 1024} KiB")


if __name__ == "__main__":
    main()
