#!/usr/bin/env python3
"""Rename two entries of the pause menu, whose labels are pictures.

    build/venv/bin/python tools/rogue_labels.py

Writes src/rogue/rogue_menu_art.c: copies of the Italian label tiles of the
pause menu, Sora's and Riku's, with the journal and the quick save renamed
for what the mod makes of them. Each label is a 96x16 plate with its name on
it; the new names are set in the plates' own letters, cut from the labels.
Needs the original ROM in roms/ and a built link map.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/rogue/rogue_menu_art.c"
LABELS = ["Controlla mazzi", "Mappamondo", "Carte Mappa", "Carte Mondo", "Stato", "Grillario", "Salvarapido"]
RENAMED = {5: "Memoria", 6: "Salva e via"}
BLOCKS = {"gUnkEu_099413B0": "gRogueMenuLabelTiles", "gUnkEu_09947CB0": "gRogueMenuLabelRikuTiles"}
WIDTH, HEIGHT = 96, 16


def label_pixels(block, label):
    """A label as rows of palette indices: three 32x16 pieces, 24 tiles."""
    rows = [[0] * WIDTH for _ in range(HEIGHT)]
    for tile in range(24):
        piece, inner = divmod(tile, 8)
        ox, oy = piece * 32 + inner % 4 * 8, inner // 4 * 8
        base = (label * 24 + tile) * 32
        for y in range(8):
            for x in range(8):
                byte = block[base + y * 4 + x // 2]
                rows[oy + y][ox + x] = byte >> 4 if x & 1 else byte & 15
    return rows


def label_tiles(rows):
    out = bytearray()
    for tile in range(24):
        piece, inner = divmod(tile, 8)
        ox, oy = piece * 32 + inner % 4 * 8, inner // 4 * 8
        for y in range(8):
            for x in range(0, 8, 2):
                out.append(rows[oy + y][ox + x] | rows[oy + y][ox + x + 1] << 4)
    return bytes(out)


def renamed(block):
    labels = [label_pixels(block, i) for i in range(len(LABELS))]
    # The name is drawn in the last two colours, the letter and its shadow,
    # on a plate that is one colour along each row inside its border.
    short = labels[LABELS.index("Stato")]
    plate = [[short[y][14] if short[y][x] >= 14 else short[y][x] for x in range(WIDTH)] for y in range(HEIGHT)]
    glyphs = {}
    for name, rows in zip(LABELS, labels):
        # A letter is a run of columns with letter colour in them, and the
        # column of shadow on its right.
        columns = [any(rows[y][x] == 15 for y in range(HEIGHT)) for x in range(WIDTH)]
        runs = []
        x = 0
        while x < WIDTH:
            if columns[x]:
                start = x
                while x < WIDTH and columns[x]:
                    x += 1
                runs.append((start, x + 1))
            else:
                x += 1
        letters = name.replace(" ", "")
        if len(runs) != len(letters):
            continue  # letters that touch: this label teaches none
        for letter, (start, end) in zip(letters, runs):
            glyphs.setdefault(letter, [[(rows[y][c], rows[y][c] >= 14) for c in range(start, end)] for y in range(HEIGHT)])
    out = bytearray(block)
    for index, name in RENAMED.items():
        missing = [c for c in name if c != " " and c not in glyphs]
        if missing:
            raise SystemExit(f"no letter {missing} to write {name!r} with")
        width = sum(4 if c == " " else len(glyphs[c][0]) for c in name)
        rows = [list(row) for row in plate]
        x = (WIDTH - width) // 2
        for c in name:
            if c == " ":
                x += 4
                continue
            for y in range(HEIGHT):
                for dx, (value, drawn) in enumerate(glyphs[c][y]):
                    if drawn:
                        rows[y][x + dx] = value
            x += len(glyphs[c][0])
        out[index * 24 * 32:(index + 1) * 24 * 32] = label_tiles(rows)
    return bytes(out)


def main():
    text = (ROOT / "build/eu/com_eu.map").read_text()
    symbols = {name: int(addr, 16) - 0x08000000 for addr, name in re.findall(r"^\s+0x(0[89][0-9a-f]{6})\s+(\w+)$", text, re.M)}
    rom = (ROOT / "roms/B8CP.gba").read_bytes()
    out = ["// Generated by tools/rogue_labels.py. Do not edit.", '#include "types.h"', ""]
    for source, name in BLOCKS.items():
        data = renamed(rom[symbols[source]:symbols[source] + len(LABELS) * 24 * 32])
        out.append(f"const u8 {name}[{len(data)}] __attribute__((aligned(4))) = {{")
        out += ["    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + "," for i in range(0, len(data), 16)]
        out += ["};", ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
