#!/usr/bin/env python3
"""Turn the Station of Calling sheet into the hub screen's background.

    build/venv/bin/python tools/rogue_backgrounds.py

Writes src/rogue/rogue_bg_station.c: 8bpp tiles (repeated ones stored once), a
32x20 tile map and a 256-colour palette. The picture is the middle of the
glass of the sheet's first platform at its own size, so that characters
standing on it look the right size, with the bottom rows darkened so that the
text drawn over them can be read.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SHEET = ROOT / "mod_assets/station_of_calling.png"
OUT = ROOT / "src/rogue/rogue_bg_station.c"
# The middle of the first platform's glass, at its own size.
GLASS = (112, 150, 352, 310)
TEXT_TOP = 130


def c_array(kind, name, values, width, per_line):
    lines = [f"const {kind} {name}[{len(values)}] = {{"]
    for i in range(0, len(values), per_line):
        lines.append("    " + ", ".join(f"0x{v:0{width}X}" for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    picture = Image.open(SHEET).convert("RGB").crop(GLASS)
    pixels = picture.load()
    for y in range(TEXT_TOP, 160):
        for x in range(240):
            r, g, b = pixels[x, y]
            pixels[x, y] = (r * 3 // 10, g * 3 // 10, b * 3 // 10)
    # Colour 0 is the backdrop and the last two rows of sixteen belong to the
    # dialogue window drawn over the picture, so it gets the 223 in between.
    quantized = picture.quantize(223, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    flat = quantized.getpalette()[:223 * 3]
    palette = [0] + [flat[i] >> 3 | (flat[i + 1] >> 3) << 5 | (flat[i + 2] >> 3) << 10 for i in range(0, len(flat), 3)]
    palette += [0] * (256 - len(palette))
    indices = quantized.load()

    tiles = {}
    tile_data = []
    tile_map = []
    blank = bytes(64)
    tiles[blank] = 0
    tile_data += blank
    for ty in range(20):
        for tx in range(32):
            if tx < 30:
                tile = bytes(indices[tx * 8 + x, ty * 8 + y] + 1 for y in range(8) for x in range(8))
            else:
                tile = blank
            if tile not in tiles:
                tiles[tile] = len(tiles)
                tile_data += tile
            tile_map.append(tiles[tile])

    OUT.write_text("\n".join([
        "// Generated by tools/rogue_backgrounds.py from mod_assets/station_of_calling.png. Do not edit.",
        '#include "types.h"', "",
        c_array("u8", "gRogueStationTiles", tile_data, 2, 16), "",
        "const u32 gRogueStationTilesSize = sizeof(gRogueStationTiles);", "",
        c_array("u16", "gRogueStationMap", tile_map, 4, 16), "",
        c_array("u16", "gRogueStationPalette", palette, 4, 16), "",
    ]))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(tiles)} tiles, {len(tile_data)} bytes")


if __name__ == "__main__":
    main()
