#!/usr/bin/env python3
"""List the enemies and bosses whose cards call them in as tag characters.

    python3 tools/rogue_tags.py

Writes src/rogue/rogue_tag_enemies.inc: for each enemy card, the sprite set
of its enemy, the animation it attacks with and the frame the hit lands on,
read out of the enemies' own code in src/btl/emy.c. Needs the original ROM in
roms/ and a built link map, for the size of each enemy's tile block.
"""
import re
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/rogue/rogue_tag_enemies.inc"

# First card id of each enemy's cards and the number in its file names.
ENEMY_CARDS = [
    (450, "00"), (453, "14"), (456, "38"), (459, "01"), (462, "02"), (465, "03"), (468, "04"), (471, "15"), (474, "16"),
    (477, "18"), (480, "19"), (483, "39"), (486, "21"), (489, "22"), (492, "06"), (495, "23"), (498, "41"), (501, "25"),
    (504, "26"), (507, "27"), (510, "28"), (513, "29"), (516, "44"), (519, "30"), (522, "31"), (525, "37"), (528, "07"),
    (529, "08"), (532, "83"), (535, "81"), (538, "82"), (541, None), (545, "TrumpH"), (548, "TrumpS"),
]
# What the hit is, for the enemies that are not just a blow: Sora's Fire,
# Blizzard and Thunder, or 0 for the ones that heal.
SPECIAL = {"01": (66, 110), "02": (69, 130), "03": (72, 150), "04": (0, 38), "07": (0, 51)}
# The bosses with a body of their own: (card ids, animations, slot, palette, tiles, attack, scale).
BOSSES = [
    ((551, 551), "gUnk_0813F22C", 3, "gHadesPalette", 100, 66, 220),
    ((555, 555), "gHumHookAnimDefs", 11, "gHookPalette", 128, 14, 768),
    ((557, 557), "gHumRikuAnimDefs", 10, "gNiserikuPalette", 64, 14, 768),
    ((558, 558), "gUnk_0813F5E0", 3, "gAccelePalette", 102, 303, 384),
    ((559, 559), "gHumLaxeneAnimDefs", 4, "gLaxinePalette", 128, 72, 220),
    ((560, 560), "gHumVixenAnimDefs", 3, "gVixenPalette", 83, 313, 512),
    ((561, 562), "gUnk_0813F368", 7, "gMaruxhaPalette", 90, 14, 896),
    ((563, 563), "gHumLexceusAnimDefs", 3, "gRexeusPalette", 128, 14, 1024),
    ((564, 564), "gUnk_0813F0D0", 2, "gAnsemPalette", 80, 14, 896),
]
# The giants have no body that fits: their cards shake the ground around Sora.
GIANTS = [(541, 544), (552, 554), (556, 556)]


def main():
    lines = (ROOT / "src/btl/emy.c").read_text().split("\n")
    owner, pending, defs = {}, [], {}
    for line in lines:
        m = re.match(r"const AnimDef (\w+)\[", line)
        if m:
            pending.append(m.group(1))
        m = re.match(r"const EmyDef gEmy(\w+)Def = \{ (\w+), (\w+), .*\{ (\d+),", line)
        if m:
            for table in pending:
                owner[table] = m.group(1)
            defs[m.group(1)] = (m.group(2), m.group(3), int(m.group(4)), pending)
            pending = []
    # An enemy's attack: the animation set just before a hit is tested, with
    # the frame the shared melee routine waits for when it is the one testing.
    attacks = {}
    last = None
    for number, line in enumerate(lines):
        m = re.search(r"AnimChangeWithDef\((\w+), [^,]+, (\w+),", line)
        if m:
            last = (m.group(1), m.group(2), number)
        hit = None
        m = re.search(r"func_0800C980\(\S+, (\w+),", line)
        if m:
            hit = int(m.group(1), 0)
        elif "func_08011F78(" in line:
            hit = 24
        if hit is not None and last and last[0] in owner and number - last[2] < 60 and last[1].isdigit():
            attacks.setdefault(owner[last[0]], (last[0], int(last[1]), hit))
    text = (ROOT / "build/eu/com_eu.map").read_text()
    symbols = {name: int(addr, 16) - 0x08000000 for addr, name in re.findall(r"^\s+0x(0[89][0-9a-f]{6})\s+(\w+)$", text, re.M)}
    rom = (ROOT / "roms/B8CP.gba").read_bytes()
    out = ["// Generated by tools/rogue_tags.py. Do not edit.", ""]
    tables = set()
    rows = []
    ends = [first for first, _ in ENEMY_CARDS[1:]] + [551]
    for (first, name), end in zip(ENEMY_CARDS, ends):
        if name is None:
            continue
        palette, stand, kind, own = defs[name]
        # Failing that, the first of its actions.
        table, slot, hit = attacks.get(name, (own[1] if len(own) > 1 else stand, 0, 24))
        tiles = struct.unpack_from("<H", rom, symbols["gUnk_09EDA4EC"] + 2 * kind)[0]
        attack, scale = SPECIAL.get(name, (14, 512))
        tables.add(table)
        hit = max(4, hit // 2)  # the move plays at twice its speed
        rows.append(f"    {{ 0, {table}, {palette}, 0, {slot}, {hit}, {hit + 16}, {attack}, {scale}, {first}, {end - 1}, {tiles}, 1 }}, // {name}")
    for (first, last_card), table, slot, palette, tiles, attack, scale in BOSSES:
        tables.add(table)
        rows.append(f"    {{ 0, {table}, {palette}, 0, {slot}, 12, 30, {attack}, {scale}, {first}, {last_card}, {tiles}, 1 }},")
    for first, last_card in GIANTS:
        rows.append(f"    {{ 0, 0, 0, 0, 0, 10, 26, 14, 1024, {first}, {last_card}, 0, 0 }},")
    out.append("extern const AnimDef " + ", ".join(f"{t}[]" for t in sorted(tables)) + ";")
    out.append("")
    out.append("static const RogueTagDef sEnemyTags[] = {")
    out += rows
    out.append("};")
    OUT.write_text("\n".join(out) + "\n")
    print(f"{len(rows)} enemy and boss tags, {sum(1 for n in defs if n not in attacks)} enemies without a known attack")


if __name__ == "__main__":
    main()
