#!/usr/bin/env python3
"""Turn pictures from the custom card sheets into the mod's card art.

    build/venv/bin/python tools/rogue_cards.py

Writes src/rogue/rogue_card_art.c. Each card gets what a vanilla card has: a
32x32 picture (16 tiles, 4bpp) with its palette, and the 16x32 card shown in
the hand and the deck (8 tiles) with a palette of its own. The small card is
the vanilla Kingdom Key one, read from the original ROM, with the new picture
shrunk into its window.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BASEROM = ROOT / "roms/B8CP.gba"
OUT = ROOT / "src/rogue/rogue_card_art.c"

# The vanilla small Kingdom Key card and its palette, as ROM offsets.
SMALL_TILES = 0x010EBEF0
SMALL_PALETTE = 0x01545CA4
TRANSPARENT = (255, 0, 255)

# name: (sheet, box of the picture with its border)
CARDS = {
    "BondOfFlame": ("extra_cards_1.png", (118, 340, 148, 374)),
    "TwoBecomeOne": ("extra_cards_1.png", (118, 395, 148, 428)),
    "HiddenDragon": ("extra_cards_1.png", (119, 283, 149, 316)),
    "FollowTheWind": ("extra_cards_1.png", (118, 226, 150, 259)),
    "Monochrome": ("extra_cards_1.png", (118, 454, 148, 487)),
}


def rom_palette(rom, offset):
    colors = []
    for i in range(16):
        value = rom[offset + 2 * i] | rom[offset + 2 * i + 1] << 8
        colors.append(((value & 31) << 3, (value >> 5 & 31) << 3, (value >> 10 & 31) << 3))
    return colors


def rom_tiles(rom, offset, count, columns, palette):
    image = Image.new("RGB", (columns * 8, count // columns * 8))
    for tile in range(count):
        for y in range(8):
            for x in range(8):
                byte = rom[offset + tile * 32 + y * 4 + x // 2]
                index = byte >> 4 if x & 1 else byte & 15
                color = TRANSPARENT if index == 0 else palette[index]
                image.putpixel((tile % columns * 8 + x, tile // columns * 8 + y), color)
    return image


def quantize(image):
    """Returns (indices, palette): index 0 is transparent, up to 15 colours follow."""
    opaque = [p for p in image.get_flattened_data() if p != TRANSPARENT]
    reduced = Image.new("RGB", (len(opaque), 1))
    reduced.putdata(opaque)
    reduced = reduced.quantize(15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    flat = reduced.getpalette()[:45]
    palette = [(0, 0, 0)] + [tuple(flat[i:i + 3]) for i in range(0, len(flat), 3)]
    palette += [(0, 0, 0)] * (16 - len(palette))
    it = iter(reduced.get_flattened_data())
    indices = [0 if p == TRANSPARENT else next(it) + 1 for p in image.get_flattened_data()]
    return indices, palette


def gba_tiles(indices, width, height):
    data = bytearray()
    for ty in range(0, height, 8):
        for tx in range(0, width, 8):
            for y in range(8):
                for x in range(0, 8, 2):
                    low = indices[(ty + y) * width + tx + x]
                    high = indices[(ty + y) * width + tx + x + 1]
                    data.append(low | high << 4)
    return bytes(data)


def gba_palette(palette):
    data = bytearray()
    for r, g, b in palette:
        value = r >> 3 | (g >> 3) << 5 | (b >> 3) << 10
        data += bytes((value & 0xFF, value >> 8))
    return bytes(data)


def c_array(name, data):
    lines = [f"const u8 {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    rom = BASEROM.read_bytes()
    small_base = rom_tiles(rom, SMALL_TILES, 8, 2, rom_palette(rom, SMALL_PALETTE))
    out = ['// Generated by tools/rogue_cards.py from the sheets in mod_assets. Do not edit.',
           '#include "types.h"', ""]
    for name, (sheet, box) in CARDS.items():
        picture = Image.open(ROOT / "mod_assets" / sheet).convert("RGB").crop(box)
        big = Image.new("RGB", (32, 32), TRANSPARENT)
        big.paste(picture, ((32 - picture.width) // 2, (32 - picture.height) // 2))
        indices, palette = quantize(big)
        out += [c_array(f"gRogueCard{name}Tiles", gba_tiles(indices, 32, 32)),
                c_array(f"gRogueCard{name}Palette", gba_palette(palette)), ""]

        # The small card: the picture without its border, shrunk into the
        # window under the crown. The value disc in the corner stays on top.
        small = small_base.copy()
        inner = picture.crop((2, 2, picture.width - 2, picture.height - 2)).resize((12, 13), Image.Resampling.BOX)
        for y in range(13):
            for x in range(12):
                target = (2 + x, 14 + y)
                if small.getpixel(target) != (0, 0, 0) or target[0] < 8 or target[1] < 22:
                    small.putpixel(target, inner.getpixel((x, y)))
        indices, palette = quantize(small)
        out += [c_array(f"gRogueCard{name}SmallTiles", gba_tiles(indices, 16, 32)),
                c_array(f"gRogueCard{name}SmallPalette", gba_palette(palette)), ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(CARDS)} cards")


if __name__ == "__main__":
    main()
