game:
  width: 1
  codec: cp1252
  chars:
    0x01: 「
    0x02: 」
    0x03: 『
    0x04: 』
    0x06: ※
    0x08: ♂
    0x09: ♀
    0x0A: ↑
    0x0B: ↓
    0x0C: ←
    0x0D: →
    0x11: ■
    0x12: ♪
    0x15: ★
    0x19: ―
  controls:
    END: [0x00]
    NL: [0x1F]
    HIGHLIGHT: [0x1D]
    PLAIN: [0x1E]
sjis:
  width: 1
  codec: cp932
  controls:
    END: [0x00]
