game:
  width: 1
  codec: cp932
  controls:
    END: [0x00]
    NL: [0x6E, 0x6E]
sjis:
  width: 1
  codec: cp932
  controls:
    END: [0x00]
latin16:
  width: 2
  codec: cp1252
  controls:
    END: [0x0000]
